package main

import (
	"encoding/json"

	"github.com/spf13/cobra"
)

// gstr2b — the static, legal ITC statement, generated by the portal on the 14th.
// It is what comparison-spec §C4 matches against SAP's purchase invoices: which
// supplier documents have actually been filed, and therefore which ITC is safe.

func init() { registerSection(newGSTR2BCmd) }

func newGSTR2BCmd(app *App) *cobra.Command {
	c := &cobra.Command{
		Use:   "gstr2b",
		Short: "GSTR-2B: the ITC statement for a period, document by document",
	}
	c.AddCommand(gstr2bSummaryCmd(app))
	return c
}

// gstr2bSummaryCmd makes both calls the portal's own 2B page makes: the header
// (who this is) and the statement itself. They are emitted together so one
// invocation answers the whole question.
//
// GTR2B-002 ("not generated for this period") is an ANSWER, not a failure: nil
// filers and the current month legitimately have no 2B. It comes back as
// generated=false with the portal's message, exit 0.
func gstr2bSummaryCmd(app *App) *cobra.Command {
	var period string
	c := &cobra.Command{
		Use:   "summary",
		Short: "GSTR-2B for one period: ITC summary plus every supplier document",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			reg, err := app.one()
			if err != nil {
				return err
			}
			if _, err := parsePeriod(period); err != nil {
				return err
			}
			fy := fyOfPeriod(period)
			cl := newClient(reg)

			out := map[string]any{"gstin": reg.GSTIN, "period": period, "fy": fy}

			user, err := cl.do(epGSTR2BUserDtls, nil, qs("rtnprd", period, "fy", fy), nil)
			if err != nil {
				return app.emitError("gstr2b summary", reg.GSTIN, endpointURL(epGSTR2BUserDtls), err)
			}
			if !user.Empty {
				out["userdtls"] = json.RawMessage(user.Raw)
			}

			data, err := cl.do(epGSTR2BData, nil, qs("rtnprd", period), nil)
			if err != nil {
				return app.emitError("gstr2b summary", reg.GSTIN, endpointURL(epGSTR2BData), err)
			}
			if data.Empty {
				out["generated"] = false
				out["note"] = data.Note
				app.logf("%s %s: %s", reg.GSTIN, period, data.Note)
			} else {
				out["generated"] = true
				out["data"] = json.RawMessage(data.Raw)
				if line := gstr2bHeadline(data.Raw); line != "" {
					app.logf("%s %s — %s", reg.GSTIN, period, line)
				}
			}
			return app.emitValue("gstr2b summary", reg.GSTIN, endpointURL(epGSTR2BData), out, gstr2bDocCount(data))
		},
	}
	periodFlag(c, &period)
	return c
}

func gstr2bDocCount(res Result) int {
	if res.Empty {
		return 0
	}
	var v struct {
		Data struct {
			DocData struct {
				B2B []struct {
					Inv []json.RawMessage `json:"inv"`
				} `json:"b2b"`
			} `json:"docdata"`
		} `json:"data"`
	}
	if err := json.Unmarshal(res.Raw, &v); err != nil {
		return 0
	}
	n := 0
	for _, s := range v.Data.DocData.B2B {
		n += len(s.Inv)
	}
	return n
}

// gstr2bHeadline reports the B2B ITC available, which is the number Accounts
// compares with what was claimed in 3B table 4.
func gstr2bHeadline(raw json.RawMessage) string {
	var v struct {
		Data struct {
			ItcSumm struct {
				ItcAvl struct {
					NonRevSup struct {
						B2B taxHeads `json:"b2b"`
					} `json:"nonrevsup"`
				} `json:"itcavl"`
			} `json:"itcsumm"`
		} `json:"data"`
	}
	if err := json.Unmarshal(raw, &v); err != nil {
		return ""
	}
	b := v.Data.ItcSumm.ItcAvl.NonRevSup.B2B
	if b.Txval == 0 && b.total() == 0 {
		return ""
	}
	return "B2B taxable " + inr(b.Txval) + ", ITC available " + inr(b.total())
}
