import type { Day, Mark4Model, Run, Scenario, SourceStamp } from "./types.ts";
export type FactoryRun = { firstStartedAt?: string | null; timingSegments?: { startedAt: string | null; endedAt: string | null; note: string | null }[]; id: string; code: string | null; product: string | null; date: string | null; sourceUpdatedAt: string | null; liveStatus: string; activeSegment: { startedAt: string | null; endedAt: string | null; isActive: boolean } | null; producedPieces: number | null; producedLitres: number | null; targetPieces?: number | null; targetLitres?: number | null; recordedRunningMinutes?: number | null; ratedSpeedPiecesPerHour?: number | null; quantityBasis: string };
export type FactoryLine = { line: string; coverage: "reported" | "unreported" | "conflict"; status: "RUNNING" | "STOPPED" | "PAUSED" | "BREAKDOWN" | "COMPLETED" | "UNKNOWN"; runs: FactoryRun[]; note: string };
export type FactoryNow = { version: 1; revision: string; attemptedAt: string; asOf: string | null; ok: boolean; complete: boolean; expectedRefreshSeconds: number; date: string; lines: FactoryLine[]; error: string | null };
export type ShiftBaseline = { factoryAtCapture?: { asOf: string; complete?: boolean; lines: { line: string; coverage: FactoryLine["coverage"]; runs: { id: string; code: string | null; pieces: number | null }[] }[] }; version: 1; id: string; date: string; timeZone: "Asia/Kolkata"; capturedAt: string; inputAsOf: string; inputRevision: string; engineVersion: string; captureKind: "first_capture" | "start_of_day"; scenario: Scenario; day: Day; sources: SourceStamp[]; feedStatus: Mark4Model["meta"]["feedStatus"] };
export type ShiftCandidate = Omit<Run, "setupHours"> & { setupHours: number | null; setupBasis: "continuation" | "product_change" | "unknown" };
export type ShiftAdvice = { action: "continue" | "switch_next" | "investigate" | "cannot_verify"; title: string; reason: string; candidate: ShiftCandidate | null; conditional: boolean; basedOn: { source: string; asOf: string | null; status: string }[]; limitations: string[] };
export type ShiftRow = { line: string; actual: FactoryLine; plannedRuns: Run[]; plannedProgress: { code: string; madePieces: number | null; remainingPieces: number | null }[]; match: "matches" | "different" | "unverifiable" | "not_planned"; advice: ShiftAdvice };
export type ShiftBoard = { version: 1; date: string; generatedAt: string; refreshSeconds: 60; factory: FactoryNow; baseline: ShiftBaseline | null; baselineError: string | null; rows: ShiftRow[] };
