// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "accounts",
		Short:       "Accounts receivable — customer aging (oil AR flat, mart & beverages pre-bucketed), on-account payments",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountsAgingBeveragesCmd(flags))
	cmd.AddCommand(newAccountsAgingMartCmd(flags))
	cmd.AddCommand(newAccountsAgingOilCmd(flags))
	cmd.AddCommand(newAccountsClaimsCmd(flags))
	cmd.AddCommand(newAccountsOpenPaymentsCmd(flags))
	return cmd
}
