// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInventoryCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "inventory",
		Short:       "Inventory & production — live on-hand stock, non-moving/ageing stock, production feasibility & catalogues",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInventoryDailyProductionCmd(flags))
	cmd.AddCommand(newInventoryNonMovingCmd(flags))
	cmd.AddCommand(newInventoryNonMovingDrillCmd(flags))
	cmd.AddCommand(newInventoryProductionFeasibilityCmd(flags))
	cmd.AddCommand(newInventoryProductionFgListCmd(flags))
	cmd.AddCommand(newInventoryProductionWarehousesCmd(flags))
	cmd.AddCommand(newInventoryReconciliationCmd(flags))
	cmd.AddCommand(newInventoryReconciliationLedgersCmd(flags))
	cmd.AddCommand(newInventoryStockCmd(flags))
	return cmd
}
