// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMasterdataCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "masterdata",
		Short:       "Reference master data — customer master, saved realise-calculator rate lists, and the FG item master.",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMasterdataCalculatorItemsCmd(flags))
	cmd.AddCommand(newMasterdataCustomerMasterCmd(flags))
	cmd.AddCommand(newMasterdataRateListCmd(flags))
	return cmd
}
