// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newItemsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "items",
		Short:       "Manage items command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newItemsGetFgCmd(flags))
	cmd.AddCommand(newItemsGetRmCmd(flags))
	cmd.AddCommand(newItemsGetRmSummaryCmd(flags))
	cmd.AddCommand(newItemsGetRmVarietiesCmd(flags))
	return cmd
}
