// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newStockStatusCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "stock-status",
		Short:       "Manage stock status command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newStockStatusGetCmd(flags))
	cmd.AddCommand(newStockStatusGetContractualHistoryCmd(flags))
	cmd.AddCommand(newStockStatusGetDebitEntriesCmd(flags))
	cmd.AddCommand(newStockStatusGetDebitInsightsCmd(flags))
	cmd.AddCommand(newStockStatusGetIdCmd(flags))
	cmd.AddCommand(newStockStatusGetStockDashboardCmd(flags))
	cmd.AddCommand(newStockStatusGetStockInsightsCmd(flags))
	cmd.AddCommand(newStockStatusGetStockLogsCmd(flags))
	cmd.AddCommand(newStockStatusGetStockSummaryCmd(flags))
	cmd.AddCommand(newStockStatusGetVehicleReportCmd(flags))
	return cmd
}
