// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTankCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "tank",
		Short:       "Manage tank command groups",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTankGetCmd(flags))
	cmd.AddCommand(newTankGetCapacityInsightsCmd(flags))
	cmd.AddCommand(newTankGetCodeCmd(flags))
	cmd.AddCommand(newTankGetInItemsCmd(flags))
	cmd.AddCommand(newTankGetItemWiseAverageCmd(flags))
	cmd.AddCommand(newTankGetItemWiseSummaryCmd(flags))
	cmd.AddCommand(newTankGetItemsCmd(flags))
	cmd.AddCommand(newTankGetLogCmd(flags))
	cmd.AddCommand(newTankGetSummaryCmd(flags))
	return cmd
}
