#!/usr/bin/env python3
"""PHASE 8 — generate the read-only Flipkart Cobra CLI from the READ allowlist.

READ-ONLY generator. Emits Go sources into ../cli/. Wires ONLY READ/READ_FILE
endpoints as GET commands; transport is GET-only so nothing else can be sent.
"""
import os, csv, collections, re, json

HERE = os.path.dirname(os.path.abspath(__file__))
CLI = os.path.join(HERE, '..', 'cli')
os.makedirs(CLI, exist_ok=True)

# section key -> (group dir, Title) — reuse the vault mapping for CLI group names
S = json.load(open(os.path.join(HERE, 'sections.json')))

def sect_cli_name(key):
    # e.g. seller:report-centre -> report-centre ; vendorhub:vendor-analytics -> vendor-analytics
    return key.split(':', 1)[1]

# load read-safe endpoints
reads = []
with open(os.path.join(HERE, 'wired-reads.tsv')) as fh:
    r = csv.DictReader(fh, delimiter='\t')
    for row in r:
        reads.append(row)

# assign each read row to its section (recompute like classify.section_of, but we
# already have sections.json — build a path->section index)
path2sec = {}
for key, rows in S.items():
    for rec in rows:
        path2sec[(rec['host'], rec['path'])] = key

# build command entries: unique (group, cmdname)
def cmdname(path):
    segs = [s for s in path.strip('/').split('/') if s and not s.startswith('{')]
    # drop leading api version/prefix noise
    segs = [s for s in segs if s not in ('napi', 'api', 'v1', 'v2', 'v3', 'v0', 'vendor', 'vendor-p', 'fed-ads', 'sellers')]
    name = '-'.join(segs[-3:]) if segs else 'root'
    name = re.sub(r'[^a-zA-Z0-9-]', '-', name).strip('-').lower() or 'root'
    return name[:48]

entries = []  # (group, name, method, host, path, cls, desc)
seen = set()
for row in reads:
    host, path, cls, method = row['host'], row['path'], row['class'], row['method']
    key = path2sec.get((host, path))
    if not key:
        # fallback surface grouping
        key = ('vendorhub:vendor-platform' if 'vendorhub' in row['surface'] else 'seller:misc')
    group = sect_cli_name(key)
    name = cmdname(path)
    g = (group, name)
    n = name; i = 2
    while (group, n) in seen:
        n = f'{name}-{i}'; i += 1
    seen.add((group, n))
    m = 'GET'  # transport is GET-only; every wired call is a GET
    entries.append((group, n, m, host, path, cls, row.get('const', '')))

entries.sort()
groups = collections.OrderedDict()
for e in entries:
    groups.setdefault(e[0], []).append(e)

# ---- registry.go ----
def gostr(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'

reg = []
reg.append('package main\n')
reg.append('// GENERATED by captures/gen_cli.py from the READ allowlist. Do not hand-edit.')
reg.append('// Every entry is a READ or READ_FILE endpoint, wired as a GET. Transport is')
reg.append('// GET-only (see client.go), so no write can ever be issued from this table.\n')
reg.append('type Endpoint struct {')
reg.append('\tGroup, Name, Method, Host, Path, Class, Const string')
reg.append('}\n')
reg.append('var registry = []Endpoint{')
for (group, name, method, host, path, cls, const) in entries:
    reg.append('\t{Group: %s, Name: %s, Method: %s, Host: %s, Path: %s, Class: %s, Const: %s},' % (
        gostr(group), gostr(name), gostr(method), gostr(host), gostr(path), gostr(cls), gostr(const)))
reg.append('}')
open(os.path.join(CLI, 'registry.go'), 'w').write('\n'.join(reg) + '\n')

print('endpoints wired:', len(entries), 'groups:', len(groups))
for g, es in groups.items():
    print(f'  {g:26} {len(es)}')
