"use client";
import { useEffect, useState } from "react";
import type { DispatchResponse } from "../lib/dispatch-types";
import { selectDispatch, planningTonnes, operationalCompany, type CompanyFilter } from "../lib/dispatch-board";
import styles from "./DispatchBoard.module.css";
const number = (value: number | null, digits = 2) => value === null ? "Unknown" : value.toLocaleString("en-IN", { maximumFractionDigits: digits });
const time = (value: string) => new Date(value).toLocaleString("en-IN", { timeZone: "Asia/Kolkata", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }) + " IST";
const today = () => new Date().toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" });
const companyNames = { JIVO_OIL: "Oil book", JIVO_MART: "Mart book", JIVO_BEVERAGES: "Beverages book" };
export default function DispatchBoard() {
  const [response, setResponse] = useState<DispatchResponse | null>(null);
  const [selected, setSelected] = useState(today);
  const [filter, setFilter] = useState<CompanyFilter>("all");
  useEffect(() => {
    let active = true;
    const controller = new AbortController();
    async function refresh() {
      try { const result = await fetch("/api/dispatch-board", { cache: "no-store", signal: controller.signal }); if (!result.ok) throw new Error("Read failed"); const payload = await result.json() as DispatchResponse; if (active) setResponse(payload); }
      catch { if (active) setResponse(previous => ({ data: previous?.data ?? null, storage: previous?.storage ?? null, status: previous?.data ? "stale" : "unavailable", error: "Dispatch refresh failed; any retained records keep their original observation time." })); }
    }
    void refresh(); const timer = setInterval(() => void refresh(), 60000);
    return () => { active = false; controller.abort(); clearInterval(timer); };
  }, []);
  const data = response?.data;
  const view = data ? selectDispatch(data, selected, filter) : null;
  const overall = data ? selectDispatch(data, selected, "all") : null;
  const covered = !!view?.day;
  const known = overall?.litres ?? null;
  const progress = known === null ? null : Math.min(100, known / 1000);
  return <section className={styles.board} aria-label="Actual factory dispatch">
    <div className={styles.heading}><div><h2>Actual dispatch · Wellness + Mart</h2><p className={styles.note}>Recorded truck departures. Beverages stays separate. FG storage uses only Wellness BH-BT and BH-PF.</p></div><span className={styles.status}>{response ? response.status === "fresh" ? "Source current" : response.status === "incomplete" ? "Partial source" : response.status === "stale" ? "Stale source" : "Source unavailable" : "Reading source…"}</span></div>
    {response?.error && <p className={styles.warning} role="status">{response.error}</p>}
    {data && <p className={styles.note}>Source read {time(data.asOf)} · actual gate-out dates · <a href="https://ji.jivo.in/dispatch" target="_blank" rel="noreferrer">Open Factory Dispatch</a>. {data.coverage.listRows.toLocaleString("en-IN")} gate records checked across {data.coverage.pages} pages.</p>}
    <div className={styles.controls}><label>Dispatch date (IST)<input type="date" value={selected} min={data?.coverage.fromDate} max={data?.coverage.toDate ?? today()} onChange={e => setSelected(e.target.value)} /></label><button className="subtle-button" onClick={() => setSelected(today())}>Today</button><label>Company view<select value={filter} onChange={e => setFilter(e.target.value as CompanyFilter)}><option value="all">Wellness + Mart total</option><option value="wellness">Wellness</option><option value="mart">Mart</option><option value="unknown">Ownership unresolved</option><option value="beverages">Beverages · separate</option></select></label></div>
    {!covered && <p className={styles.warning}>{data ? "This date is outside the verified source coverage. Its dispatch total is unknown." : "Waiting for actual dispatch records. Missing data is not zero dispatch."}</p>}
    <div className={styles.stats}><Stat label="Wellness + Mart total" value={`${number(planningTonnes(known))} T`} note={known === null ? "Not established" : `${number(known)} source litres · ${overall?.trips.length ?? 0} trips`} /><Stat label="Wellness" value={`${number(planningTonnes(overall?.wellnessLitres ?? null))} T`} note="Operational warehouse classification" /><Stat label="Mart" value={`${number(planningTonnes(overall?.martLitres ?? null))} T`} note="Includes Gupta GP-FG / GP-FGM" /><Stat label="Left BH-BT + BH-PF" value={`${number(planningTonnes(overall?.storageLitres ?? null))} T`} note="Dispatch from the production godowns" /></div>
    {overall?.unclassifiedLitres !== 0 && covered && <p className={styles.warning}>Ownership unresolved: {number(overall?.unclassifiedLitres ?? null)} L. These loads remain in the overall total but are not assigned to Wellness or Mart. Conflicting source company and warehouse records need confirmation.</p>}
    <p className={styles.note}><strong>Daily aim: 100 planning tonnes across Wellness + Mart.</strong> {known === null ? "Progress unknown." : known >= 100000 ? `Aim exceeded by ${number((known-100000)/1000)} T.` : `${number((100000-known)/1000)} T remaining.`} This aim is not a confirmed truck booking.</p>
    {progress !== null && <div className={styles.progress} role="progressbar" aria-label="Wellness and Mart daily dispatch aim" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${progress}%` }} /></div>}
    <p className={styles.note}>Planning tonnes = recorded litres ÷ 1,000, not weighbridge weight. A shared factory arrival counts once in the overall trip count, even when it carries both companies. Company trip counts should not be added.</p>
    <h3>{filter === "all" ? "Every Wellness + Mart trip" : filter === "beverages" ? "Beverages trips · excluded from the 100 T aim" : `${filter === "unknown" ? "Ownership unresolved" : filter === "mart" ? "Mart" : "Wellness"} loads by trip`}</h3>
    {view && covered && view.trips.length === 0 && <p className={styles.warning}>{response?.status === "fresh" ? "No recorded departures for this selection as of the source read." : "No matching records in this incomplete or stale read. This does not establish zero departures."}</p>}
    <div className={styles.scroll}><table className={styles.table}><thead><tr><th scope="col">Trip / gate records</th><th scope="col">Departure</th><th scope="col">Companies / warehouses</th><th scope="col" className={styles.numeric}>Planning T</th><th scope="col" className={styles.numeric}>Source litres</th><th scope="col">Load details</th></tr></thead><tbody>{view?.trips.map(trip => <tr key={trip.id}><td><strong>{trip.id}</strong><small>{trip.entries.map(entry => entry.reference).join(" · ")}</small><small>{trip.identityBasis}</small></td><td>{time(trip.departedAt)}</td><td>{[...new Set(trip.entries.flatMap(entry => entry.items.map(item => operationalCompany(entry,item))))].join(" + ")}<small>{[...new Set(trip.entries.flatMap(entry => entry.warehouseLitres.map(row => row.warehouse)))].join(", ") || "Warehouse not recorded"}</small></td><td className={styles.numeric}>{number(planningTonnes(trip.litres),3)}</td><td className={styles.numeric}>{number(trip.litres)}</td><td><details><summary>View materials and evidence</summary>{trip.entries.map(entry => <div key={entry.id}><p><strong>{entry.reference}</strong> · {companyNames[entry.company]} · {entry.documentCount} documents · {number(entry.litres)} L</p>{entry.issues.map(issue => <p key={issue}>{issue}</p>)}<table className={styles.table}><thead><tr><th>Item / warehouse</th><th>Source quantity</th><th>Litres / business</th></tr></thead><tbody>{entry.items.map((item,index) => <tr key={`${entry.id}-${index}`}><td>{item.name ?? item.code ?? "Item not named"}<small>{item.code} · {item.warehouse ?? "Warehouse unknown"}</small></td><td>{number(item.quantity)} {item.uom ?? "unit unknown"}</td><td>{number(item.litres)} L<small>{operationalCompany(entry,item)}</small></td></tr>)}</tbody></table></div>)}</details></td></tr>)}</tbody></table></div>
    <details className={styles.details}><summary>Company classification and source totals</summary><p className={styles.note}>Your operational rule assigns GP-FG and GP-FGM to Mart. Raw Oil-book records can therefore appear under Mart here; the original source company is retained in each load’s evidence. Other loads retain their source company, except a conflicting Mart record at BH-BT or BH-PF: ownership stays unresolved. Unknown item splits remain unknown.</p><p className={styles.note}>For {selected}: source Oil book {number(view?.day?.wellnessLitres ?? null)} L; source Mart book {number(view?.day?.martLitres ?? null)} L; Beverages {number(view?.day?.beveragesLitres ?? null)} L (separate).</p></details>
    <details className={styles.details}><summary>Daily dispatch history</summary><div className={styles.scroll}><table className={styles.table}><thead><tr><th>Date</th><th className={styles.numeric}>Wellness + Mart L</th><th className={styles.numeric}>Trips</th><th className={styles.numeric}>BH-BT + BH-PF L</th><th className={styles.numeric}>Beverages L · separate</th><th>Evidence</th></tr></thead><tbody>{data?.days.slice().reverse().map(day => <tr key={day.date}><td><button className="text-button" onClick={() => setSelected(day.date)}>{day.date}</button></td><td className={styles.numeric}>{number(day.combinedLitres)}</td><td className={styles.numeric}>{day.tripCount}</td><td className={styles.numeric}>{number(day.wellnessStorageLitres)}</td><td className={styles.numeric}>{number(day.beveragesLitres)}</td><td>{day.complete ? "Recorded" : "Partial details"}</td></tr>)}</tbody></table></div></details>
    <section className={styles.details} aria-label="Recorded godown stock"><h3>BH-BT + BH-PF · source stock beside the simulation</h3>{response?.storage ? <><div className={styles.stats}><Stat label="Recorded FG balance" value={`${number(response.storage.recordedFgLitres)} L`} note={`Observed ${time(response.storage.asOf)}`} /><Stat label="Previous recorded balance" value={`${number(response.storage.previousObservation?.recordedFgLitres ?? null)} L`} note={response.storage.previousObservation ? time(response.storage.previousObservation.observedAt) : "No earlier observation archived yet"} /><Stat label="Estimated billed, waiting" value={`${number(response.storage.legacyWaitingEstimateLitres)} L`} note="Legacy model estimate; not verified BH-only stock" /><Stat label="Physical closing variance" value="Unknown" note="Matching physical stock and movement evidence needed" /></div><p className={styles.note}>{!response.storage.ok || Date.now()-Date.parse(response.storage.asOf)>Math.max(3600,response.storage.expectedObservationSeconds)*2000 ? "Stock reading is stale or its refresh failed. " : ""}{response.storage.note}</p><ul className={styles.note}>{response.storage.physicalReconciliation.missing.map(item => <li key={item}>{item}</li>)}</ul></> : <p className={styles.warning}>The dated stock evidence could not be read. Dispatch remains available separately; physical closing stock is unknown.</p>}</section>
    <div className={styles.warning}><strong>Physical closing-stock reconciliation is not established.</strong><p className={styles.note}>Opening stock + production + other movements − actual departures = calculated closing stock. We still need matching stock observation times, complete movements, and confirmation of when the factory stock balance deducts a dispatch. Actual departures above are not subtracted again from a newer stock snapshot. The estimated billed-waiting figure below is not a verified physical count.</p></div>
  </section>;
}
function Stat({ label, value, note }: { label: string; value: string; note: string }) { return <div className={styles.stat}><p>{label}</p><strong>{value}</strong><small>{note}</small></div>; }
