"use client";

import { useState } from "react";
import type { Mark4Model, Scenario } from "../lib/types";

const number = (value: number) => value.toLocaleString("en-IN", { maximumFractionDigits: 1 });
const date = (value: string | null | undefined) => value ? new Date(value.length === 10 ? `${value}T12:00:00Z` : value).toLocaleDateString("en-IN", { day: "numeric", month: "short" }) : "Not supplied";
const timestamp = (value: string | null | undefined) => value ? new Date(value.length === 10 ? `${value}T00:00:00+05:30` : value).toLocaleString("en-IN", { timeZone: "Asia/Kolkata", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }) + " IST" : "Not supplied";
const money = (value: number) => `₹${(value / 10000000).toFixed(2)} Cr`;
const stageNames: Record<string, string> = { ordered: "Ordered; not yet at gate", loading: "Being loaded", in_transit: "On the way", arrived: "At factory", qc_pending: "At factory; QC pending", accepted_unposted: "QC accepted; stock posting unresolved", usable: "Usable stock", rejected: "Rejected", cancelled: "Cancelled", conflict: "Needs reconciliation" };

export default function MaterialSupply({ model, busy, onScenario }: { model: Mark4Model; busy: boolean; onScenario: (scenario: Scenario) => Promise<void> }) {
  const [query, setQuery] = useState("");
  const [lotLimit, setLotLimit] = useState(25);
  const [stockLimit, setStockLimit] = useState(25);
  const [actionLimit, setActionLimit] = useState(25);
  const [showHistory, setShowHistory] = useState(false);
  const [sourceLimit, setSourceLimit] = useState(25);
  const supply = model.materialSupply;
  if (!supply) return null;
  const name = (code: string) => model.materials.find(row => row.code === code)?.name ?? code;
  const visible = (code: string) => `${code} ${name(code)}`.toLowerCase().includes(query.toLowerCase());
  const comparison = supply.comparison;
  const sourceRows = [...supply.coverage.datasets].sort((a, b) => Number(a.id.startsWith("receipt-")) - Number(b.id.startsWith("receipt-")));
  const sourceName = (id: string) => id === "factory_purchase_orders" ? "Factory purchase orders" : id.startsWith("stock-") ? `Factory stock · ${id.slice(6)}` : id.startsWith("gate-") ? `Factory arrivals · ${id.slice(5)}` : id.startsWith("exim-") ? `EXIM · ${id.slice(5).replaceAll("_", " ")}` : `Receipt evidence · ${id.replace(/^receipt-(detail|link)-/, "")}`;
  const stockRows = Object.entries(supply.stock.byItem).filter(([code]) => visible(code));
  const lotRows = supply.lots.filter(row => visible(row.code) && (showHistory || !["usable", "cancelled", "rejected"].includes(row.stage))).sort((a, b) => Number(model.materials.some(row => row.code === b.code && row.shortage > 0)) - Number(model.materials.some(row => row.code === a.code && row.shortage > 0)));
  const actionRows = supply.requiredActions.filter(row => visible(row.code)).sort((a, b) => Number(b.affectedProducts.length > 0) - Number(a.affectedProducts.length > 0));
  return <section className="card material-supply" aria-label="Live material supply">
    <div className="incoming-head"><h2>What is available, and what is coming</h2><p>Factory orders, gate arrivals, QC and usable stock are reconciled before the schedule is rebuilt. An order is not stock, and arrival is not QC clearance.</p></div>
    <p className="source-text">Supply checked {supply.asOf ? new Date(supply.asOf).toLocaleString("en-IN") : "at an unknown time"}. {supply.coverage.complete ? "All required datasets returned complete reads." : "Some source reads are incomplete. Unknown quantities or dates remain unresolved."}</p>
    <label className="field"><span>Dates to use for production</span><select aria-label="Supply evidence mode" disabled={busy} value={model.scenario.supplyMode ?? "expected"} onChange={event => void onScenario({ ...model.scenario, supplyMode: event.target.value as Scenario["supplyMode"] })}><option value="expected">Source arrivals + estimated QC time</option><option value="recorded">Recorded usable dates only</option></select></label>
    <label className="check-field"><input type="checkbox" disabled={busy} checked={model.scenario.includePackagingEstimates ?? true} onChange={event => void onScenario({ ...model.scenario, includePackagingEstimates: event.target.checked })} /><span>Use temporary packaging arrival estimates<br /><small>For existing outstanding orders without a dependable date. These are our estimates, awaiting the team's confirmation tomorrow; they expire automatically and are never supplier promises.</small></span></label>
    <p>Oil arrival dates come from EXIM. Matching receiving-to-QA hours estimate quality clearance, conditional on no further Stores delay. Temporary packaging estimates are separately labelled. A new purchase is not counted until an order is recorded. After estimated QC, a run can use the remaining shift hours on that same date.</p>
    {comparison && <div className="supply-comparison"><div><strong>With evidenced expected supply</strong><p>{number(comparison.expected.plannedLitres)} L · {money(comparison.expected.knownPlannedValue)} priced{comparison.expected.unvaluedLitres > 0 ? ` + ${number(comparison.expected.unvaluedLitres)} L unpriced` : ""}</p></div><div><strong>Recorded usable dates only</strong><p>{number(comparison.recorded.plannedLitres)} L · {money(comparison.recorded.knownPlannedValue)} priced{comparison.recorded.unvaluedLitres > 0 ? ` + ${number(comparison.recorded.unvaluedLitres)} L unpriced` : ""}</p></div></div>}
    <p>{number(model.summary.conditionalSupplyLitres ?? 0)} L of planned runs use estimated supply. A whole run is marked conditional when any material in it depends on an estimated date. Suggested new purchases are not counted as placed orders.</p>
    <p className="callout">A day with no planned filling means the selected evidence does not yet support a run. It is not a prediction that deliveries or factory work will stop.</p>
    <details><summary>Source refresh times</summary><div className="table-wrap"><table><thead><tr><th>Source</th><th>Last successful read</th><th>Latest attempt</th><th>Coverage</th></tr></thead><tbody>{sourceRows.slice(0, sourceLimit).map(row => <tr key={row.id}><td>{sourceName(row.id)}<small>{row.note}</small></td><td>{row.asOf ? new Date(row.asOf).toLocaleString("en-IN") : "Unknown"}</td><td>{row.attemptedAt ? new Date(row.attemptedAt).toLocaleString("en-IN") : "Unknown"}</td><td>{row.ok && row.complete ? "Complete read" : "Incomplete / failed"}<small>Refresh interval {number(row.expectedRefreshSeconds / 60)} min</small></td></tr>)}</tbody></table></div>{sourceRows.length > sourceLimit && <button type="button" className="text-button" onClick={() => setSourceLimit(sourceLimit + 25)}>Show 25 more receipt checks ({sourceRows.length} total)</button>}</details>
    <div className="toolbar"><input className="search" aria-label="Search incoming supply" placeholder="Find incoming material or item code" value={query} onChange={event => setQuery(event.target.value)} /></div>
    <p>Opening oil uses EXIM only. Factory oil balances are excluded. Packaging uses BH-BS, BH-PM, BH-NM, BH-SDL, GP-NM, GP-PM and GP-FG. BH-OT, BH-PP, BH-WST and GP-FGM are excluded.</p>{!!supply.stock.unmappedOils?.length && <p>EXIM oil awaiting exact material mapping: {supply.stock.unmappedOils.map(row => `${row.name}: ${number(row.quantity)} ${row.unit}`).join("; ")}. These quantities are visible but cannot feed a recipe yet.</p>}<>{!!supply.unmappedShipments?.length && <p>Incoming EXIM oil awaiting exact material mapping: {supply.unmappedShipments.map(row => `${row.name}: ${row.quantity === null ? "quantity unknown" : number(row.quantity)} ${row.unit}; ${stageNames[row.stage] ?? row.stage}; source ETA ${date(row.eta)}`).join("; ")}. Source reads may be complete while these material identities remain unresolved. These loads are excluded from production.</p>}</><details open><summary>Usable stock now</summary><div className="table-wrap"><table><thead><tr><th>Material</th><th>Usable quantity</th><th>Stock read</th></tr></thead><tbody>{stockRows.slice(0, stockLimit).map(([code, quantity]) => <tr key={code}><td>{name(code)}<small>{code}</small></td><td>{number(quantity)} {model.materials.find(row => row.code === code)?.unit ?? "source units"}</td><td>{date(supply.stock.asOf)}</td></tr>)}</tbody></table></div>{stockRows.length > stockLimit && <button type="button" className="text-button" onClick={() => setStockLimit(stockLimit + 25)}>Show 25 more stock items ({stockRows.length} total)</button>}<p>{supply.stock.conflicts.length} unresolved stock checks; {supply.stock.excludedWarehouses.length} excluded warehouse entries. Missing stock is not proof of zero stock.</p></details>
    <details open><summary>Existing orders and loads</summary><label className="check-field"><input type="checkbox" checked={showHistory} onChange={event => setShowHistory(event.target.checked)} />Include posted, rejected and cancelled history</label><div className="table-wrap"><table><thead><tr><th>Material and source</th><th>Quantity / current stage</th><th>Source arrival</th><th>Ready for production (IST)</th><th>Used in this plan?</th></tr></thead><tbody>{lotRows.slice(0, lotLimit).map(lot => {
      const receipt = supply.expectedReceipts.find(row => row.lotId === lot.id && row.basis !== "supplier_item_history" && (row.confidence === "recorded" || (row.timingVersion === 1 || row.timingVersion === 2) || row.basis === "temporary_packaging_estimate"));
      const event = model.inboundEvents.find(row => row.id === lot.id);
      const order = supply.orders.find(row => row.id === lot.orderId);
      return <tr key={lot.id}><td>{name(lot.code)}<small>{lot.code} · {lot.id}</small>{order && <small>Order {order.id}: {number(order.orderedQty)} {order.unit}; book received {number(order.bookReceivedQty)}; outstanding {number(order.outstandingQty)}. {order.reconciliationComplete === false || order.notYetAtGateBasis === "unreconciled_upper_bound" ? `As much as ${number(order.notYetAtGateQty)} ${order.unit} may still be undelivered; receipt matching needs reconciliation.` : `${number(order.notYetAtGateQty)} ${order.unit} not yet at gate.`}</small>}</td><td>{number(lot.quantity)} {lot.unit}<small>{stageNames[lot.stage] ?? lot.stage}</small><small>{lot.reason}</small></td><td>{date(receipt?.arrivalExpected ?? lot.arrivalDate)}{receipt?.arrivalEarliest && receipt.arrivalLatest && <small>{date(receipt.arrivalEarliest)}–{date(receipt.arrivalLatest)}</small>}</td><td>{receipt?.usableExpected ? <>{timestamp(receipt.readyAt ?? receipt.qaEstimatedAt ?? receipt.usableExpected)}{receipt.basis === "temporary_packaging_estimate" && <small>Temporary estimate · valid through {date(receipt.temporaryUntil)}</small>}<small>Window {date(receipt.usableEarliest)}–{date(receipt.usableLatest)}</small><small>{receipt.confidence === "recorded" ? "Recorded date" : `Estimate from ${number(receipt.sampleCount)} observations`}</small>{receipt.historyFrom && <small>History {date(receipt.historyFrom)}–{date(receipt.historyTo)}</small>}<small>{receipt.qaMedianHours != null && <>Receiving to QA: {number(receipt.qaMedianHours)} hours (median). Estimated QA: {receipt.qaEstimatedAt ? new Date(receipt.qaEstimatedAt).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }) : "unknown"} IST. {receipt.arrivalTimeKnown ? "Arrival time recorded." : "Arrival time missing; end of IST day assumed."} Stores release: {receipt.storesReleaseAt ?? "not recorded"}.</>}</small><small>{receipt.note}</small><details><summary>Evidence</summary>{receipt.evidenceIds.join(" · ")}</details></> : <>Unknown — needs confirmation</>}</td><td>{event?.included ? `Expected usable ${timestamp(event.readyAt ?? event.appliedAt)}${event.conditional ? " (conditional)" : ""}` : "Not added as future stock"}<small>{event?.reason}</small></td></tr>;
    })}</tbody></table></div>{lotRows.length > lotLimit && <button type="button" className="text-button" onClick={() => setLotLimit(lotLimit + 25)}>Show 25 more loads ({lotRows.length} total)</button>}</details>
    <details open><summary>What needs action</summary>{actionRows.slice(0, actionLimit).map(action => <article className="supply-action" key={action.id}><strong>{name(action.code)} · {action.quantity === null ? "Quantity unresolved" : number(action.quantity)} {action.unit}</strong><p>{action.reason}</p><p><strong>{action.ownerRole}:</strong> {action.requiredConfirmation}</p><p>First blocked use: {date(action.firstNeeded)}. {action.affectedProducts.length ? action.affectedProducts.map(product => `${product.name} (${product.code}), ${date(product.dates[0])}`).join("; ") : "No affected run is currently identified; this source gap still needs resolution."}</p><small>{action.orderId ? `Order ${action.orderId}. ` : ""}{action.evidenceIds.join(" · ")}</small></article>)}{actionRows.length > actionLimit && <button type="button" className="text-button" onClick={() => setActionLimit(actionLimit + 25)}>Show 25 more actions ({actionRows.length} total)</button>}</details>
  </section>;
}
