// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"jivo-factory-pp-cli/internal/cli"
	"jivo-factory-pp-cli/internal/client"
	"jivo-factory-pp-cli/internal/cliutil"
	"jivo-factory-pp-cli/internal/config"
	"jivo-factory-pp-cli/internal/mcp/cobratree"
	"jivo-factory-pp-cli/internal/store"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	// Code-orchestration mode — the full surface is covered by two tools
	// (<api>_search + <api>_execute). Endpoint-mirror tools are suppressed.
	RegisterCodeOrchestrationTools(s)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		default:
			// READ-ONLY LAW (jivogpt): this CLI never mutates JIVO source
			// systems. The spec is GET-only; refuse every write method by
			// construction so no MCP tool can ever open a write path.
			return mcplib.NewToolResultError("read-only CLI: method " + method + " is not permitted (GET only, per the JivoGPT READ-ONLY LAW)"), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("authentication error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: the API rejected the request — this usually means auth is missing or invalid." +
					"\n      Set your API key: export JIVO_FACTORY_TOKEN=<your-key>" +
					"\n      Run 'jivo-factory-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: check your token." +
					"\n      Set it with: export JIVO_FACTORY_TOKEN=<your-key>" +
					"\n      Run 'jivo-factory-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: your credentials are valid but lack access to this resource." +
					"\n      Set it with: export JIVO_FACTORY_TOKEN=<your-key>" +
					"\n      Run 'jivo-factory-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "jivo-factory-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "jivo-factory-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "jivo-factory",
		"description": "Read-only access to every live endpoint of JIVO's factory system across all three companies",
		"archetype":   "crm",
		"tool_count":  386,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion jivo-factory-pp-cli binary.",
		"auth": map[string]any{
			"type": "bearer_token",
			"env_vars": []map[string]any{
				{
					"name":        "JIVO_FACTORY_TOKEN",
					"kind":        "per_call",
					"required":    true,
					"sensitive":   true,
					"description": "Set to your API credential.",
				},
			},
		},
		"resources": []map[string]any{
			{
				"name":        "accounts",
				"description": "The 'platform' group is the plumbing the rest of the factory app sits on: who you are, who else exists",
				"endpoints":   []string{"departments", "me", "users"},
				"syncable":    true,
			},
			{
				"name":        "activity-center",
				"description": "The activity feed behind the app's home screen — what each user did today and what the whole plant did today",
				"endpoints":   []string{"my-today", "team-today"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "attendance",
				"description": "This group covers three small, separate parts of the gate operation.",
				"endpoints":   []string{"attendance-employees", "attendance-export", "attendance-records"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "barcode",
				"description": "This is JIVO's carton-level traceability system — the barcode that gets stuck on every box coming off a filling line",
				"endpoints":   []string{"activity", "activity-recent", "box", "box-history", "boxes", "dispatch-report-detail", "dispatch-reports", "dispatch-reports-boxes", "dispatch-reports-pallets", "dispatch-reports-rejected-scans", "dispatch-sap-sync-logs", "dispatch-scan-logs", "dispatch-session", "dispatch-sessions", "dispatch-sessions-active", "dispatch-sessions-closed", "dispatch-sessions-completed", "dispatch-sessions-from-bill", "dispatch-settings", "intercompany-dashboard", "intercompany-trace", "intercompany-transfer", "intercompany-transfers", "intercompany-warehouses", "item-detail", "items-oitm", "lookup", "loose", "loose-item", "loose-summary", "pallet", "pallet-history", "pallets", "print-history", "production-release-oil", "scan-history", "verify-request", "verify-requests", "voided-boxes", "voided-pallets"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "blowing",
				"description": "The blowing module tracks JIVO's own PET bottle-making",
				"endpoints":   []string{"audit", "breakdown-categories", "buy-prices", "cost-rates", "machines", "make-vs-buy", "preform-specs", "rate-configs", "report-daily", "report-monthly", "run", "runs", "sap-items", "variances"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "company",
				"description": "company",
				"endpoints":   []string{"companies"},
			},
			{
				"name":        "construction-gatein",
				"description": "These five prefixes are the 'what came in the gate' flows, split by what kind of material arrived",
				"endpoints":   []string{"construction-categories", "construction-entry"},
				"syncable":    true,
			},
			{
				"name":        "daily-needs-gatein",
				"description": "These five prefixes are the 'what came in the gate' flows, split by what kind of material arrived",
				"endpoints":   []string{"daily-need-entry", "gate-entries-daily-need-categories"},
				"syncable":    true,
			},
			{
				"name":        "dashboards",
				"description": "This is the factory app's read-only reporting corner — the five 'management dashboard' screens the plant and purchase",
				"endpoints":   []string{"inventory-age-filter-options", "inventory-age-report", "sales-planning-requirement-analysis", "sales-planning-requirement-report", "sales-planning-requirement-status", "stock", "stock-as-of", "stock-benchmark-item-warehouses", "stock-export"},
				"searchable":  true,
			},
			{
				"name":        "dispatch",
				"description": "The dispatch domain follows a SAP sales invoice from the moment it becomes a 'dispatch bill' to the moment the truck",
				"endpoints":   []string{"bilty-grpo-history", "bilty-grpo-options", "bilty-grpo-pending", "open-bilties", "transporter-invoices-history"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "dispatch-plans",
				"description": "The dispatch domain follows a SAP sales invoice from the moment it becomes a 'dispatch bill' to the moment the truck",
				"endpoints":   []string{"bills", "dispatch-fulfilment-bills", "dispatch-fulfilment-summary", "dispatch-plans-bill-by-number", "pipeline"},
				"searchable":  true,
			},
			{
				"name":        "docking-admin",
				"description": "The dispatch domain follows a SAP sales invoice from the moment it becomes a 'dispatch bill' to the moment the truck",
				"endpoints":   []string{"partial-scan-requests", "scan-skip-requests"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "driver-management",
				"description": "This is the factory's transport master file plus the gate's vehicle-entry log.",
				"endpoints":   []string{"driver", "drivers", "drivers-names"},
				"syncable":    true,
			},
			{
				"name":        "fixed-asset-gatein",
				"description": "These five prefixes are the 'what came in the gate' flows, split by what kind of material arrived",
				"endpoints":   []string{"fixed-asset-categories"},
				"syncable":    true,
			},
			{
				"name":        "gate-core",
				"description": "gate-core is the shared gate engine underneath every category-specific gate app (raw-material, daily-needs, maintenance",
				"endpoints":   []string{"arrival-gatepass-readiness", "arrivals", "arrivals-expected", "bst-in", "bst-ins", "bst-ins-eligible-outs", "bst-out", "bst-outs", "bst-outs-sap-transfer", "bst-outs-sap-transfers", "bst-return", "bst-returns", "bst-returns-eligible-outs", "construction-gate-entry", "daily-need-gate-entry", "dispatch-tracking", "dispatch-tracking-summary", "dispatch-tracking-updates", "empty-vehicle-in", "empty-vehicle-ins", "empty-vehicle-ins-eligible", "empty-vehicle-ins-reasons", "empty-vehicle-out", "empty-vehicle-outs", "empty-vehicle-outs-eligible-entries", "gate-attachments", "inside-dispatch-vehicles", "job-work", "job-work-detail", "job-work-sap-grpo", "job-work-sap-grpos", "job-work-sap-production-order", "job-work-sap-production-orders", "maintenance-gate-entry", "raw-material-gate-entry", "rejected-qc-return", "rejected-qc-returns", "sales-dispatch", "sales-dispatch-attachments", "sales-dispatch-barcode-scans", "sales-dispatch-box-scans", "sales-dispatch-detail", "sales-dispatch-document", "sales-dispatch-documents", "sales-dispatch-gatepass-prints", "sales-dispatch-pending-bookings", "sales-dispatch-reports", "unit-choices"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "goods-return",
				"description": "Goods Return handles stock coming BACK from customers into the plant",
				"endpoints":   []string{"gate-expected", "list", "warehouses"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "grpo",
				"description": "GRPO = 'Goods Receipt PO' — the step where material that has physically arrived at a JIVO plant gets booked into SAP as",
				"endpoints":   []string{"all-entries", "attachments", "fg-all-entries", "fg-history", "fg-pending", "fg-summary", "history", "history-detail", "inspection-report", "pending", "preview", "service-history", "service-history-detail", "service-options", "service-pending", "summary"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "labour-count",
				"description": "This domain covers how JIVO's factory counts contract ('casual') labour on and off the site each day.",
				"endpoints":   []string{"gate-board", "sheet-history"},
				"searchable":  true,
			},
			{
				"name":        "labour-gate",
				"description": "This domain covers how JIVO's factory counts contract ('casual') labour on and off the site each day.",
				"endpoints":   []string{"gate-day", "gate-entry-audit"},
				"searchable":  true,
			},
			{
				"name":        "maintenance",
				"description": "The `/maintenance/` group is the factory's plant-engineering system — everything that keeps machines running and the",
				"endpoints":   []string{"alerts", "asset-categories", "asset-departments", "asset-documents", "asset-locations", "asset-photos", "assets", "daily-electricity-readings", "daily-wastage-logs", "dashboard", "electricity-meters", "maintenance-asset-category-get", "maintenance-asset-department-get", "maintenance-asset-document-get", "maintenance-asset-get", "maintenance-asset-location-get", "maintenance-asset-photo-get", "maintenance-asset-qr", "maintenance-fire-categories", "maintenance-fire-category-get", "maintenance-fire-issue-get", "maintenance-fire-issues", "maintenance-fire-item-get", "maintenance-fire-items", "maintenance-fire-low-stock", "maintenance-fire-movements", "maintenance-fire-report-attachments", "maintenance-fire-report-get", "maintenance-fire-report-item-get", "maintenance-fire-report-items", "maintenance-fire-report-photo-get", "maintenance-fire-report-photos", "maintenance-fire-reports", "maintenance-fire-request-get", "maintenance-fire-requests", "maintenance-material-indent-attachment-get", "maintenance-material-indent-attachments", "maintenance-material-indent-get", "maintenance-material-indent-quotations", "maintenance-material-indents", "maintenance-pm-execution-get", "maintenance-safety-fine-get", "maintenance-safety-fine-photo-get", "maintenance-safety-fine-photos", "maintenance-safety-fines", "maintenance-safety-violation-type-get", "maintenance-safety-violation-types", "maintenance-spare-get", "maintenance-spare-request-get", "maintenance-vendor-visit-get", "maintenance-work-order-get", "maintenance-work-order-photo-get", "maintenance-work-permit-attachments", "maintenance-work-permit-get", "maintenance-work-permit-worker-get", "maintenance-work-permit-workers", "maintenance-work-permits", "options", "pm-checklist-items", "pm-executions", "pm-plans", "reports", "spare-categories", "spare-movements", "spare-requests", "spares", "spares-low-stock", "vendor-visits", "work-order-photos", "work-orders"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "maintenance-gatein",
				"description": "These five prefixes are the 'what came in the gate' flows, split by what kind of material arrived",
				"endpoints":   []string{"maintenance-entry", "maintenance-types"},
				"syncable":    true,
			},
			{
				"name":        "marketplace",
				"description": "This is the catalogue and reconciliation half of JIVO's Marketplace module — the cell that fulfils Flipkart/Amazon",
				"endpoints":   []string{"batch", "batch-issuance-csv", "batch-stock-list", "batch-variants", "batches", "combos", "dispatch", "dispatch-board", "dispatch-orders-in-range", "dispatch-sheets", "dispatches-list", "dn-awaiting-approval", "dn-export-csv", "dn-posted", "dn-sheets", "dn-summary", "gate-queue", "gate-sheet", "issue-request", "issue-requests-list", "orders-list", "packing-queue", "packing-summary", "reconciliation", "reconciliation-export-csv", "report-export-csv", "return", "returns-list", "sap-items", "sku-mappings", "warehouse-insights", "warehouses"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "non-moving-rm",
				"description": "This is the factory app's read-only reporting corner — the five 'management dashboard' screens the plant and purchase",
				"endpoints":   []string{"item-groups", "report"},
			},
			{
				"name":        "notifications",
				"description": "The 'platform' group is the plumbing the rest of the factory app sits on: who you are, who else exists",
				"endpoints":   []string{"detail", "list", "preferences", "unread-count"},
				"syncable":    true,
			},
			{
				"name":        "oms",
				"description": "The 'platform' group is the plumbing the rest of the factory app sits on: who you are, who else exists",
				"endpoints":   []string{"invoice-audit", "invoice-history", "invoices", "pending-count"},
				"searchable":  true,
			},
			{
				"name":        "order-processing",
				"description": "Order Processing is the factory app's mirror of OMS sales orders and the planning engine sitting on top of it",
				"endpoints":   []string{"dashboard", "line-issues", "materials", "order", "order-timeline", "orders", "procurement", "production", "sync-status"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "person-gatein",
				"description": "This is the factory's people register at the gate — who walked into the plant, when, through which gate, why",
				"endpoints":   []string{"contractors", "entries", "gate-labour", "gate-person-dashboard", "gate-person-inside", "gate-person-search", "gates", "labours", "person-types", "visitors"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "po",
				"description": "This corner of the factory app answers one question: can we actually build what SAP says we are going to build",
				"endpoints":   []string{"open-po-items", "open-pos", "vendors", "warehouses"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "production-execution",
				"description": "This is the factory's shop-floor execution system (MES) for the Bhakharpur plant — it is where a production run is born",
				"endpoints":   []string{"breakdown-categories", "checklist-templates", "cost-rates", "costs-analytics", "line-clearance", "line-clearance-detail", "line-config-detail", "line-configs", "line-configs-auto-fill", "lines", "machine-checklists", "machines", "recon-material", "recon-production", "recon-wastage", "reports-analytics", "reports-analytics-cost-analysis", "reports-analytics-downtime", "reports-analytics-downtime-pareto", "reports-analytics-monthly-summary", "reports-analytics-oee", "reports-analytics-oee-trend", "reports-analytics-plan-vs-production", "reports-analytics-procurement-vs-planned", "reports-analytics-resource-consumption", "reports-analytics-waste", "reports-analytics-waste-trend", "reports-daily-production", "reports-line-clearance", "reports-production-movement", "reports-production-movement-filter-options", "run-breakdowns", "run-compressed-air", "run-detail", "run-electricity", "run-gas", "run-labour", "run-machine-costs", "run-machine-runtime", "run-manpower", "run-materials", "run-overhead", "run-qc-inprocess", "run-water", "runs", "sap-bom", "sap-items", "sap-order-detail", "sap-orders", "waste", "waste-detail", "yield-report"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "quality-control",
				"description": "Quality Control is the QA department's own workflow inside the factory app",
				"endpoints":   []string{"arrival-slips", "inspections", "inspections-actionable", "inspections-awaiting-chemist", "inspections-awaiting-qam", "inspections-completed", "inspections-counts", "inspections-draft", "inspections-pending", "inspections-rejected", "inspections-return-to-vendor", "material-types", "print-documents", "production-qc", "production-qc-counts", "production-qc-pending", "qc-arrival-slip-get", "qc-inspection-get", "qc-inspections-decision-changed", "qc-material-type-get", "qc-material-type-parameters", "qc-online-monitoring", "qc-online-monitoring-get", "qc-online-monitoring-lines", "qc-online-monitoring-runs", "qc-online-monitoring-specs", "qc-parameter-get", "qc-print-document-get", "qc-production-running-runs", "qc-production-session-get", "sap-items"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "returnable-items",
				"description": "This is JIVO's RGP/NRGP gate-pass book — the register of material that leaves the factory gate and is meant to come",
				"endpoints":   []string{"attachment", "attachments", "dashboard", "gatepass", "gatepass-item", "gatepass-items", "gatepasses", "options", "pending-approval", "pending-gate-in", "pending-gate-out", "report", "return-events", "sap-items", "timeline"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "sap",
				"description": "This corner of the factory app answers one question: can we actually build what SAP says we are going to build",
				"endpoints":   []string{"plan-dashboard-details", "plan-dashboard-procurement", "plan-dashboard-sku", "plan-dashboard-summary"},
				"searchable":  true,
			},
			{
				"name":        "supply-chain",
				"description": "\"Smart Supply Chain\" is the factory app's buy-and-build planner",
				"endpoints":   []string{"alarms-preview", "capacity", "dashboard", "floor-convention", "floors", "live-trail", "monitored-skus", "parameters", "policy", "procurement", "reference-imports", "reference-lead-times", "reference-machines", "reference-sku-machines", "run-latest", "runs", "weekly"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "vehicle-management",
				"description": "This is the factory's transport master file plus the gate's vehicle-entry log.",
				"endpoints":   []string{"transporter", "transporters", "transporters-names", "vehicle", "vehicle-entries", "vehicle-entries-count", "vehicle-entries-list-by-status", "vehicle-types", "vehicles", "vehicles-names"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "warehouse",
				"description": "The warehouse module is the factory floor's stock-handling desk — its own landing page calls it 'Material requests",
				"endpoints":   []string{"bom-request-get", "bom-requests", "bst-gate-inwards", "bst-gate-outwards", "bst-get", "bst-incoming", "bst-incoming-get", "bst-list", "bst-partial-transfers", "bst-sap-transfer-get", "bst-sap-transfers", "fg-receipt-get", "fg-receipts", "wms-item-groups", "wms-warehouses"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "wms",
				"description": "The warehouse module is the factory floor's stock-handling desk — its own landing page calls it 'Material requests",
				"endpoints":   []string{"wms-cell-purposes", "wms-get", "wms-inventory", "wms-locations", "wms-materials", "wms-movements", "wms-pallets", "wms-templates", "wms-warehouses", "wms-zones"},
				"syncable":    true,
				"searchable":  true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass page parameter for subsequent pages.",
			"Control page size with the page_size parameter (default 100).",
			"Use from_date for incremental fetches (filter by modification time).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
