#!/usr/bin/env python3
"""Create the deterministic detached attestation for a verified identity release.

This tool does not make a map trusted by itself. After independent review, the
printed attestation SHA-256 must be deliberately copied into every production
consumer's compiled trust-anchor constant.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import verify_map


def canonical_bytes(value) -> bytes:
    return (
        json.dumps(value, ensure_ascii=False, sort_keys=True, indent=2) + "\n"
    ).encode("utf-8")


def bundle_relative_uri(source: dict, map_path: Path) -> str:
    source_path = (verify_map.ROOT / source["uri"]).resolve()
    release_dir = map_path.parent.resolve()
    try:
        relative = source_path.relative_to(release_dir)
    except ValueError as exc:
        raise ValueError(
            f"source {source.get('source_id')!r} is outside the release bundle"
        ) from exc
    uri = relative.as_posix()
    if uri.startswith("../") or "/../" in uri or uri in {"", ".", ".."}:
        raise ValueError(f"source {source.get('source_id')!r} has unsafe URI")
    return uri


def build_attestation(map_path: Path):
    audit, artifact = verify_map.verify_semantics(map_path)
    if audit.errors:
        raise ValueError(
            "map failed independent semantic verification: "
            + "; ".join(audit.errors[:20])
        )
    contract = artifact["contract"]
    if contract.get("release_status") != "released":
        raise ValueError("only a released map can be attested")

    evidence_artifacts = []
    for source in sorted(artifact["sources"], key=lambda row: row["source_id"]):
        uri = bundle_relative_uri(source, map_path)
        evidence_path = map_path.parent.joinpath(*uri.split("/"))
        actual_sha256 = verify_map.sha256_bytes(evidence_path.read_bytes())
        if actual_sha256 != source.get("content_sha256"):
            raise ValueError(f"source hash drift: {source['source_id']}")
        evidence_artifacts.append(
            {
                "source_id": source["source_id"],
                "uri": uri,
                "sha256": actual_sha256,
            }
        )

    return {
        "format_version": verify_map.ATTESTATION_FORMAT_VERSION,
        "contract_name": verify_map.ATTESTATION_CONTRACT_NAME,
        "dataset_version": contract["dataset_version"],
        "schema_version": contract["schema_version"],
        "release_status": contract["release_status"],
        "map": {
            "uri": map_path.name,
            "sha256": verify_map.sha256_bytes(map_path.read_bytes()),
        },
        "evidence_artifacts": evidence_artifacts,
        "verification": {
            "verifier_version": verify_map.VERIFIER_VERSION,
            "check_count": audit.checks,
        },
    }


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--map", default=str(verify_map.DEFAULT_MAP))
    parser.add_argument("--output", default=None)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes with the existing output instead of writing",
    )
    args = parser.parse_args(argv)
    map_path = Path(args.map).resolve()
    output = Path(args.output).resolve() if args.output else map_path.parent / verify_map.ATTESTATION_PATH.name
    try:
        attestation = build_attestation(map_path)
        raw = canonical_bytes(attestation)
        if args.check:
            if output.read_bytes() != raw:
                raise ValueError(f"release attestation drift: {output}")
        else:
            output.write_bytes(raw)
    except (OSError, ValueError, KeyError, TypeError, json.JSONDecodeError) as exc:
        print(f"ATTESTATION FAILED: {exc}", file=sys.stderr)
        return 6
    print(
        json.dumps(
            {
                "attestation": str(output),
                "attestation_sha256": verify_map.sha256_bytes(raw),
                "dataset_version": attestation["dataset_version"],
                "map_sha256": attestation["map"]["sha256"],
                "check_count": attestation["verification"]["check_count"],
            },
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
