"use client";

import { useEffect, useState } from "react";
import type { DayProposal, MachineId, MachineNow, PlanRevision } from "../lib/planning-types";
import { useDashboard } from "../lib/use-dashboard";
import { BlockerGroups, clockLabel, dateLabel, Drawer, latestRevision, MACHINE_IDS, number, Objective, Runs, timeLabel, tonnes, WarehouseAction } from "./board-parts";
import PlanEditor from "./plan-editor";

type Tab = "today" | "tomorrow" | "activity";
type Context = { type: "machine"; machineId: MachineId } | { type: "sources" } | { type: "constraints"; proposal: DayProposal } | { type: "unlock" } | null;
const stateLabel: Record<MachineNow["status"], string> = { running: "Running", stopped: "Stopped", completed: "Completed", not_started: "Not started", unknown: "Unknown" };

export default function FactoryBoard() {
  const board = useDashboard();
  const { snapshot, plans, jobs, authenticated, busy } = board;
  const [tab, setTab] = useState<Tab>("today");
  const [context, setContext] = useState<Context>(null);
  const [passcode, setPasscode] = useState("");
  const [planView, setPlanView] = useState<"proposal" | "agreed">("proposal");
  const [reviewedId, setReviewedId] = useState<string | null>(null);
  const [reviewAcknowledged, setReviewAcknowledged] = useState(false);

  useEffect(() => {
    const initial = window.location.hash.slice(1);
    if (["today", "tomorrow", "activity"].includes(initial)) setTab(initial as Tab);
  }, []);
  function changeTab(value: Tab) { setTab(value); window.history.replaceState(null, "", `#${value}`); }

  const tomorrowPlans = snapshot ? plans[snapshot.tomorrow.date] : undefined;
  const todayPlans = snapshot ? plans[snapshot.today.date] : undefined;
  const latest = latestRevision(tomorrowPlans);
  const draft = latestRevision(tomorrowPlans, "draft");
  const approved = latestRevision(tomorrowPlans, "approved");
  const todayApproved = latestRevision(todayPlans, "approved");
  const todayDraft = latestRevision(todayPlans, "draft");
  const proposal = draft?.proposal ?? tomorrowPlans?.proposal ?? snapshot?.tomorrow;
  const todaySuggestion = todayDraft?.proposal ?? todayPlans?.proposal ?? snapshot?.today.proposal;
  const shownPlan = planView === "agreed" ? approved?.proposal : proposal;
  const activeJobs = jobs.filter(job => ["queued", "running"].includes(job.status));
  const pendingPlanJob = activeJobs.some(job => job.kind === "replan" || job.kind === "ai_review");
  const draftSourceChanged = !!draft && !!snapshot && draft.sourceRevision !== snapshot.sourceRevision;
  const draftCanApprove = !!draft && draft.revision === latest?.revision && draft.proposal.validation.valid && !draftSourceChanged;
  const draftIsReviewed = !!draft && reviewedId === draft.id && reviewAcknowledged && planView === "proposal";

  useEffect(() => { setReviewedId(draft?.id ?? null); setReviewAcknowledged(false); }, [draft?.id, planView]);

  function requestWrite(action: () => void) { if (authenticated) action(); else setContext({ type: "unlock" }); }

  return <div className="app-shell">
    <a className="skip-link" href="#main-content">Skip to factory board</a>
    <header className="site-header"><a className="brand" href="#today" onClick={event => { event.preventDefault(); changeTab("today"); }} aria-label="MARK V home"><span className="brand-mark" aria-hidden="true">J</span><span><strong>MARK V</strong><small>JIVO production</small></span></a><div className="header-right"><span className="header-caption">The factory. The next shift.</span>{authenticated ? <button className="text-button" disabled={busy} onClick={() => void board.lock()}>Editing unlocked <span aria-hidden="true">·</span> Lock</button> : <button className="button secondary small" onClick={() => setContext({ type: "unlock" })}>Unlock editing</button>}</div></header>
    <div className="workspace-bar"><nav className="tabs" aria-label="Factory views">{(["today", "tomorrow", "activity"] as Tab[]).map(value => <button key={value} className={tab === value ? "active" : ""} aria-current={tab === value ? "page" : undefined} onClick={() => changeTab(value)}>{value === "today" ? "Today" : value === "tomorrow" ? "Tomorrow" : "Activity"}{value === "activity" && activeJobs.length > 0 && <span className="count-badge">{activeJobs.length}</span>}</button>)}</nav><div className="toolbar"><button className="source-button" onClick={() => setContext({ type: "sources" })}><span className={`status-dot ${snapshot?.freshness.some(source => source.status !== "fresh") ? "dot-amber" : snapshot?.freshness.length ? "dot-green" : "dot-grey"}`} aria-hidden="true" />{snapshot ? `Source ${dateLabel(snapshot.sourceAsOf)} ${timeLabel(snapshot.sourceAsOf)} IST` : "Sources"}</button><button className="button secondary small" disabled={busy || activeJobs.some(job => job.kind === "refresh")} onClick={() => requestWrite(() => { void board.refresh(); })}>{activeJobs.some(job => job.kind === "refresh") ? "Refreshing…" : "Refresh"}</button></div></div>
    <main id="main-content">
      {board.error && <div className="message error-message" role="alert"><div><strong>Something needs attention</strong><p>{board.error}</p>{snapshot && <small>The last loaded board is retained below.</small>}</div><button className="button secondary small" onClick={() => void board.reload()}>Reload board</button></div>}
      {board.notice && <div className="message notice-message" role="status"><p>{board.notice}</p><button className="icon-button" aria-label="Dismiss update" onClick={board.dismissNotice}>×</button></div>}
      {activeJobs.length > 0 && tab !== "activity" && <button className="job-strip" onClick={() => changeTab("activity")}><span className="status-dot dot-amber" aria-hidden="true" /><span>{activeJobs[0].kind === "refresh" ? "Refreshing factory sources" : activeJobs[0].kind === "ai_review" ? "AI is reviewing the plan" : "Calculating your revision"}</span><span className="muted">{activeJobs[0].status === "queued" ? "Queued" : "In progress"} · View activity</span></button>}
      {!snapshot ? <section className="load-state" aria-live="polite"><div className="load-mark" aria-hidden="true">J</div><h1>{board.loading ? "Opening the factory board" : "Factory board unavailable"}</h1><p>{board.loading ? "Loading the latest saved production and plan." : "Reload to try the source service again."}</p>{!board.loading && <button className="button primary" onClick={() => void board.reload()}>Try again</button>}</section> : <>
        {tab === "today" && <>
          <div className="page-heading"><div><h1>On the floor today</h1><p>{dateLabel(snapshot.today.date, true)} <span className="separator">/</span> Recorded work beside the agreed plan.</p></div><button className="button primary" disabled={busy || pendingPlanJob} onClick={() => requestWrite(() => { void board.review(snapshot.today.date); })}>Ask AI to review today</button></div>
          <section className="today-summary" aria-label="Today's production"><div><span className="muted">Recorded today</span><strong>{tonnes(snapshot.today.recordedLitres)}</strong><small>{snapshot.today.recordedBasis}</small></div><div><span className="muted">Agreed plan</span><strong>{todayApproved ? tonnes(todayApproved.proposal.totalLitres) : "Not agreed"}</strong><small>{todayApproved ? `Revision ${todayApproved.revision} · ${clockLabel(todayApproved.createdAt)}` : "Approve a reviewed proposal to establish an agreement."}</small></div><div><span className="muted">Latest suggestion</span><strong>{todaySuggestion ? tonnes(todaySuggestion.totalLitres) : "Not available"}</strong><small>{todayDraft ? `Draft revision ${todayDraft.revision}` : "A proposal does not change the agreement."}</small></div></section>
          {todaySuggestion && <WarehouseAction proposal={todaySuggestion} onDetails={() => setContext({ type: "constraints", proposal: todaySuggestion })} />}
          <div className="table-intro"><h2>Machine by machine</h2><p>Open a machine for its rules and setup.</p></div>
          <div className="machine-table today-table"><div className="table-head"><span>Machine</span><span>Running now</span><span>Agreed plan{todayApproved ? ` · r${todayApproved.revision}` : ""}</span><span>Latest suggestion{todayDraft ? ` · r${todayDraft.revision}` : ""}</span></div>{MACHINE_IDS.map(machineId => {
            const actual = snapshot.today.machines.find(machine => machine.machineId === machineId);
            return <section className="machine-row" key={machineId} aria-label={machineId}><div className="machine-name"><button onClick={() => setContext({ type: "machine", machineId })}>{machineId}<span aria-hidden="true">↗</span></button><span className={`machine-state state-${actual?.status ?? "unknown"}`}><span className="status-dot" aria-hidden="true" />{stateLabel[actual?.status ?? "unknown"]}</span></div><div className="machine-cell now-cell" data-label="Running now"><strong>{actual?.product ?? "Product not reported"}</strong><div className="run-numbers"><span>{tonnes(actual?.recordedLitres)}</span><span>Recorded</span></div><small>{clockLabel(actual?.asOf)}</small>{actual?.note && <p className="actual-note">{actual.note}</p>}</div><div className="machine-cell" data-label="Agreed plan">{todayApproved ? <Runs runs={todayApproved.proposal.runs.filter(run => run.machineId === machineId)} compact /> : <span className="empty-cell">No agreed plan</span>}</div><div className="machine-cell suggestion-cell" data-label="Latest suggestion">{todaySuggestion ? <Runs runs={todaySuggestion.runs.filter(run => run.machineId === machineId)} compact /> : <span className="empty-cell">No current suggestion</span>}</div></section>;
          })}</div>
          {snapshot.today.aggregatePouchNote && <p className="context-note">{snapshot.today.aggregatePouchNote}</p>}
          {todaySuggestion && <div className="board-bottom"><p>{todaySuggestion.nightReason}</p><button className="text-button" onClick={() => setContext({ type: "constraints", proposal: todaySuggestion })}>View holds and assumptions</button></div>}
          {todayDraft && <TodayApproval revision={todayDraft} latestRevision={latestRevision(todayPlans)?.revision} sourceChanged={todayDraft.sourceRevision !== snapshot.sourceRevision} authenticated={authenticated} busy={busy || pendingPlanJob} onUnlock={() => setContext({ type: "unlock" })} onApprove={board.approve} />}
        </>}
        <section hidden={tab !== "tomorrow"} aria-label="Tomorrow planning workspace">
          <div className="page-heading"><div><h1>Agree tomorrow’s work</h1><p>{dateLabel(snapshot.tomorrow.date, true)} <span className="separator">/</span> Day and night, planned together.</p></div><button className="button secondary" disabled={busy || pendingPlanJob} onClick={() => requestWrite(() => { void board.review(snapshot.tomorrow.date); })}>Ask AI to review tomorrow</button></div>
          <div className="tomorrow-layout"><div className="plan-workspace"><div className="plan-switch"><div className="segmented" aria-label="Plan version"><button className={planView === "proposal" ? "selected" : ""} onClick={() => setPlanView("proposal")}>Latest proposal{draft ? ` · r${draft.revision}` : ""}</button><button className={planView === "agreed" ? "selected" : ""} onClick={() => setPlanView("agreed")}>Agreed{approved ? ` · r${approved.revision}` : ""}</button></div><span className={planView === "agreed" && approved ? "green-text" : "muted"}>{planView === "agreed" ? approved ? "Saved agreement" : "No agreement yet" : draft ? `${draft.createdBy === "ai" ? "AI" : draft.createdBy === "operator" ? "Operator" : "System"} draft` : "Source-based suggestion"}</span></div>
          {shownPlan ? <><Objective proposal={shownPlan} /><WarehouseAction proposal={shownPlan} onDetails={() => setContext({ type: "constraints", proposal: shownPlan })} /><div className="plan-machine-table"><div className="plan-table-head"><span>Machine</span><span>Day session</span><span>Night session</span></div>{MACHINE_IDS.map(machineId => <section className="plan-machine-row" key={machineId} aria-label={`${machineId} plan`}><div className="machine-name"><button onClick={() => setContext({ type: "machine", machineId })}>{machineId}<span aria-hidden="true">↗</span></button></div><div className="machine-cell" data-label="Day session"><Runs runs={shownPlan.runs.filter(run => run.machineId === machineId && run.shift === "day")} compact /></div><div className="machine-cell" data-label="Night session"><Runs runs={shownPlan.runs.filter(run => run.machineId === machineId && run.shift === "night")} compact /></div></section>)}</div>
          <div className="board-bottom"><p>{shownPlan.blockers.length ? `${new Set(shownPlan.blockers.map(blocker => blocker.kind)).size} types of constraint explain the unscheduled work.` : "No scheduling constraints reported for this proposal."}</p><button className="text-button" onClick={() => setContext({ type: "constraints", proposal: shownPlan })}>View constraints and assumptions</button></div>
          {!shownPlan.validation.valid && <div className="validation-error" role="alert"><strong>This proposal cannot be approved</strong><ul>{shownPlan.validation.errors.map((error, index) => <li key={index}>{error}</li>)}</ul></div>}
          {planView === "proposal" && draftSourceChanged && <div className="validation-error" role="status">Factory sources changed since this draft. Ask AI to review again or save a new revision before approval.</div>}
          {planView === "proposal" && <section className="approval-panel"><div><h2>Keep the agreement deliberate</h2><p>{draft ? `Review revision ${draft.revision} above. Approval saves this exact day and night plan.` : "Save a revision or request an AI review to create a draft for approval."}</p>{approved && <p className="agreement-note">Revision {approved.revision} remains agreed until another revision is approved.</p>}</div>{draft && <><label className="check-label"><input type="checkbox" checked={draftIsReviewed} onChange={event => { setReviewedId(draft.id); setReviewAcknowledged(event.target.checked); }} />I reviewed revision {draft.revision}, including setup and night work.</label><button className="button primary" disabled={!draftCanApprove || !draftIsReviewed || busy || pendingPlanJob} onClick={() => requestWrite(() => { void board.approve(draft); })}>Approve revision {draft.revision}</button></>}</section>}
          </> : <section className="empty-plan"><h2>No agreed plan for tomorrow yet</h2><p>Review the latest proposal, save any changes and approve the exact revision.</p><button className="button secondary" onClick={() => setPlanView("proposal")}>View latest proposal</button></section>}
          <RevisionHistory revisions={tomorrowPlans?.revisions ?? []} />
          </div><PlanEditor key={snapshot.tomorrow.date} date={snapshot.tomorrow.date} revision={latest?.revision ?? null} products={snapshot.products} authenticated={authenticated} busy={busy || pendingPlanJob} jobs={jobs} onSave={board.revise} onUnlock={() => setContext({ type: "unlock" })} /></div>
        </section>
        {tab === "activity" && <>
          <div className="page-heading"><div><h1>What changed, and why</h1><p>Source refreshes, AI reviews and saved decisions.</p></div><button className="button secondary" onClick={() => void board.reload()}>Reload activity</button></div>
          <div className="activity-layout"><section><h2>Recent activity</h2>{snapshot.activity.length ? <ol className="activity-list">{[...snapshot.activity].sort((a, b) => b.at.localeCompare(a.at)).map(event => <li key={event.id}><span className={`activity-dot activity-${event.status}`} aria-hidden="true" /><div><div className="activity-title"><h3>{event.title}</h3><time dateTime={event.at}>{clockLabel(event.at)}</time></div><p>{event.detail}</p><span className={`event-status event-${event.status}`}>{event.status}</span></div></li>)}</ol> : <div className="empty-plan"><p>No recorded activity is available yet. A refresh, saved revision or AI review will appear here when the service records it.</p></div>}</section><aside className="jobs-panel"><h2>Jobs</h2>{jobs.length ? jobs.map(job => <article className="job-item" key={job.id}><div><strong>{job.kind === "refresh" ? "Factory refresh" : job.kind === "ai_review" ? "AI plan review" : "Plan revision"}</strong><span className={`event-status event-${job.status}`}>{job.status}</span></div><p>{clockLabel(job.createdAt)}</p>{job.finishedAt && <small>Finished {clockLabel(job.finishedAt)}</small>}{job.error && <p className="inline-error">{job.error}</p>}</article>) : <p className="muted">No jobs recorded.</p>}</aside></div>
        </>}
        <footer className="board-footer"><span>Planning T = 1,000 L. Recorded output and planned output stay separate.</span><button className="text-button" onClick={() => setContext({ type: "sources" })}>Sources and freshness</button></footer>
      </>}
    </main>
    {context && <Drawer title={context.type === "machine" ? context.machineId : context.type === "sources" ? "Sources and freshness" : context.type === "unlock" ? "Unlock operator editing" : "Why this plan looks this way"} onClose={() => { setContext(null); setPasscode(""); }}>
      {context.type === "unlock" && <form onSubmit={async event => { event.preventDefault(); const unlocked = await board.unlock(passcode); setPasscode(""); if (unlocked) setContext(null); }}><p className="drawer-lead">The board is public. Enter the operator passcode to save revisions, approve plans and request a refresh.</p><label>Operator passcode<input autoFocus type="password" autoComplete="current-password" value={passcode} onChange={event => setPasscode(event.target.value)} required /></label><button className="button primary full-width" disabled={busy || !passcode.trim()} type="submit">{busy ? "Unlocking…" : "Unlock editing"}</button>{board.error && <p className="inline-error" role="alert">{board.error}</p>}</form>}
      {context.type === "sources" && <><p className="drawer-lead">These are the sources’ own timestamps. Reloading the page does not make old data fresh.</p>{snapshot ? <><p className="source-stamp">Source position: {clockLabel(snapshot.sourceAsOf)}</p><div className="source-list">{snapshot.freshness.map(source => <section key={source.id}><div><h3>{source.label}</h3><span className={`event-status event-${source.status}`}>{source.status}</span></div><p>{clockLabel(source.asOf)}</p><p>{source.note}</p></section>)}</div><details className="technical-details"><summary>Snapshot details</summary><p>Board generated: {clockLabel(snapshot.generatedAt)}</p><p>Rules: {snapshot.machineRulesVersion}</p><p>Source revision: {snapshot.sourceRevision}</p></details></> : <p>Source information is unavailable until the board loads.</p>}</>}
      {context.type === "machine" && snapshot && <>{(() => { const rule = snapshot.machineRules.find(rule => rule.machineId === context.machineId); const machine = snapshot.today.machines.find(machine => machine.machineId === context.machineId); return <><div className="machine-drawer-status"><span className={`machine-state state-${machine?.status ?? "unknown"}`}><span className="status-dot" />{stateLabel[machine?.status ?? "unknown"]}</span><span>{clockLabel(machine?.asOf)}</span></div>{rule ? <dl className="rule-details"><div><dt>Operating packs</dt><dd>{rule.packs}</dd></div><div><dt>Running speed</dt><dd>{rule.speed}</dd></div><div><dt>Changeover</dt><dd>{rule.changeover}</dd></div><div><dt>Operating note</dt><dd>{rule.note}</dd></div><div><dt>Approved source</dt><dd>{rule.sourcePages}</dd></div></dl> : <p>Machine rules have not loaded.</p>}{machine?.note && <p className="context-note">{machine.note}</p>}<h3>Tomorrow’s proposed work</h3><Runs runs={proposal?.runs.filter(run => run.machineId === context.machineId) ?? []} /><BlockerGroups blockers={proposal?.blockers.filter(blocker => blocker.machineId === context.machineId) ?? []} products={snapshot.products} /></>; })()}</>}
      {context.type === "constraints" && <><p className="drawer-lead">{context.proposal.nightReason}</p><h3>Constraints</h3><BlockerGroups blockers={context.proposal.blockers} products={snapshot?.products ?? []} /><h3>Planning assumptions</h3><dl className="rule-details">{context.proposal.assumptions.map(assumption => <div key={assumption.id}><dt>{assumption.label}</dt><dd>{assumption.detail}</dd></div>)}</dl>{context.proposal.validation.warnings.length > 0 && <><h3>Review notes</h3><ul>{context.proposal.validation.warnings.map((warning, index) => <li key={index}>{warning}</li>)}</ul></>}</>}
    </Drawer>}
  </div>;
}

function TodayApproval({ revision, latestRevision: latest, sourceChanged, authenticated, busy, onUnlock, onApprove }: { revision: PlanRevision; latestRevision: number | undefined; sourceChanged: boolean; authenticated: boolean; busy: boolean; onUnlock: () => void; onApprove: (revision: PlanRevision) => Promise<PlanRevision | null> }) {
  const [acknowledged, setAcknowledged] = useState(false);
  useEffect(() => setAcknowledged(false), [revision.id]);
  return <section className="approval-panel today-approval"><div><h2>Agree today’s revision {revision.revision}</h2><p>{sourceChanged ? "Sources changed since this draft. Request a new AI review before approval." : "The suggestion remains separate until you approve it."}</p></div><label className="check-label"><input type="checkbox" checked={acknowledged} onChange={event => setAcknowledged(event.target.checked)} />I reviewed the full suggested work, setup and constraints.</label><button className="button primary" disabled={!acknowledged || busy || sourceChanged || latest !== revision.revision || !revision.proposal.validation.valid} onClick={() => authenticated ? void onApprove(revision) : onUnlock()}>Approve revision {revision.revision}</button></section>;
}

function RevisionHistory({ revisions }: { revisions: PlanRevision[] }) {
  return <details className="revision-history"><summary>Saved revisions <span>{revisions.length}</span></summary>{revisions.length ? <ol>{[...revisions].sort((a, b) => b.revision - a.revision).map(revision => <li key={revision.id}><div><strong>Revision {revision.revision}</strong><span className={`event-status event-${revision.status}`}>{revision.status}</span></div><span>{tonnes(revision.proposal.totalLitres)} · {revision.createdBy} · {clockLabel(revision.createdAt)}</span></li>)}</ol> : <p>No revisions saved yet.</p>}</details>;
}
