// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"net/http"
	"testing"
	"time"

	"exim-pp-cli/internal/config"
)

// recordingRoundTripper counts how many times its RoundTrip method is
// invoked and returns an empty 200 response. The read-only guard tests use it
// to prove rejected requests never reach the transport.
type recordingRoundTripper struct {
	calls int
}

func (r *recordingRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	r.calls++
	return &http.Response{
		StatusCode: http.StatusOK,
		Body:       io.NopCloser(bytes.NewReader([]byte("{}"))),
		Header:     http.Header{},
	}, nil
}

// newClientWithRecorder builds a minimal *Client wired to a recording
// transport. The Client is constructed through New() so the unexported
// limiter and cacheDir fields are initialized, then HTTPClient is swapped out
// for one whose Transport records every call.
func newClientWithRecorder(t *testing.T) (*Client, *recordingRoundTripper) {
	t.Helper()
	rec := &recordingRoundTripper{}
	cfg := &config.Config{BaseURL: "http://example.test"}
	c := New(cfg, time.Second, 0)
	c.HTTPClient = &http.Client{Transport: rec}
	c.NoCache = true
	return c, rec
}

func assertReadOnlyRefusal(t *testing.T, verb, path string, body []byte, status int, err error, rec *recordingRoundTripper) {
	t.Helper()

	wantErr := fmt.Sprintf("read-only CLI: refusing %s %s (only GET is permitted against EXIM)", verb, path)
	if err == nil {
		t.Fatalf("request returned nil error; want %q", wantErr)
	}
	if err.Error() != wantErr {
		t.Fatalf("error = %q, want %q", err, wantErr)
	}
	if body != nil {
		t.Fatalf("body = %q, want nil", body)
	}
	if status != 0 {
		t.Fatalf("status = %d, want 0", status)
	}
	if rec.calls != 0 {
		t.Fatalf("request attempted %d HTTP calls; want 0", rec.calls)
	}
}

// TestClient_ReadOnlyGuard_DoRejectsNonGETRegardlessOfVerifyMode replaces the
// generated verify-short-circuit expectations for this read-only CLI. Its
// hand-patched transport guard is absolute: ordinary operation, verify mode,
// and verify mode with LIVE_HTTP explicitly enabled must all refuse every
// non-GET before a synthetic response or a real network dial can occur.
func TestClient_ReadOnlyGuard_DoRejectsNonGETRegardlessOfVerifyMode(t *testing.T) {
	envModes := []struct {
		name     string
		verify   string
		liveHTTP string
	}{
		{name: "no-env"},
		{name: "verify", verify: "1"},
		{name: "verify-live-http", verify: "1", liveHTTP: "1"},
	}

	for _, envMode := range envModes {
		envMode := envMode
		t.Run(envMode.name, func(t *testing.T) {
			t.Setenv("PRINTING_PRESS_VERIFY", envMode.verify)
			t.Setenv("PRINTING_PRESS_VERIFY_LIVE_HTTP", envMode.liveHTTP)

			for _, verb := range []string{http.MethodDelete, http.MethodPost, http.MethodPut, http.MethodPatch} {
				verb := verb
				t.Run(verb, func(t *testing.T) {
					c, rec := newClientWithRecorder(t)
					body, status, err := c.do(context.Background(), verb, "/test", nil, nil, nil)
					assertReadOnlyRefusal(t, verb, "/test", body, status, err, rec)
				})
			}
		})
	}
}

// TestClient_ReadOnlyGuard_DoReadCannotBypass pins the second entrance to
// doInternal. Although generated CLIs use doRead for POST-based query APIs,
// EXIM permits no such exception: readOnlyIntent must not bypass its absolute
// method check under any verify-mode configuration.
func TestClient_ReadOnlyGuard_DoReadCannotBypass(t *testing.T) {
	envModes := []struct {
		name     string
		verify   string
		liveHTTP string
	}{
		{name: "no-env"},
		{name: "verify", verify: "1"},
		{name: "verify-live-http", verify: "1", liveHTTP: "1"},
	}

	for _, envMode := range envModes {
		envMode := envMode
		t.Run(envMode.name, func(t *testing.T) {
			t.Setenv("PRINTING_PRESS_VERIFY", envMode.verify)
			t.Setenv("PRINTING_PRESS_VERIFY_LIVE_HTTP", envMode.liveHTTP)

			for _, verb := range []string{http.MethodDelete, http.MethodPost, http.MethodPut, http.MethodPatch} {
				verb := verb
				t.Run(verb, func(t *testing.T) {
					c, rec := newClientWithRecorder(t)
					body, status, err := c.doRead(context.Background(), verb, "/query", nil, nil, nil)
					assertReadOnlyRefusal(t, verb, "/query", body, status, err, rec)
				})
			}
		})
	}
}

// TestClient_ReadOnlyGuard_GETControl proves the absolute method guard stays
// narrowly scoped: GET reaches the transport in ordinary and verify modes.
func TestClient_ReadOnlyGuard_GETControl(t *testing.T) {
	envModes := []struct {
		name     string
		verify   string
		liveHTTP string
	}{
		{name: "no-env"},
		{name: "verify", verify: "1"},
		{name: "verify-live-http", verify: "1", liveHTTP: "1"},
	}

	for _, envMode := range envModes {
		envMode := envMode
		t.Run(envMode.name, func(t *testing.T) {
			t.Setenv("PRINTING_PRESS_VERIFY", envMode.verify)
			t.Setenv("PRINTING_PRESS_VERIFY_LIVE_HTTP", envMode.liveHTTP)
			c, rec := newClientWithRecorder(t)

			body, status, err := c.do(context.Background(), http.MethodGet, "/test", nil, nil, nil)
			if err != nil {
				t.Fatalf("GET returned error: %v", err)
			}
			if status != http.StatusOK {
				t.Fatalf("GET status = %d, want %d", status, http.StatusOK)
			}
			if string(body) != "{}" {
				t.Fatalf("GET body = %q, want %q", body, "{}")
			}
			if rec.calls != 1 {
				t.Fatalf("GET attempted %d HTTP calls; want 1", rec.calls)
			}
		})
	}
}
