package main

// Code generated by scripts/gen_commands.py — DO NOT EDIT.

import "github.com/spf13/cobra"

func init() {
	registerSection(func(app *App) *cobra.Command {
		return buildSection(app, "Accounts-Taxes", "accounts", "Wallet ledger, TDS, investment declarations and proofs (8 reads)")
	})
}
