package main

// Code generated by scripts/gen_commands.py — DO NOT EDIT.

import "github.com/spf13/cobra"

func init() {
	registerSection(func(app *App) *cobra.Command {
		return buildSection(app, "Broadcast-Visitor-Help", "broadcast", "Broadcasts, visitor management and help/support reads (13 reads)")
	})
}
