package main

// Code generated by scripts/gen_commands.py — DO NOT EDIT.

import "github.com/spf13/cobra"

func init() {
	registerSection(func(app *App) *cobra.Command {
		return buildSection(app, "Dashboard", "dashboard", "Dashboard \u2014 headline counts, alerts and wishes-data reads (7 reads)")
	})
}
