package main

// Code generated by scripts/gen_commands.py — DO NOT EDIT.

import "github.com/spf13/cobra"

func init() {
	registerSection(func(app *App) *cobra.Command {
		return buildSection(app, "Employee-Management", "employee", "Employee master \u2014 profiles, KYC, bank, family, documents (53 reads)")
	})
}
