package main

// Code generated by scripts/gen_commands.py — DO NOT EDIT.

import "github.com/spf13/cobra"

func init() {
	registerSection(func(app *App) *cobra.Command {
		return buildSection(app, "Leave-Management", "leave", "Leave balances, requests, policies and holidays (19 reads)")
	})
}
