import test from "node:test";
import assert from "node:assert/strict";
import { dispatchStatus, selectDispatch } from "../lib/dispatch-board.ts";
import { validateDispatchFeed, validateStorageEvidence } from "../lib/dispatch-validation.ts";
import type { DispatchFeed, GateEntry } from "../lib/dispatch-types.ts";
const instant = "2026-09-09T01:00:00+05:30";
function entry(id: string, company: GateEntry["company"], warehouse: string, litres: number, tripId = "shared-arrival") : GateEntry {
 const operationalCompany = company === "JIVO_BEVERAGES" ? "BEVERAGES" : ["GP-FG","GP-FGM"].includes(warehouse) ? "MART" : company === "JIVO_MART" && ["BH-BT","BH-PF"].includes(warehouse) ? "UNKNOWN" : company === "JIVO_OIL" ? "WELLNESS" : "MART";
 return { operationalWellnessLitres: operationalCompany === "WELLNESS" ? litres : 0, operationalMartLitres: operationalCompany === "MART" ? litres : 0, operationalUnclassifiedLitres: operationalCompany === "UNKNOWN" ? litres : 0, id, company, reference:`Gate-${id}`,tripId,identityBasis:"factory arrival identity",date:"2026-09-08",departedAt:"2026-09-08T17:00:00+05:30",litres,planningTonnes:litres/1000,documentCount:1,warehouseLitres:[{warehouse,litres}],wellnessStorageLitres:company === "JIVO_OIL" && ["BH-BT","BH-PF"].includes(warehouse) ? litres : 0,items:[{operationalCompany,code:"FG1",name:"Oil",warehouse,quantity:litres,uom:"L",litres}],detailComplete:true,issues:[] };
}
function fixture(): DispatchFeed {
 const entries = [entry("1","JIVO_OIL","BH-BT",54076),entry("2","JIVO_OIL","GP-FG",26373.6),entry("3","JIVO_MART","GP-FGM",45025),entry("4","JIVO_BEVERAGES","BEV",40783.2,"bev-arrival")];
 const totals={operationalWellnessLitres:54076,operationalMartLitres:71398.6,operationalUnclassifiedLitres:0,combinedLitres:125474.6,wellnessLitres:80449.6,martLitres:45025,beveragesLitres:40783.2,wellnessStorageLitres:54076};
 return {version:1,ok:true,complete:true,asOf:instant,attemptedAt:instant,expectedRefreshSeconds:60,sourceUrl:"https://ji.jivo.in/dispatch",coverage:{fromDate:"2026-09-08",toDate:"2026-09-08",dateBasis:"actual gate",allCompanies:true,listRows:4,pages:1,listComplete:true},unitNote:"Planning T",scopeNote:"Wellness + Mart",gateEntries:entries,days:[{date:"2026-09-08",...totals,gateEntryCount:3,tripCount:1,complete:true}],trips:[{id:"shared-arrival",date:"2026-09-08",departedAt:entries[0].departedAt,gateEntryIds:["1","2","3"],identityBasis:"factory arrival identity",...totals,beveragesLitres:0},{id:"bev-arrival",date:"2026-09-08",departedAt:entries[3].departedAt,gateEntryIds:["4"],identityBasis:"factory arrival identity",...totals,operationalWellnessLitres:0,operationalMartLitres:0,combinedLitres:0,wellnessLitres:0,martLitres:0,wellnessStorageLitres:0}],issues:[]};
}
test("overall counts shared company arrival once and excludes beverages",()=>{const data=validateDispatchFeed(fixture());const view=selectDispatch(data,"2026-09-08");assert.equal(view.trips.length,1);assert.equal(view.litres,125474.6);assert.equal(view.wellnessLitres,54076);assert.equal(view.martLitres,71398.6);assert.equal(view.storageLitres,54076);});
test("company views show their share of a shared truck",()=>{const data=fixture();assert.equal(selectDispatch(data,"2026-09-08","wellness").litres,54076);assert.equal(selectDispatch(data,"2026-09-08","mart").litres,71398.6);assert.equal(selectDispatch(data,"2026-09-08","beverages").litres,40783.2);assert.equal(data.gateEntries[1].company,"JIVO_OIL");});
test("missing date is unknown, not zero",()=>{assert.equal(selectDispatch(fixture(),"2026-09-09").litres,null);});
test("incomplete item evidence retains known header but does not invent business split",()=>{const data=fixture();data.gateEntries[0].detailComplete=false;data.gateEntries[0].items[0].litres=null;const view=selectDispatch(data,"2026-09-08");assert.equal(view.litres,125474.6);assert.equal(view.wellnessLitres,null);});
test("fresh, stale, failed and partial source states",()=>{const data=fixture();const now=Date.parse(instant);assert.equal(dispatchStatus(data,now),"fresh");assert.equal(dispatchStatus(data,now+301000),"stale");data.complete=false;assert.equal(dispatchStatus(data,now),"incomplete");data.ok=false;assert.equal(dispatchStatus(data,now),"stale");assert.equal(data.asOf,instant);});
test("duplicate trip membership and wrong totals fail validation",()=>{const data=fixture();data.trips[1].gateEntryIds.push("1");assert.throws(()=>validateDispatchFeed(data));const other=fixture();other.days[0].combinedLitres=1;assert.throws(()=>validateDispatchFeed(other));});
test("departure date is verified in IST",()=>{const data=fixture();data.gateEntries[0].departedAt="2026-09-08T20:00:00Z";assert.throws(()=>validateDispatchFeed(data));});
test("missing days in coverage fail instead of appearing as zero",()=>{const data=fixture();data.coverage.toDate="2026-09-09";assert.throws(()=>validateDispatchFeed(data));});
test("negative unknown quantities and companies fail validation",()=>{const data=fixture();data.gateEntries[0].litres=-1;assert.throws(()=>validateDispatchFeed(data));const other=fixture();(other.gateEntries[0] as unknown as {company:string}).company="UNKNOWN";assert.throws(()=>validateDispatchFeed(other));});
test("storage evidence requires BH2 and keeps closing variance unknown",()=>{assert.equal(validateStorageEvidence({version:1,scope:["GP-FG"]}),null);const data={version:1,asOf:instant,attemptedAt:instant,ok:true,expectedObservationSeconds:3600,scope:["BH-BT","BH-PF"],recordedFgLitres:591451,previousObservation:null,recordedChangeLitres:null,legacyWaitingEstimateLitres:183190,legacyPlanningPressureLitres:774641,physicalReconciliation:{complete:false,calculatedClosingLitres:null,physicalClosingLitres:null,varianceLitres:null,missing:["Stock deduction timing"]},note:"Recorded balance"};assert.equal(validateStorageEvidence(data)?.physicalReconciliation.varianceLitres,null);});
test("Mart record at Wellness godown stays explicitly UNKNOWN, contributes only to combined dispatch",()=>{
 const data=fixture(); const row=data.gateEntries[2]; row.items[0].warehouse="BH-BT"; row.items[0].operationalCompany="UNKNOWN";row.warehouseLitres=[{warehouse:"BH-BT",litres:45025}];row.operationalMartLitres=0;row.operationalUnclassifiedLitres=45025;
 data.days[0].operationalMartLitres=26373.6;data.days[0].operationalUnclassifiedLitres=45025;data.trips[0].operationalMartLitres=26373.6;data.trips[0].operationalUnclassifiedLitres=45025;
 const view=selectDispatch(validateDispatchFeed(data),"2026-09-08");assert.equal(view.litres,125474.6);assert.equal(view.martLitres,26373.6);assert.equal(view.unclassifiedLitres,45025);assert.equal(view.storageLitres,54076);assert.equal(selectDispatch(data,"2026-09-08","unknown").litres,45025);
});
test("operational entries, trips and day totals each reconcile or fail",()=>{
 for(const level of ["entry","trip","day"]){ const data=fixture(); if(level === "entry")data.gateEntries[0].operationalWellnessLitres=1;if(level === "trip")data.trips[0].operationalMartLitres=1;if(level === "day")data.days[0].operationalUnclassifiedLitres=1;assert.throws(()=>validateDispatchFeed(data),level); }
 const data=fixture();(data.gateEntries[0].items[0] as unknown as {operationalCompany:string}).operationalCompany="OTHER";assert.throws(()=>validateDispatchFeed(data));
});
