// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

func newAPICmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "api [interface]",
		Short:       "Browse all API endpoints by interface name",
		Annotations: map[string]string{"mcp:read-only": "true"},
		Long: `Browse and call any API endpoint using the raw interface names.

The friendly top-level commands cover the most common operations.
This command provides access to ALL endpoints for power users and
agents that need full API coverage.

Run 'api' with no arguments to list all interfaces.
Run 'api <interface>' to see that interface's methods.`,
		Example: `  # List all available interfaces
  jivo-ecom-pp-cli api

  # Show methods for a specific interface
  jivo-ecom-pp-cli api <interface-name>`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			interfaces := discoverAPIInterfaces(cmd.Root())

			if len(args) > 0 {
				target := strings.ToLower(args[0])
				for _, iface := range interfaces {
					if strings.ToLower(iface.Name) == target {
						methods := discoverAPIEndpointMethods(iface.command)
						// JSON envelope: {interface, short, methods: [{name, short,
						// endpoint, method, path}, ...]}.
						if flags.asJSON {
							return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
								"interface": iface.Name,
								"short":     iface.Short,
								"methods":   methods,
							}, flags)
						}
						fmt.Fprintf(cmd.OutOrStdout(), "%s — %s\n\nMethods:\n", iface.Name, iface.Short)
						for _, method := range methods {
							fmt.Fprintf(cmd.OutOrStdout(), "  %-50s %s\n", iface.Name+" "+method.Name, method.Short)
						}
						fmt.Fprintf(cmd.OutOrStdout(), "\nUse '%s-pp-cli %s <method> --help' for details.\n", "jivo-ecom", iface.Name)
						return nil
					}
				}
				return fmt.Errorf("interface %q not found. Run '%s-pp-cli api' to list all interfaces", args[0], "jivo-ecom")
			}

			// JSON envelope: {interfaces: [...], note?: "..."}.
			if flags.asJSON {
				out := map[string]any{"interfaces": interfaces}
				if len(interfaces) == 0 {
					out["interfaces"] = []apiInterfaceEntry{}
					out["note"] = "No API interfaces found."
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if len(interfaces) == 0 {
				fmt.Fprintln(cmd.OutOrStdout(), "No API interfaces found.")
				return nil
			}

			fmt.Fprintf(cmd.OutOrStdout(), "Available API interfaces (%d):\n\n", len(interfaces))
			for _, e := range interfaces {
				fmt.Fprintf(cmd.OutOrStdout(), "  %-45s %s\n", e.Name, e.Short)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "\nUse '%s-pp-cli api <interface>' to see methods.\n", "jivo-ecom")
			return nil
		},
	}

	return cmd
}

// apiInterfaceEntry is a top-level generated resource group. command stays
// private so JSON output remains the stable {name, short} shape.
type apiInterfaceEntry struct {
	Name    string `json:"name"`
	Short   string `json:"short"`
	command *cobra.Command
}

// apiEndpointMethod describes one generated endpoint below a resource group.
// Name is the complete command path relative to the interface, so discovery
// remains accurate if a future regeneration nests endpoint commands.
type apiEndpointMethod struct {
	Name     string `json:"name"`
	Short    string `json:"short"`
	Endpoint string `json:"endpoint,omitempty"`
	Method   string `json:"method,omitempty"`
	Path     string `json:"path,omitempty"`
}

// discoverAPIInterfaces selects generated resource groups by endpoint
// descendants, not Cobra visibility. Regenerated resource parents are visible,
// while unrelated utility commands may be hidden; Hidden therefore cannot be
// used as an API/interface marker.
func discoverAPIInterfaces(root *cobra.Command) []apiInterfaceEntry {
	interfaces := make([]apiInterfaceEntry, 0)
	for _, child := range root.Commands() {
		if !hasEndpointDescendant(child) {
			continue
		}
		interfaces = append(interfaces, apiInterfaceEntry{
			Name:    child.Name(),
			Short:   child.Short,
			command: child,
		})
	}
	sort.Slice(interfaces, func(i, j int) bool { return interfaces[i].Name < interfaces[j].Name })
	return interfaces
}

func hasEndpointDescendant(command *cobra.Command) bool {
	for _, child := range command.Commands() {
		if isGeneratedEndpoint(child) || hasEndpointDescendant(child) {
			return true
		}
	}
	return false
}

func isGeneratedEndpoint(command *cobra.Command) bool {
	return command.Annotations != nil && strings.TrimSpace(command.Annotations["pp:endpoint"]) != ""
}

func discoverAPIEndpointMethods(iface *cobra.Command) []apiEndpointMethod {
	methods := make([]apiEndpointMethod, 0)
	var walk func(*cobra.Command, []string)
	walk = func(parent *cobra.Command, parentPath []string) {
		for _, child := range parent.Commands() {
			commandPath := append(append([]string(nil), parentPath...), child.Name())
			if isGeneratedEndpoint(child) {
				methods = append(methods, apiEndpointMethod{
					Name:     strings.Join(commandPath, " "),
					Short:    child.Short,
					Endpoint: child.Annotations["pp:endpoint"],
					Method:   child.Annotations["pp:method"],
					Path:     child.Annotations["pp:path"],
				})
			}
			walk(child, commandPath)
		}
	}
	walk(iface, nil)
	sort.Slice(methods, func(i, j int) bool { return methods[i].Name < methods[j].Name })
	return methods
}
