// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDashboardStateSalesDetailCitiesCmd(flags *rootFlags) *cobra.Command {
	var flagState string
	var flagMetric string
	var flagDimension string
	var flagPlatform string
	var flagMonth int
	var flagYear int

	cmd := &cobra.Command{
		Use:         "state-sales-detail-cities",
		Short:       "State-sales detail drilled to cities",
		Example:     "  jivo-ecom-pp-cli dashboard state-sales-detail-cities --state example-value",
		Annotations: map[string]string{"pp:endpoint": "dashboard.state-sales-detail-cities", "pp:method": "GET", "pp:path": "/api/dashboard/state-sales/detail/cities", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("state") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "state")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/dashboard/state-sales/detail/cities"
			params := map[string]string{}
			if flagState != "" {
				params["state"] = formatCLIParamValue(flagState)
			}
			if flagMetric != "" {
				params["metric"] = formatCLIParamValue(flagMetric)
			}
			if flagDimension != "" {
				params["dimension"] = formatCLIParamValue(flagDimension)
			}
			if flagPlatform != "" {
				params["platform"] = formatCLIParamValue(flagPlatform)
			}
			if flagMonth != 0 {
				params["month"] = formatCLIParamValue(flagMonth)
			}
			if flagYear != 0 {
				params["year"] = formatCLIParamValue(flagYear)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "dashboard", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagState, "state", "", "State name")
	cmd.Flags().StringVar(&flagMetric, "metric", "", "Metric (units/value)")
	cmd.Flags().StringVar(&flagDimension, "dimension", "", "Dimension")
	cmd.Flags().StringVar(&flagPlatform, "platform", "", "Platform slug")
	cmd.Flags().IntVar(&flagMonth, "month", 0, "Month number 1-12")
	cmd.Flags().IntVar(&flagYear, "year", 0, "Four-digit year")

	return cmd
}
