// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDashboardPenetrationReportCmd(flags *rootFlags) *cobra.Command {
	var flagMonth int
	var flagYear int
	var flagPage string
	var flagPageSize int
	var flagPlatform string
	var flagItemHead string
	var flagCategory string
	var flagSubCategory string
	var flagStatus string
	var flagSearch string
	var flagGroupBy string
	var flagSort string
	var flagDir string
	var flagNocache string

	cmd := &cobra.Command{
		Use:         "penetration-report",
		Short:       "Penetration report (get)",
		Example:     "  jivo-ecom-pp-cli dashboard penetration-report",
		Annotations: map[string]string{"pp:endpoint": "dashboard.penetration-report", "pp:method": "GET", "pp:path": "/api/dashboard/penetration-report", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"live", "selling", "stocked", "inactive"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagStatus, "status", allowedStatus)
				}
			}
			if cmd.Flags().Changed("group-by") {
				allowedGroupBy := []string{"city", "sku"}
				validGroupBy := false
				for _, v := range allowedGroupBy {
					if flagGroupBy == v {
						validGroupBy = true
						break
					}
				}
				if !validGroupBy {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagGroupBy, "group-by", allowedGroupBy)
				}
			}
			if cmd.Flags().Changed("dir") {
				allowedDir := []string{"asc", "desc"}
				validDir := false
				for _, v := range allowedDir {
					if flagDir == v {
						validDir = true
						break
					}
				}
				if !validDir {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagDir, "dir", allowedDir)
				}
			}
			if cmd.Flags().Changed("nocache") {
				allowedNocache := []string{"1"}
				validNocache := false
				for _, v := range allowedNocache {
					if flagNocache == v {
						validNocache = true
						break
					}
				}
				if !validNocache {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagNocache, "nocache", allowedNocache)
				}
			}
			if cmd.Flags().Changed("nocache") {
				var parsedNocache any
				if err := json.Unmarshal([]byte(flagNocache), &parsedNocache); err != nil {
					return fmt.Errorf("--nocache must be valid JSON: %w", err)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/dashboard/penetration-report"
			params := map[string]string{}
			if flagMonth != 0 {
				params["month"] = formatCLIParamValue(flagMonth)
			}
			if flagYear != 0 {
				params["year"] = formatCLIParamValue(flagYear)
			}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageSize != 0 {
				params["page_size"] = formatCLIParamValue(flagPageSize)
			}
			if flagPlatform != "" {
				params["platform"] = formatCLIParamValue(flagPlatform)
			}
			if flagItemHead != "" {
				params["item_head"] = formatCLIParamValue(flagItemHead)
			}
			if flagCategory != "" {
				params["category"] = formatCLIParamValue(flagCategory)
			}
			if flagSubCategory != "" {
				params["sub_category"] = formatCLIParamValue(flagSubCategory)
			}
			if flagStatus != "" {
				params["status"] = formatCLIParamValue(flagStatus)
			}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagGroupBy != "" {
				params["group_by"] = formatCLIParamValue(flagGroupBy)
			}
			if flagSort != "" {
				params["sort"] = formatCLIParamValue(flagSort)
			}
			if flagDir != "" {
				params["dir"] = formatCLIParamValue(flagDir)
			}
			if flagNocache != "" {
				params["nocache"] = formatCLIParamValue(flagNocache)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "dashboard", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().IntVar(&flagMonth, "month", 0, "month number")
	cmd.Flags().IntVar(&flagYear, "year", 0, "4-digit year")
	cmd.Flags().StringVar(&flagPage, "page", "", "0-based integer")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "integer; 1e5 used for export")
	cmd.Flags().StringVar(&flagPlatform, "platform", "", "array of platform slugs")
	cmd.Flags().StringVar(&flagItemHead, "item-head", "", "array of item-head keys")
	cmd.Flags().StringVar(&flagCategory, "category", "", "array of category names")
	cmd.Flags().StringVar(&flagSubCategory, "sub-category", "", "array of sub-category names")
	cmd.Flags().StringVar(&flagStatus, "status", "", "keys read off the status-ranking map n={live:3,selling:2,stocked:1,inactive:0}; the filter chips use the same keys (one of: live, selling, stocked, inactive)")
	cmd.Flags().StringVar(&flagSearch, "search", "", "free text")
	cmd.Flags().StringVar(&flagGroupBy, "group-by", "", "A===`city`?...:A===`sku`?...; empty means no grouping (one of: city, sku)")
	cmd.Flags().StringVar(&flagSort, "sort", "", "column key from the table header")
	cmd.Flags().StringVar(&flagDir, "dir", "", "both literals present in the chunk; I did not isolate the toggle that writes them (one of: asc, desc)")
	cmd.Flags().StringVar(&flagNocache, "nocache", "", "{...F,nocache:1} on the force-refresh path (one of: 1)")

	return cmd
}
