// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDashboardExpiryAlertsPoItemsCmd(flags *rootFlags) *cobra.Command {
	var flagPlatform string
	var flagPo string
	var flagPoNumber string

	cmd := &cobra.Command{
		Use:         "expiry-alerts-po-items",
		Short:       "Line items for a PO behind an expiry alert",
		Example:     "  jivo-ecom-pp-cli dashboard expiry-alerts-po-items --platform amazon --po example-value --po-number example-value",
		Annotations: map[string]string{"pp:endpoint": "dashboard.expiry-alerts-po-items", "pp:method": "GET", "pp:path": "/api/dashboard/platform-expiry-alerts/{platform}/pos/{po}/items", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("platform") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "platform")
			}
			if !cmd.Flags().Changed("po") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "po")
			}
			if !cmd.Flags().Changed("po-number") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "po-number")
			}
			if cmd.Flags().Changed("platform") {
				allowedPlatform := []string{"amazon", "bigbasket", "blinkit", "citymall", "flipkart", "flipkart_grocery", "jiomart", "swiggy", "zepto", "zomato"}
				validPlatform := false
				for _, v := range allowedPlatform {
					if flagPlatform == v {
						validPlatform = true
						break
					}
				}
				if !validPlatform {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagPlatform, "platform", allowedPlatform)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/dashboard/platform-expiry-alerts/{platform}/pos/{po}/items"
			path = replacePathParam(path, "platform", formatCLIParamValue(flagPlatform))
			path = replacePathParam(path, "po", formatCLIParamValue(flagPo))
			params := map[string]string{}
			if flagPoNumber != "" {
				params["po_number"] = formatCLIParamValue(flagPoNumber)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "dashboard", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPlatform, "platform", "", "Platform slug (one of: amazon, bigbasket, blinkit, citymall, flipkart, flipkart_grocery, jiomart, swiggy, zepto, zomato)")
	cmd.Flags().StringVar(&flagPo, "po", "", "Purchase-order number")
	cmd.Flags().StringVar(&flagPoNumber, "po-number", "", "PO number, URL-encoded (encodeURIComponent in the template)")

	return cmd
}
