// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPlatformBlinkitCampaignsOptimizationCmd(flags *rootFlags) *cobra.Command {
	var flagPlatform string
	var flagFrom string
	var flagTo string

	cmd := &cobra.Command{
		Use:         "blinkit-campaigns-optimization",
		Short:       "Blinkit Campaigns Optimization workbook: SKU master, brand fund, produ",
		Example:     "  jivo-ecom-pp-cli platform blinkit-campaigns-optimization --platform <platform>",
		Annotations: map[string]string{"pp:endpoint": "platform.blinkit-campaigns-optimization", "pp:method": "GET", "pp:path": "/api/platform/{platform}/blinkit-campaigns-optimization", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("platform") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "platform")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/platform/{platform}/blinkit-campaigns-optimization"
			path = replacePathParam(path, "platform", formatCLIParamValue(flagPlatform))
			params := map[string]string{}
			if flagFrom != "" {
				params["from"] = formatCLIParamValue(flagFrom)
			}
			if flagTo != "" {
				params["to"] = formatCLIParamValue(flagTo)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "platform", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPlatform, "platform", "", "Platform slug. Syntactically required, semantically ignored - always pass blinkit.")
	cmd.Flags().StringVar(&flagFrom, "from", "", "Window start, YYYY-MM-DD. Narrows server-side. Default = 1st of the current month. `from` and `to` default INDEPENDENTLY - passing only one does not widen the other.")
	cmd.Flags().StringVar(&flagTo, "to", "", "Window end, YYYY-MM-DD. Narrows server-side. Default = last day of the current month.")

	return cmd
}
