// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newPlatformPendencyCmd(flags *rootFlags) *cobra.Command {
	var flagPlatform string
	var flagScope string
	var flagFromDate string
	var flagToDate string
	var flagStatus string

	cmd := &cobra.Command{
		Use:         "pendency",
		Short:       "Order pendency dashboard for a platform",
		Example:     "  jivo-ecom-pp-cli platform pendency --platform blinkit",
		Annotations: map[string]string{"pp:endpoint": "platform.pendency", "pp:method": "GET", "pp:path": "/api/platform/{platform}/pendency-dashboard", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("platform") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "platform")
			}
			if cmd.Flags().Changed("platform") {
				allowedPlatform := []string{"blinkit", "zepto", "swiggy", "bigbasket"}
				validPlatform := false
				for _, v := range allowedPlatform {
					if flagPlatform == v {
						validPlatform = true
						break
					}
				}
				if !validPlatform {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagPlatform, "platform", allowedPlatform)
				}
			}
			if cmd.Flags().Changed("scope") {
				allowedScope := []string{"all"}
				validScope := false
				for _, v := range allowedScope {
					if flagScope == v {
						validScope = true
						break
					}
				}
				if !validScope {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagScope, "scope", allowedScope)
				}
			}
			if cmd.Flags().Changed("status") {
				allowedStatus := []string{"expired"}
				validStatus := false
				for _, v := range allowedStatus {
					if flagStatus == v {
						validStatus = true
						break
					}
				}
				if !validStatus {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagStatus, "status", allowedStatus)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/platform/{platform}/pendency-dashboard"
			path = replacePathParam(path, "platform", formatCLIParamValue(flagPlatform))
			params := map[string]string{}
			if flagScope != "" {
				params["scope"] = formatCLIParamValue(flagScope)
			}
			if flagFromDate != "" {
				params["from_date"] = formatCLIParamValue(flagFromDate)
			}
			if flagToDate != "" {
				params["to_date"] = formatCLIParamValue(flagToDate)
			}
			if flagStatus != "" {
				params["status"] = formatCLIParamValue(flagStatus)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "platform", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPlatform, "platform", "", "Platform slug. This endpoint is served ONLY for: blinkit, zepto, swiggy, bigbasket (one of: blinkit, zepto, swiggy, bigbasket)")
	cmd.Flags().StringVar(&flagScope, "scope", "", "sent only when no explicit date range is chosen (one of: all)")
	cmd.Flags().StringVar(&flagFromDate, "from-date", "", "date string from the range picker; from_date and to_date are sent as a pair or not at all")
	cmd.Flags().StringVar(&flagToDate, "to-date", "", "date string from the range picker; from_date and to_date are sent as a pair or not at all")
	cmd.Flags().StringVar(&flagStatus, "status", "", "only literal ever sent on this endpoint (one of: expired)")

	return cmd
}
