// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newReportsLiveDataCmd(flags *rootFlags) *cobra.Command {
	var flagReport string
	var flagSheet string
	var flagFull string
	var flagPage string
	var flagPageSize int

	cmd := &cobra.Command{
		Use:         "live-data",
		Short:       "Live data (data) Requires additional permission; returns 403 otherwise.",
		Example:     "  jivo-ecom-pp-cli reports live-data --report example-value",
		Annotations: map[string]string{"pp:endpoint": "reports.live-data", "pp:method": "GET", "pp:path": "/api/reports/live/data", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("report") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "report")
			}
			if cmd.Flags().Changed("full") {
				allowedFull := []string{"1"}
				validFull := false
				for _, v := range allowedFull {
					if flagFull == v {
						validFull = true
						break
					}
				}
				if !validFull {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagFull, "full", allowedFull)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/reports/live/data"
			params := map[string]string{}
			if flagReport != "" {
				params["report"] = formatCLIParamValue(flagReport)
			}
			if flagSheet != "" {
				params["sheet"] = formatCLIParamValue(flagSheet)
			}
			if flagFull != "" {
				params["full"] = formatCLIParamValue(flagFull)
			}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageSize != 0 {
				params["page_size"] = formatCLIParamValue(flagPageSize)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "reports", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagReport, "report", "", "report id from GET /api/reports/live/reports; required - the effect returns early when it is empty")
	cmd.Flags().StringVar(&flagSheet, "sheet", "", "sheet name from the chosen report")
	cmd.Flags().StringVar(&flagFull, "full", "", "mutually exclusive with page/page_size (one of: 1)")
	cmd.Flags().StringVar(&flagPage, "page", "", "0-based integer")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "integer")

	return cmd
}
