// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newReportsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "reports",
		Short:       "Report views: Amazon PO, appointment, and raw report tables",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newReportsAmazonPoCmd(flags))
	cmd.AddCommand(newReportsAmazonPoBillingCmd(flags))
	cmd.AddCommand(newReportsAmazonPoFilterOptionsCmd(flags))
	cmd.AddCommand(newReportsAmazonPoMatrixCmd(flags))
	cmd.AddCommand(newReportsAmazonPoNewPoCmd(flags))
	cmd.AddCommand(newReportsAmazonPoSkuPendencyCmd(flags))
	cmd.AddCommand(newReportsAmazonPoSkuPendencyFilterOptionsCmd(flags))
	cmd.AddCommand(newReportsAmazonPoSummaryCmd(flags))
	cmd.AddCommand(newReportsAppointmentCmd(flags))
	cmd.AddCommand(newReportsAppointmentFilterOptionsCmd(flags))
	cmd.AddCommand(newReportsAppointmentSummaryCmd(flags))
	cmd.AddCommand(newReportsColumnsCmd(flags))
	cmd.AddCommand(newReportsLiveDataCmd(flags))
	cmd.AddCommand(newReportsLiveReportsCmd(flags))
	cmd.AddCommand(newReportsRawCmd(flags))
	return cmd
}
