// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newReportsAmazonPoSkuPendencyCmd(flags *rootFlags) *cobra.Command {
	var flagPage string
	var flagPageSize int
	var flagSearch string
	var flagCategory string
	var flagSubCategory string
	var flagChannel string
	var flagFulfillmentCenter string
	var flagHaveInvoice string
	var flagDispatched string
	var flagOnlyInvoiced string

	cmd := &cobra.Command{
		Use:         "amazon-po-sku-pendency",
		Short:       "Amazon po sku pendency (amazonSkuPendency)",
		Example:     "  jivo-ecom-pp-cli reports amazon-po-sku-pendency",
		Annotations: map[string]string{"pp:endpoint": "reports.amazon-po-sku-pendency", "pp:method": "GET", "pp:path": "/api/reports/amazon-po/sku-pendency", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("have-invoice") {
				allowedHaveInvoice := []string{"1"}
				validHaveInvoice := false
				for _, v := range allowedHaveInvoice {
					if flagHaveInvoice == v {
						validHaveInvoice = true
						break
					}
				}
				if !validHaveInvoice {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagHaveInvoice, "have-invoice", allowedHaveInvoice)
				}
			}
			if cmd.Flags().Changed("dispatched") {
				allowedDispatched := []string{"1"}
				validDispatched := false
				for _, v := range allowedDispatched {
					if flagDispatched == v {
						validDispatched = true
						break
					}
				}
				if !validDispatched {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagDispatched, "dispatched", allowedDispatched)
				}
			}
			if cmd.Flags().Changed("only-invoiced") {
				allowedOnlyInvoiced := []string{"1"}
				validOnlyInvoiced := false
				for _, v := range allowedOnlyInvoiced {
					if flagOnlyInvoiced == v {
						validOnlyInvoiced = true
						break
					}
				}
				if !validOnlyInvoiced {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagOnlyInvoiced, "only-invoiced", allowedOnlyInvoiced)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/reports/amazon-po/sku-pendency"
			params := map[string]string{}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageSize != 0 {
				params["page_size"] = formatCLIParamValue(flagPageSize)
			}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagCategory != "" {
				params["category"] = formatCLIParamValue(flagCategory)
			}
			if flagSubCategory != "" {
				params["sub_category"] = formatCLIParamValue(flagSubCategory)
			}
			if flagChannel != "" {
				params["channel"] = formatCLIParamValue(flagChannel)
			}
			if flagFulfillmentCenter != "" {
				params["fulfillment_center"] = formatCLIParamValue(flagFulfillmentCenter)
			}
			if flagHaveInvoice != "" {
				params["have_invoice"] = formatCLIParamValue(flagHaveInvoice)
			}
			if flagDispatched != "" {
				params["dispatched"] = formatCLIParamValue(flagDispatched)
			}
			if flagOnlyInvoiced != "" {
				params["only_invoiced"] = formatCLIParamValue(flagOnlyInvoiced)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "reports", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagPage, "page", "", "0-based integer")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "integer")
	cmd.Flags().StringVar(&flagSearch, "search", "", "free text")
	cmd.Flags().StringVar(&flagCategory, "category", "", "category name")
	cmd.Flags().StringVar(&flagSubCategory, "sub-category", "", "sub-category name")
	cmd.Flags().StringVar(&flagChannel, "channel", "", "channel from filter-options.channels")
	cmd.Flags().StringVar(&flagFulfillmentCenter, "fulfillment-center", "", "FC from filter-options.fulfillment_centers")
	cmd.Flags().StringVar(&flagHaveInvoice, "have-invoice", "", " (one of: 1)")
	cmd.Flags().StringVar(&flagDispatched, "dispatched", "", " (one of: 1)")
	cmd.Flags().StringVar(&flagOnlyInvoiced, "only-invoiced", "", " (one of: 1)")

	return cmd
}
