// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newReportsRawCmd(flags *rootFlags) *cobra.Command {
	var flagView string
	var flagPage string
	var flagPageSize int
	var flagDateFrom string
	var flagDateTo string
	var flagPlatform string

	cmd := &cobra.Command{
		Use:         "raw",
		Short:       "Raw rows for one report view. `view` is required - a bare call returns 400 'Unknown report view'.",
		Example:     "  jivo-ecom-pp-cli reports raw --view all_platform_inventory",
		Annotations: map[string]string{"pp:endpoint": "reports.raw", "pp:method": "GET", "pp:path": "/api/reports/raw", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("view") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "view")
			}
			if cmd.Flags().Changed("view") {
				allowedView := []string{"all_platform_inventory", "master_po", "total_po", "SecMaster", "amazon_sec_range_master_view", "amazon_sec_daily_master_view", "amazon_mp_master_view", "sap:jm_primary:oil", "sap:jm_primary:mart", "sap:jm_inventory:oil", "sap:jm_inventory:mart"}
				validView := false
				for _, v := range allowedView {
					if flagView == v {
						validView = true
						break
					}
				}
				if !validView {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagView, "view", allowedView)
				}
			}
			if cmd.Flags().Changed("platform") {
				allowedPlatform := []string{"AMAZON", "BLINKIT", "ZEPTO", "SWIGGY", "BIG BASKET", "FLIPKART", "FLIPKART GROCERY", "ZOMATO", "CITY MALL"}
				validPlatform := false
				for _, v := range allowedPlatform {
					if flagPlatform == v {
						validPlatform = true
						break
					}
				}
				if !validPlatform {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagPlatform, "platform", allowedPlatform)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/reports/raw"
			params := map[string]string{}
			if flagView != "" {
				params["view"] = formatCLIParamValue(flagView)
			}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageSize != 0 {
				params["page_size"] = formatCLIParamValue(flagPageSize)
			}
			if flagDateFrom != "" {
				params["date_from"] = formatCLIParamValue(flagDateFrom)
			}
			if flagDateTo != "" {
				params["date_to"] = formatCLIParamValue(flagDateTo)
			}
			if flagPlatform != "" {
				params["platform"] = formatCLIParamValue(flagPlatform)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "reports", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagView, "view", "", "view name (one of: all_platform_inventory, master_po, total_po, SecMaster, amazon_sec_range_master_view, amazon_sec_daily_master_view, amazon_mp_master_view, sap:jm_primary:oil, sap:jm_primary:mart, sap:jm_inventory:oil, sap:jm_inventory:mart)")
	cmd.Flags().StringVar(&flagPage, "page", "", "0-based integer")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "integer")
	cmd.Flags().StringVar(&flagDateFrom, "date-from", "", "date string derived from the period preset (this_week/this_month/this_year/custom)")
	cmd.Flags().StringVar(&flagDateTo, "date-to", "", "date string derived from the period preset (this_week/this_month/this_year/custom)")
	cmd.Flags().StringVar(&flagPlatform, "platform", "", "comma-joined UPPERCASE display names, NOT slugs; TRAP (one of: AMAZON, BLINKIT, ZEPTO, SWIGGY, BIG BASKET, FLIPKART, FLIPKART GROCERY, ZOMATO, CITY MALL)")

	return cmd
}
