// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newShipmentCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "shipment",
		Short:       "Amazon Shipment Planner (read-only). Requires the amazon.shipment_planning.view permission; returns 403 without it.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newShipmentAllAppointmentsCmd(flags))
	cmd.AddCommand(newShipmentAppointmentCommitsCmd(flags))
	cmd.AddCommand(newShipmentAppointmentDatesCmd(flags))
	cmd.AddCommand(newShipmentAppointmentExtraPosCmd(flags))
	cmd.AddCommand(newShipmentAppointmentFamiliesCmd(flags))
	cmd.AddCommand(newShipmentAppointmentItemsCmd(flags))
	cmd.AddCommand(newShipmentAppointmentsCmd(flags))
	cmd.AddCommand(newShipmentAsinCatalogCmd(flags))
	cmd.AddCommand(newShipmentFcSwitchGroupCmd(flags))
	cmd.AddCommand(newShipmentInventoryCmd(flags))
	cmd.AddCommand(newShipmentPoAppointmentsCmd(flags))
	cmd.AddCommand(newShipmentPoItemsCmd(flags))
	cmd.AddCommand(newShipmentPoShipmentLookupCmd(flags))
	cmd.AddCommand(newShipmentPoShortSupplyCmd(flags))
	cmd.AddCommand(newShipmentRecordCmd(flags))
	cmd.AddCommand(newShipmentShipmentCmd(flags))
	cmd.AddCommand(newShipmentShipmentInvoiceFileCmd(flags))
	cmd.AddCommand(newShipmentShipmentInvoicesCmd(flags))
	cmd.AddCommand(newShipmentShipmentPoDocumentCmd(flags))
	cmd.AddCommand(newShipmentShipmentPoDocumentsCmd(flags))
	cmd.AddCommand(newShipmentShipmentSwitchVerifyCmd(flags))
	cmd.AddCommand(newShipmentShipmentsCmd(flags))
	cmd.AddCommand(newShipmentShipmentsDeletionLogCmd(flags))
	cmd.AddCommand(newShipmentShipmentsDohAutoFillCmd(flags))
	cmd.AddCommand(newShipmentShipmentsPendingApprovalsCmd(flags))
	cmd.AddCommand(newShipmentShipmentsStatsCmd(flags))
	cmd.AddCommand(newShipmentSwitchingCmd(flags))
	cmd.AddCommand(newShipmentV2AppointmentLinesCmd(flags))
	cmd.AddCommand(newShipmentV2AppointmentsCmd(flags))
	cmd.AddCommand(newShipmentV2ChannelsCmd(flags))
	cmd.AddCommand(newShipmentV2FillOptionsCmd(flags))
	cmd.AddCommand(newShipmentV2PosCmd(flags))
	return cmd
}
