// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newShipmentAppointmentItemsCmd(flags *rootFlags) *cobra.Command {
	var flagId string
	var flagAppointmentId string
	var flagTruckSize string
	var flagTruckCapacityLiters string
	var flagPriorityPremiumPct string
	var flagPriorityCommodityPct string
	var flagPriorityOtherPct string
	var flagPriorityStrict string
	var flagMaximizeFill string
	var flagRespectStock bool
	var flagAppointmentIds string
	var flagSelectedPos string
	var flagProductFamily string
	var flagFamilyAsins string
	var flagCommitCapsJson string

	cmd := &cobra.Command{
		Use:         "appointment-items",
		Short:       "Items for an appointment",
		Example:     "  jivo-ecom-pp-cli shipment appointment-items --id 550e8400-e29b-41d4-a716-446655440000 --appointment-id 550e8400-e29b-41d4-a716-446655440000 --truck-size 10_ton",
		Annotations: map[string]string{"pp:endpoint": "shipment.appointment-items", "pp:method": "GET", "pp:path": "/api/shipment/appointments/{id}/items/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "id")
			}
			if !cmd.Flags().Changed("appointment-id") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "appointment-id")
			}
			if !cmd.Flags().Changed("truck-size") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "truck-size")
			}
			if cmd.Flags().Changed("truck-size") {
				allowedTruckSize := []string{"10_ton", "15_ton", "custom"}
				validTruckSize := false
				for _, v := range allowedTruckSize {
					if flagTruckSize == v {
						validTruckSize = true
						break
					}
				}
				if !validTruckSize {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagTruckSize, "truck-size", allowedTruckSize)
				}
			}
			if cmd.Flags().Changed("priority-strict") {
				allowedPriorityStrict := []string{"1"}
				validPriorityStrict := false
				for _, v := range allowedPriorityStrict {
					if flagPriorityStrict == v {
						validPriorityStrict = true
						break
					}
				}
				if !validPriorityStrict {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagPriorityStrict, "priority-strict", allowedPriorityStrict)
				}
			}
			if cmd.Flags().Changed("maximize-fill") {
				allowedMaximizeFill := []string{"0", "1"}
				validMaximizeFill := false
				for _, v := range allowedMaximizeFill {
					if flagMaximizeFill == v {
						validMaximizeFill = true
						break
					}
				}
				if !validMaximizeFill {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagMaximizeFill, "maximize-fill", allowedMaximizeFill)
				}
			}
			if cmd.Flags().Changed("commit-caps-json") {
				var parsedCommitCapsJson any
				if err := json.Unmarshal([]byte(flagCommitCapsJson), &parsedCommitCapsJson); err != nil {
					return fmt.Errorf("--commit-caps-json must be valid JSON: %w", err)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/shipment/appointments/{id}/items/"
			path = replacePathParam(path, "id", formatCLIParamValue(flagId))
			params := map[string]string{}
			if flagAppointmentId != "" {
				params["appointment_id"] = formatCLIParamValue(flagAppointmentId)
			}
			if flagTruckSize != "" {
				params["truck_size"] = formatCLIParamValue(flagTruckSize)
			}
			if flagTruckCapacityLiters != "" {
				params["truck_capacity_liters"] = formatCLIParamValue(flagTruckCapacityLiters)
			}
			if flagPriorityPremiumPct != "" {
				params["priority_premium_pct"] = formatCLIParamValue(flagPriorityPremiumPct)
			}
			if flagPriorityCommodityPct != "" {
				params["priority_commodity_pct"] = formatCLIParamValue(flagPriorityCommodityPct)
			}
			if flagPriorityOtherPct != "" {
				params["priority_other_pct"] = formatCLIParamValue(flagPriorityOtherPct)
			}
			if flagPriorityStrict != "" {
				params["priority_strict"] = formatCLIParamValue(flagPriorityStrict)
			}
			if flagMaximizeFill != "" {
				params["maximize_fill"] = formatCLIParamValue(flagMaximizeFill)
			}
			if flagRespectStock != false {
				params["respect_stock"] = formatCLIParamValue(flagRespectStock)
			}
			if flagAppointmentIds != "" {
				params["appointment_ids"] = formatCLIParamValue(flagAppointmentIds)
			}
			if flagSelectedPos != "" {
				params["selected_pos"] = formatCLIParamValue(flagSelectedPos)
			}
			if flagProductFamily != "" {
				params["product_family"] = formatCLIParamValue(flagProductFamily)
			}
			if flagFamilyAsins != "" {
				params["family_asins"] = formatCLIParamValue(flagFamilyAsins)
			}
			if flagCommitCapsJson != "" {
				params["commit_caps_json"] = formatCLIParamValue(flagCommitCapsJson)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "shipment", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagId, "id", "", "Appointment id")
	cmd.Flags().StringVar(&flagAppointmentId, "appointment-id", "", "numeric/string appointment id from the appointments list")
	cmd.Flags().StringVar(&flagTruckSize, "truck-size", "", "always set - it is the only unconditional key in the URLSearchParams. UI default is 15_ton (one of: 10_ton, 15_ton, custom)")
	cmd.Flags().StringVar(&flagTruckCapacityLiters, "truck-capacity-liters", "", "integer litres; 10000 for 10_ton, 15000 for 15_ton, 12000 default for custom")
	cmd.Flags().StringVar(&flagPriorityPremiumPct, "priority-premium-pct", "", "number as string (percentage); sent as a group of three or not at all")
	cmd.Flags().StringVar(&flagPriorityCommodityPct, "priority-commodity-pct", "", "number as string (percentage); sent as a group of three or not at all")
	cmd.Flags().StringVar(&flagPriorityOtherPct, "priority-other-pct", "", "number as string (percentage); sent as a group of three or not at all")
	cmd.Flags().StringVar(&flagPriorityStrict, "priority-strict", "", "flag; only ever the string 1 (one of: 1)")
	cmd.Flags().StringVar(&flagMaximizeFill, "maximize-fill", "", "always sent; defaults to 1 (one of: 0, 1)")
	cmd.Flags().BoolVar(&flagRespectStock, "respect-stock", false, "only ever set to 0 (to switch stock respect OFF); omitted means on (one of: 0)")
	cmd.Flags().StringVar(&flagAppointmentIds, "appointment-ids", "", "comma-joined appointment ids")
	cmd.Flags().StringVar(&flagSelectedPos, "selected-pos", "", "comma-joined PO numbers")
	cmd.Flags().StringVar(&flagProductFamily, "product-family", "", "family key from GET /api/shipment/appointments/{id}/families/; not a fixed set - fetch families first")
	cmd.Flags().StringVar(&flagFamilyAsins, "family-asins", "", "comma-joined ASINs")
	cmd.Flags().StringVar(&flagCommitCapsJson, "commit-caps-json", "", "JSON object {'<asin>':{'units':N,'cartons':N}}")

	return cmd
}
