// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newTablesDataCmd(flags *rootFlags) *cobra.Command {
	var flagTable string
	var flagPage string
	var flagPageSize string
	var flagSearch string
	var flagSearchColumns string
	var flagDateColumn string
	var flagSortBy string
	var flagSortDir string
	var flagMaxDate string
	var flagYear int
	var flagMonth int
	var flagDate string
	var flagColumnFilters string

	cmd := &cobra.Command{
		Use:         "data",
		Short:       "Paginated rows for a table (server-shaped payload)",
		Example:     "  jivo-ecom-pp-cli tables data --table all_platform_inventory",
		Annotations: map[string]string{"pp:endpoint": "tables.data", "pp:method": "GET", "pp:path": "/api/dashboard/table-data/{table}", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("table") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "table")
			}
			if cmd.Flags().Changed("table") {
				allowedTable := []string{"all_platform_inventory", "amazon_ads", "amazon_coupon", "amazon_inventory", "amazon_mp", "amazon_price_data", "amazon_sec_city", "amazon_sec_daily", "amazon_sec_daily_master_view", "amazon_sec_range", "amazon_sec_range_margins", "amazon_sec_range_master_view", "bigbasketSec", "bigbasket_ads", "bigbasket_inventory", "bigbasket_sec_range", "blinkitSec", "blinkit_ads", "blinkit_brandfund", "blinkit_inventory", "citymallSec", "citymall_inventory", "fk_grocery", "flipkartSec", "flipkart_ads", "flipkart_grocery_master", "flipkart_secondary_all", "jiomartSec", "jiomart_inventory", "master_po", "prim_master_po", "swiggySec", "swiggy_ads", "swiggy_brandfund", "swiggy_inventory", "test_master_po", "total_po", "total_po_zbs", "zeptoSec", "zepto_ads", "zepto_brandfund", "zepto_inventory", "zomatoSec", "zomato_inventory"}
				validTable := false
				for _, v := range allowedTable {
					if flagTable == v {
						validTable = true
						break
					}
				}
				if !validTable {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagTable, "table", allowedTable)
				}
			}
			if cmd.Flags().Changed("sort-dir") {
				allowedSortDir := []string{"desc"}
				validSortDir := false
				for _, v := range allowedSortDir {
					if flagSortDir == v {
						validSortDir = true
						break
					}
				}
				if !validSortDir {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagSortDir, "sort-dir", allowedSortDir)
				}
			}
			if cmd.Flags().Changed("max-date") {
				allowedMaxDate := []string{"1"}
				validMaxDate := false
				for _, v := range allowedMaxDate {
					if flagMaxDate == v {
						validMaxDate = true
						break
					}
				}
				if !validMaxDate {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagMaxDate, "max-date", allowedMaxDate)
				}
			}
			if cmd.Flags().Changed("column-filters") {
				var parsedColumnFilters any
				if err := json.Unmarshal([]byte(flagColumnFilters), &parsedColumnFilters); err != nil {
					return fmt.Errorf("--column-filters must be valid JSON: %w", err)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/dashboard/table-data/{table}"
			path = replacePathParam(path, "table", formatCLIParamValue(flagTable))
			params := map[string]string{}
			if flagPage != "" {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageSize != "" {
				params["page_size"] = formatCLIParamValue(flagPageSize)
			}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagSearchColumns != "" {
				params["search_columns"] = formatCLIParamValue(flagSearchColumns)
			}
			if flagDateColumn != "" {
				params["date_column"] = formatCLIParamValue(flagDateColumn)
			}
			if flagSortBy != "" {
				params["sort_by"] = formatCLIParamValue(flagSortBy)
			}
			if flagSortDir != "" {
				params["sort_dir"] = formatCLIParamValue(flagSortDir)
			}
			if flagMaxDate != "" {
				params["max_date"] = formatCLIParamValue(flagMaxDate)
			}
			if flagYear != 0 {
				params["year"] = formatCLIParamValue(flagYear)
			}
			if flagMonth != 0 {
				params["month"] = formatCLIParamValue(flagMonth)
			}
			if flagDate != "" {
				params["date"] = formatCLIParamValue(flagDate)
			}
			if flagColumnFilters != "" {
				params["column_filters"] = formatCLIParamValue(flagColumnFilters)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "tables", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagTable, "table", "", "Reporting-schema table name, case-sensitive. (one of: all_platform_inventory, amazon_ads, amazon_coupon, amazon_inventory, amazon_mp, amazon_price_data, amazon_sec_city, amazon_sec_daily, amazon_sec_daily_master_view, amazon_sec_range, amazon_sec_range_margins, amazon_sec_range_master_view, bigbasketSec, bigbasket_ads, bigbasket_inventory, bigbasket_sec_range, blinkitSec, blinkit_ads, blinkit_brandfund, blinkit_inventory, citymallSec, citymall_inventory, fk_grocery, flipkartSec, flipkart_ads, flipkart_grocery_master, flipkart_secondary_all, jiomartSec, jiomart_inventory, master_po, prim_master_po, swiggySec, swiggy_ads, swiggy_brandfund, swiggy_inventory, test_master_po, total_po, total_po_zbs, zeptoSec, zepto_ads, zepto_brandfund, zepto_inventory, zomatoSec, zomato_inventory)")
	cmd.Flags().StringVar(&flagPage, "page", "", "Page number")
	cmd.Flags().StringVar(&flagPageSize, "page-size", "", "Rows per page")
	cmd.Flags().StringVar(&flagSearch, "search", "", "free text")
	cmd.Flags().StringVar(&flagSearchColumns, "search-columns", "", "comma-joined column names")
	cmd.Flags().StringVar(&flagDateColumn, "date-column", "", "column name")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "column name")
	cmd.Flags().StringVar(&flagSortDir, "sort-dir", "", " (one of: desc)")
	cmd.Flags().StringVar(&flagMaxDate, "max-date", "", " (one of: 1)")
	cmd.Flags().IntVar(&flagYear, "year", 0, "4-digit year")
	cmd.Flags().IntVar(&flagMonth, "month", 0, "month number")
	cmd.Flags().StringVar(&flagDate, "date", "", "date string from the picker")
	cmd.Flags().StringVar(&flagColumnFilters, "column-filters", "", "JSON array string [{'column':'<col>','values':[...]}]")

	return cmd
}
