#!/usr/bin/env python3
"""
build_cli.py — generates the read-only CLI's allowlist and per-section command
files from captures/endpoints-raw.tsv.

Generating rather than hand-writing is the point: the CLI's reachable surface is
*derived* from the classification the study proved, so a command can never exist
for an endpoint the study did not classify READ with a proven method. Re-run this
after any change to the endpoint inventory.

Emits into cli/:
  allowlist.go      the (host, path) READ allowlist + template matcher
  cmd_<section>.go  one cobra command group per section
"""
import csv
import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from sections import assign          # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CLI = os.path.join(ROOT, "cli")

HOSTCONST = {
    "brand-portal-service-http.swiggy.com": "hostBrandPortal",
    "partner-api.swiggy.com": "hostPartnerAPI",
    "picker.swiggy.com": "hostPicker",
}

# section note name -> cobra command group name
GROUP = {
    "Purchase-Orders": "po", "PO-Booking-Appointments": "po-booking",
    "Goods-Received-GRN": "grn", "Returns-RTV-and-Purchase-Returns": "returns",
    "Stock-On-Hand-and-Low-Stock": "stock", "Availability-and-Fill-Rate": "availability",
    "Vendor-Performance-Scores": "vendor-perf", "Vendor-Downloads": "vendor-downloads",
    "Local-Buying": "local-buying", "Vendor-FAQ-Help": "vendor-help",
    "Sales-Reports": "sales-reports", "Sales-Insights": "sales-insights",
    "Ad-Campaigns": "campaigns", "Brand-Insights-Metrics": "brand-insights",
    "Keyword-And-Bid-Suggestions": "keywords", "Creatives": "creatives",
    "Requisition-Orders": "release-orders", "Products-And-SPINs": "products",
    "Ads-AI-Chat": "ads-chat", "NPI-New-Product-Introduction": "npi",
    "Discounts-BDPO": "discounts", "Sampling-Campaigns": "sampling",
    "Brandverse": "brandverse", "Catalog-SPIN-Management": "catalog",
    "Accounts-And-Entities": "accounts", "Config-And-Feature-Flags": "config",
    "Auth-Sessions-And-Login": "clock",
    "Telemetry-And-Third-Party": "telemetry",
    "Unclassified-Endpoints": "unclassified",
}


def leaf_name(path):
    """A short, stable command name for one endpoint."""
    p = re.sub(r"\{[^}]*\}|\$\{[^}]*\}", "", path)
    segs = [s for s in p.split("/") if s and not re.fullmatch(r"v\d|api|instamart|im-discounts", s)]
    name = "-".join(segs[-2:]) if len(segs) >= 2 else (segs[-1] if segs else "get")
    name = re.sub(r"[^A-Za-z0-9]+", "-", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", name).lower().strip("-")
    return name or "get"


def go_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    rows = list(csv.DictReader(open(os.path.join(HERE, "endpoints-raw.tsv")), delimiter="\t"))
    reads = [r for r in rows if r["wired"] == "yes"]

    # ---------------- allowlist.go ----------------
    a = ['package main', '',
         '// Code generated by captures/build_cli.py from captures/endpoints-raw.tsv.',
         '// DO NOT EDIT BY HAND — regenerate instead, so the CLI\'s reachable surface',
         '// always equals what the study classified READ with a PROVEN method.',
         '//',
         '// LAYER 2 of the read-only guardrail. Every entry here is a row whose class is',
         f'// READ or READ_FILE in vault/Swiggy-Instamart-Endpoints.md ({len(reads)} of {len(rows)}',
         '// catalogued endpoints). WRITE, EXPORT and UNKNOWN rows are absent by',
         '// construction, so they are unreachable even by GET.', '',
         'import "strings"', '',
         '// allowedReads maps host -> the set of readable paths on it.',
         'var allowedReads = map[string]map[string]bool{']
    byhost = defaultdict(list)
    for r in reads:
        byhost[r["host"]].append(r["path"])
    for h in sorted(byhost):
        a.append(f'\t{go_str(h)}: {{')
        for p in sorted(set(byhost[h])):
            a.append(f'\t\t{go_str(p)}: true,')
        a.append('\t},')
    # explicit exclusions: every row NOT wired. A template placeholder must never
    # admit one of these — see the campaign/{0} vs campaign/batch case below.
    a += ['}', '']
    a += ['// deniedPaths lists every catalogued endpoint that is NOT a wired read',
          '// (WRITE, EXPORT, or UNKNOWN). It is consulted BEFORE template matching.',
          '//',
          '// WHY: the read template "/api/v1/campaign/{0}" (a sampling campaign detail',
          '// lookup) has a placeholder that happily matches the literal segment "batch",',
          '// so "/api/v1/campaign/batch" — a bulk BID AND BUDGET UPDATE — was being',
          '// admitted by the matcher. This was caught by guardrail_test.go, not in review.',
          '// An explicit exclusion always beats a template match.',
          'var deniedPaths = map[string]map[string]bool{']
    denied = defaultdict(list)
    for r in rows:
        if r["wired"] != "yes":
            denied[r["host"]].append(r["path"])
    for h in sorted(denied):
        a.append(f'\t{go_str(h)}: {{')
        for p in sorted(set(denied[h])):
            a.append(f'\t\t{go_str(p)}: true,')
        a.append('\t},')
    a += ['}', '',
          '// isAllowedRead reports whether host+path is on the READ allowlist.',
          '//',
          '// Path templates in the inventory carry an id placeholder ({conversation_id},',
          '// ${e}, {0}). A concrete request substitutes a real id, so a literal map lookup',
          '// would miss it. Templates are therefore matched segment-wise, with the',
          '// placeholder segment accepting exactly one segment and nothing else — a',
          '// template can never widen into a prefix match.',
          'func isAllowedRead(host, path string) bool {',
          '\tpaths, ok := allowedReads[host]',
          '\tif !ok {',
          '\t\treturn false',
          '\t}',
          '\t// an explicit exclusion always wins over any template match',
          '\tif d, ok := deniedPaths[host]; ok && d[path] {',
          '\t\treturn false',
          '\t}',
          '\tif paths[path] {',
          '\t\treturn true',
          '\t}',
          '\tgot := strings.Split(strings.Trim(path, "/"), "/")',
          '\tfor tmpl := range paths {',
          '\t\tif !strings.ContainsAny(tmpl, "{$") {',
          '\t\t\tcontinue',
          '\t\t}',
          '\t\twant := strings.Split(strings.Trim(tmpl, "/"), "/")',
          '\t\tif len(want) != len(got) {',
          '\t\t\tcontinue',
          '\t\t}',
          '\t\tmatch := true',
          '\t\tfor i := range want {',
          '\t\t\tif strings.ContainsAny(want[i], "{$") {',
          '\t\t\t\tif got[i] == "" {',
          '\t\t\t\t\tmatch = false',
          '\t\t\t\t\tbreak',
          '\t\t\t\t}',
          '\t\t\t\tcontinue',
          '\t\t\t}',
          '\t\t\tif want[i] != got[i] {',
          '\t\t\t\tmatch = false',
          '\t\t\t\tbreak',
          '\t\t\t}',
          '\t\t}',
          '\t\tif match {',
          '\t\t\treturn true',
          '\t\t}',
          '\t}',
          '\treturn false',
          '}', '',
          '// allowlistSize is used by the coverage test and by `doctor`.',
          'func allowlistSize() int {',
          '\tn := 0',
          '\tfor _, m := range allowedReads {',
          '\t\tn += len(m)',
          '\t}',
          '\treturn n',
          '}', '']
    open(os.path.join(CLI, "allowlist.go"), "w").write("\n".join(a))

    # ---------------- cmd_<section>.go ----------------
    bysec = defaultdict(list)
    for r in reads:
        bysec[assign(r["path"])["name"]].append(r)

    made = 0
    for sec, srows in sorted(bysec.items()):
        grp = GROUP.get(sec, re.sub(r"[^a-z0-9]+", "-", sec.lower()))
        fn = "cmd_" + re.sub(r"[^a-z0-9]+", "_", grp) + ".go"
        goname = "new" + re.sub(r"[^A-Za-z0-9]", "", sec) + "Cmd"
        used = set()
        lines = ['package main', '',
                 '// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.',
                 f'// Section: {sec} — see vault/*/{sec}.md',
                 f'// Every command below maps to a READ row in the endpoint inventory;',
                 '// the writes and exports of this section are documented in the note and',
                 '// are not reachable from here.', '',
                 'import "github.com/spf13/cobra"', '',
                 f'func init() {{ registerSection({goname}) }}', '',
                 f'func {goname}(app *App) *cobra.Command {{',
                 f'\tg := &cobra.Command{{Use: {go_str(grp)}, '
                 f'Short: {go_str(sec.replace("-", " ") + " (read-only)")}}}',
                 '\tg.AddCommand(']
        for r in sorted(srows, key=lambda x: x["path"]):
            base = leaf_name(r["path"])
            name, i = base, 2
            while name in used:
                name = f"{base}-{i}"
                i += 1
            used.add(name)
            hc = HOSTCONST.get(r["host"])
            if not hc:
                continue
            short = f'{r["method"]} {r["path"]}'
            if r["const"]:
                short += f' ({r["const"].split(",")[0]})'
            builder = "readGet" if r["method"] == "GET" else "readPost"
            lines.append(f'\t\t{builder}(app, {go_str(grp)}, {go_str(name)}, '
                         f'{go_str(short)}, {hc}, {go_str(r["path"])}),')
        lines += ['\t)', '\treturn g', '}', '']
        open(os.path.join(CLI, fn), "w").write("\n".join(lines))
        made += 1

    print(f"allowlist.go: {len(reads)} read endpoints across {len(byhost)} hosts")
    print(f"command files: {made}")
    print(f"commands: {sum(len(v) for v in bysec.values())}")


if __name__ == "__main__":
    main()
