package main

// Code generated by scripts/gen_commands.py — DO NOT EDIT.

import "github.com/spf13/cobra"

func init() {
	registerSection(func(app *App) *cobra.Command {
		return buildSection(app, "Masters-Config", "masters", "Master data and configuration reads (units, designations, rates) (33 reads)")
	})
}
