package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Discounts-BDPO — see vault/*/Discounts-BDPO.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newDiscountsBDPOCmd) }

func newDiscountsBDPOCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "discounts", Short: "Discounts BDPO (read-only)"}
	g.AddCommand(
		readGet(app, "discounts", "campaign-file", "GET /api/discounting/v1/campaign/file", hostBrandPortal, "/api/discounting/v1/campaign/file"),
		readPost(app, "discounts", "campaign-search", "POST /api/discounting/v1/campaign/search", hostBrandPortal, "/api/discounting/v1/campaign/search"),
		readGet(app, "discounts", "campaign-spins", "GET /api/discounting/v1/campaign/spins", hostBrandPortal, "/api/discounting/v1/campaign/spins"),
		readPost(app, "discounts", "metrics-batch", "POST /api/discounting/v1/metrics/batch", hostBrandPortal, "/api/discounting/v1/metrics/batch"),
		readPost(app, "discounts", "discount-reports", "POST /api/v1/discount/reports (LIST_DISCOUNTS_REPORTS)", hostBrandPortal, "/api/v1/discount/reports"),
		readGet(app, "discounts", "account-get", "GET /im-discounts/v1/account/get", hostPartnerAPI, "/im-discounts/v1/account/get"),
		readGet(app, "discounts", "account-list", "GET /im-discounts/v1/account/list", hostPartnerAPI, "/im-discounts/v1/account/list"),
		readGet(app, "discounts", "account-permissions", "GET /im-discounts/v1/account/permissions", hostPartnerAPI, "/im-discounts/v1/account/permissions"),
		readGet(app, "discounts", "configs", "GET /im-discounts/v1/configs", hostPartnerAPI, "/im-discounts/v1/configs"),
	)
	return g
}
