package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Ads-AI-Chat — see vault/*/Ads-AI-Chat.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newAdsAIChatCmd) }

func newAdsAIChatCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "ads-chat", Short: "Ads AI Chat (read-only)"}
	g.AddCommand(
		readPost(app, "ads-chat", "conversations-list", "POST /api/v1/ads-chat/conversations/list (ADS_CHAT_LIST_SESSIONS)", hostBrandPortal, "/api/v1/ads-chat/conversations/list"),
		readPost(app, "ads-chat", "messages-list", "POST /api/v1/ads-chat/conversations/{conversation_id}/messages/list (ADS_CHAT_GET_SESSION)", hostBrandPortal, "/api/v1/ads-chat/conversations/{conversation_id}/messages/list"),
	)
	return g
}
