package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Catalog-SPIN-Management — see vault/*/Catalog-SPIN-Management.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newCatalogSPINManagementCmd) }

func newCatalogSPINManagementCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "catalog", Short: "Catalog SPIN Management (read-only)"}
	g.AddCommand(
		readPost(app, "catalog", "get-spin-change-attribute-details", "POST /v1/get_spin_change_attribute_details (GET_SPIN_CHANGE_ATTRIBUTE_DETAILS)", hostBrandPortal, "/v1/get_spin_change_attribute_details"),
		readPost(app, "catalog", "get-spin-change-workflow-details", "POST /v1/get_spin_change_workflow_details (GET_SPIN_CHANGE_WORKFLOW_DETAILS)", hostBrandPortal, "/v1/get_spin_change_workflow_details"),
		readPost(app, "catalog", "get-spin-details", "POST /v1/get_spin_details (GET_SPIN_DETAILS)", hostBrandPortal, "/v1/get_spin_details"),
		readPost(app, "catalog", "get-spin-metrics", "POST /v1/get_spin_metrics (GET_SPIN_METRICS)", hostBrandPortal, "/v1/get_spin_metrics"),
		readPost(app, "catalog", "list-spin-change-requests", "POST /v1/list_spin_change_requests (LIST_SPIN_CHANGE_REQUESTS)", hostBrandPortal, "/v1/list_spin_change_requests"),
		readPost(app, "catalog", "list-spins", "POST /v1/list_spins (LIST_SPINS)", hostBrandPortal, "/v1/list_spins"),
		readPost(app, "catalog", "search-brands", "POST /v1/search_brands (SEARCH_BRANDS)", hostBrandPortal, "/v1/search_brands"),
		readPost(app, "catalog", "search-categories", "POST /v1/search_categories (SEARCH_CATEGORIES)", hostBrandPortal, "/v1/search_categories"),
	)
	return g
}
