package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Goods-Received-GRN — see vault/*/Goods-Received-GRN.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newGoodsReceivedGRNCmd) }

func newGoodsReceivedGRNCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "grn", Short: "Goods Received GRN (read-only)"}
	g.AddCommand(
		readPost(app, "grn", "grn-search-grn-lines", "POST /api/v1/grn/searchGrnLines", hostPicker, "/api/v1/grn/searchGrnLines"),
		readPost(app, "grn", "search-grns", "POST /api/v1/searchGrns", hostPicker, "/api/v1/searchGrns"),
	)
	return g
}
