package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: NPI-New-Product-Introduction — see vault/*/NPI-New-Product-Introduction.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newNPINewProductIntroductionCmd) }

func newNPINewProductIntroductionCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "npi", Short: "NPI New Product Introduction (read-only)"}
	g.AddCommand(
		readPost(app, "npi", "suggest-placement", "POST /api/v1/suggest-placement (SUGGEST_PLACEMENT)", hostBrandPortal, "/api/v1/suggest-placement"),
	)
	return g
}
