package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Stock-On-Hand-and-Low-Stock — see vault/*/Stock-On-Hand-and-Low-Stock.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newStockOnHandandLowStockCmd) }

func newStockOnHandandLowStockCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "stock", Short: "Stock On Hand and Low Stock (read-only)"}
	g.AddCommand(
		readPost(app, "stock", "inventory-metrics", "POST /api/v1/inventory/metrics", hostPicker, "/api/v1/inventory/metrics"),
		readPost(app, "stock", "search-item-inventories", "POST /api/v1/inventory/search/itemInventories", hostPicker, "/api/v1/inventory/search/itemInventories"),
		readPost(app, "stock", "search-low-stock-fcs", "POST /api/v1/inventory/search/lowStockFcs", hostPicker, "/api/v1/inventory/search/lowStockFcs"),
	)
	return g
}
