package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Config-And-Feature-Flags — see vault/*/Config-And-Feature-Flags.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newConfigAndFeatureFlagsCmd) }

func newConfigAndFeatureFlagsCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "config", Short: "Config And Feature Flags (read-only)"}
	g.AddCommand(
		readGet(app, "config", "campaign-config", "GET /api/discounting/v1/campaign/config", hostBrandPortal, "/api/discounting/v1/campaign/config"),
		readGet(app, "config", "configs", "GET /instamart/v1/configs (FETCH_CONFIGS)", hostPartnerAPI, "/instamart/v1/configs"),
	)
	return g
}
