package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: PO-Booking-Appointments — see vault/*/PO-Booking-Appointments.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newPOBookingAppointmentsCmd) }

func newPOBookingAppointmentsCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "po-booking", Short: "PO Booking Appointments (read-only)"}
	g.AddCommand(
		readGet(app, "po-booking", "batch-list", "GET /api/v1/batch/list (BATCH_LIST)", hostPicker, "/api/v1/batch/list"),
	)
	return g
}
