package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Sampling-Campaigns — see vault/*/Sampling-Campaigns.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newSamplingCampaignsCmd) }

func newSamplingCampaignsCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "sampling", Short: "Sampling Campaigns (read-only)"}
	g.AddCommand(
		readPost(app, "sampling", "campaign", "POST /api/v1/campaign/{0} (GET_CAMPAIGN_DETAILS)", hostBrandPortal, "/api/v1/campaign/{0}"),
		readPost(app, "sampling", "spins-batch", "POST /api/v1/spins/batch (GET_PRODUCT_SPINS_BATCH)", hostBrandPortal, "/api/v1/spins/batch"),
	)
	return g
}
