package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Returns-RTV-and-Purchase-Returns — see vault/*/Returns-RTV-and-Purchase-Returns.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newReturnsRTVandPurchaseReturnsCmd) }

func newReturnsRTVandPurchaseReturnsCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "returns", Short: "Returns RTV and Purchase Returns (read-only)"}
	g.AddCommand(
		readPost(app, "returns", "return-metrics", "POST /api/v1/returnMetrics", hostPicker, "/api/v1/returnMetrics"),
		readPost(app, "returns", "search-rtv", "POST /api/v1/search/rtv", hostPicker, "/api/v1/search/rtv"),
		readPost(app, "returns", "search-rtv-lines", "POST /api/v1/search/rtvLines", hostPicker, "/api/v1/search/rtvLines"),
		readPost(app, "returns", "search-purchase-return-lines", "POST /api/v1/searchPurchaseReturnLines", hostPicker, "/api/v1/searchPurchaseReturnLines"),
		readPost(app, "returns", "search-purchase-returns", "POST /api/v1/searchPurchaseReturns", hostPicker, "/api/v1/searchPurchaseReturns"),
	)
	return g
}
