package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Brand-Insights-Metrics — see vault/*/Brand-Insights-Metrics.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newBrandInsightsMetricsCmd) }

func newBrandInsightsMetricsCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "brand-insights", Short: "Brand Insights Metrics (read-only)"}
	g.AddCommand(
		readPost(app, "brand-insights", "advertiser-metrics", "POST /api/v1/advertiser/metrics (BRAND_INSIGHTS_METRICS)", hostBrandPortal, "/api/v1/advertiser/metrics"),
		readPost(app, "brand-insights", "metrics-batch", "POST /api/v1/advertiser/metrics/batch (BRAND_INSIGHTS_GET_BATCH_ADVERTISER_METRICS)", hostBrandPortal, "/api/v1/advertiser/metrics/batch"),
		readPost(app, "brand-insights", "report-list", "POST /api/v1/advertiser/metrics/report/list (LIST_CUSTOM_REPORTS)", hostBrandPortal, "/api/v1/advertiser/metrics/report/list"),
		readPost(app, "brand-insights", "metrics", "POST /instamart/v1/metrics (METRICS)", hostPartnerAPI, "/instamart/v1/metrics"),
	)
	return g
}
