package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Accounts-And-Entities — see vault/*/Accounts-And-Entities.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newAccountsAndEntitiesCmd) }

func newAccountsAndEntitiesCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "accounts", Short: "Accounts And Entities (read-only)"}
	g.AddCommand(
		readGet(app, "accounts", "account-permissions", "GET /api/v1/account/permissions (ACCOUNT_PERMISSIONS)", hostBrandPortal, "/api/v1/account/permissions"),
		readGet(app, "accounts", "account-get", "GET /instamart/v1/account/get (ACCOUNT_GET)", hostPartnerAPI, "/instamart/v1/account/get"),
		readGet(app, "accounts", "account-list", "GET /instamart/v1/account/list (ACCOUNT_LIST)", hostPartnerAPI, "/instamart/v1/account/list"),
		readGet(app, "accounts", "account-permissions-2", "GET /instamart/v1/account/permissions (ACCOUNT_PERMISSIONS)", hostPartnerAPI, "/instamart/v1/account/permissions"),
	)
	return g
}
