package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Vendor-Performance-Scores — see vault/*/Vendor-Performance-Scores.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newVendorPerformanceScoresCmd) }

func newVendorPerformanceScoresCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "vendor-perf", Short: "Vendor Performance Scores (read-only)"}
	g.AddCommand(
		readPost(app, "vendor-perf", "search-supplier-performance-metrics", "POST /api/v1/searchSupplierPerformanceMetrics", hostPicker, "/api/v1/searchSupplierPerformanceMetrics"),
	)
	return g
}
