package main

// Code generated by captures/build_cli.py. DO NOT EDIT BY HAND.
// Section: Purchase-Orders — see vault/*/Purchase-Orders.md
// Every command below maps to a READ row in the endpoint inventory;
// the writes and exports of this section are documented in the note and
// are not reachable from here.

import "github.com/spf13/cobra"

func init() { registerSection(newPurchaseOrdersCmd) }

func newPurchaseOrdersCmd(app *App) *cobra.Command {
	g := &cobra.Command{Use: "po", Short: "Purchase Orders (read-only)"}
	g.AddCommand(
		readPost(app, "po", "list-all-fcs", "POST /api/v1/listAllFCs", hostPicker, "/api/v1/listAllFCs"),
		readPost(app, "po", "list-purchase-order-lines", "POST /api/v1/listPurchaseOrderLines (GET_ITEM_LIST_DATA)", hostPicker, "/api/v1/listPurchaseOrderLines"),
		readPost(app, "po", "purchase-metrics", "POST /api/v1/purchaseMetrics", hostPicker, "/api/v1/purchaseMetrics"),
		readPost(app, "po", "search-purchase-order", "POST /api/v1/searchPurchaseOrder (GET_PO_DETAILS)", hostPicker, "/api/v1/searchPurchaseOrder"),
	)
	return g
}
