// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
	"jivo-pp-cli/internal/cli"
	"jivo-pp-cli/internal/client"
	"jivo-pp-cli/internal/config"
	"jivo-pp-cli/internal/mcp/cobratree"
	"jivo-pp-cli/internal/store"
)

const (
	mcpToolResultMaxBytes = 60000
	mcpToolResultMaxItems = 50
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("accounts_aging-beverages",
			mcplib.WithDescription("Beverages A/R aging as a pre-bucketed pivot (grouped by salesperson) with KPIs and totals. Optional: as_of."),
			mcplib.WithString("as_of", mcplib.Description("Age balances to this date (YYYY-MM-DD; default today).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/customer-aging-beverages/", true, false, nil, []mcpParamBinding{{PublicName: "as_of", WireName: "as_of", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("accounts_aging-mart",
			mcplib.WithDescription("Mart A/R aging as a pre-bucketed pivot by Format with book KPIs and totals. Optional: as_of."),
			mcplib.WithString("as_of", mcplib.Description("Age balances to this date (YYYY-MM-DD; default today).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/customer-aging-mart/", true, false, nil, []mcpParamBinding{{PublicName: "as_of", WireName: "as_of", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("accounts_aging-oil",
			mcplib.WithDescription("Oil company open A/R ledger as a flat per-open-invoice list (aged to as_of). Optional: as_of."),
			mcplib.WithString("as_of", mcplib.Description("Age balances to this date (YYYY-MM-DD; default today).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/customer-aging-oil-ar/", true, false, nil, []mcpParamBinding{{PublicName: "as_of", WireName: "as_of", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("accounts_claims",
			mcplib.WithDescription("Full claim register (hand-maintained customer claims) plus the customer master picklist."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/claims/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("accounts_open-payments",
			mcplib.WithDescription("Customer payments on account (receipts not yet applied to invoices) for a date range. Required: start_date, end_date."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Receipt range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Receipt range end (YYYY-MM-DD).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/open-payments/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("credit_required-limit",
			mcplib.WithDescription("Required credit limits per ASM (Total Outstanding + 2%), lock state, as-of date — read from the page's embedded JSON."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/required-credit-limit/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_daily-production",
			mcplib.WithDescription("Standard work-order (OWOR) production transactions for a date range — planned vs completed, warehouse, status, user. Optional: start, end."),
			mcplib.WithString("start", mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end", mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/daily-production/api/data/", true, false, nil, []mcpParamBinding{{PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "end", WireName: "end", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_non-moving",
			mcplib.WithDescription("Every in-stock finished good with ageing / movement signals (DaysInStock, DaysSinceMoved, last customer, qty/litres/value). Optional: schema."),
			mcplib.WithString("schema", mcplib.Description("Company DB: jivo_oil (default) | jivo_mart | jivo_beverages.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/non-inventory/api/data/", true, false, nil, []mcpParamBinding{{PublicName: "schema", WireName: "schema", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_non-moving-drill",
			mcplib.WithDescription("Per-warehouse breakdown of a single finished good (code, name, qty, lot production date). Required: schema, item. Optional: whs."),
			mcplib.WithString("schema", mcplib.Required(), mcplib.Description("Company DB (same as parent page).")),
			mcplib.WithString("item", mcplib.Required(), mcplib.Description("SAP FG ItemCode to drill, e.g. FG0000441.")),
			mcplib.WithString("whs", mcplib.Description("Comma-separated warehouse codes to restrict to (optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/non-inventory/api/drill/", true, false, nil, []mcpParamBinding{{PublicName: "schema", WireName: "schema", Location: "query"}, {PublicName: "item", WireName: "item", Location: "query"}, {PublicName: "whs", WireName: "whs", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_production-feasibility",
			mcplib.WithDescription("Read-only feasibility check for one FG at a requested qty: max producible count + per-component sufficiency (no production occurs). Required: fg_code. Optional: qty, warehouses."),
			mcplib.WithString("fg_code", mcplib.Required(), mcplib.Description("FG code to check, e.g. FG0000149.")),
			mcplib.WithString("qty", mcplib.Description("Planned FG quantity to test (optional).")),
			mcplib.WithString("warehouses", mcplib.Description("ALL or comma-separated warehouse codes ('Stock from' selection).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/production/api/feasibility/", true, false, nil, []mcpParamBinding{{PublicName: "fg_code", WireName: "fg_code", Location: "query"}, {PublicName: "qty", WireName: "qty", Location: "query"}, {PublicName: "warehouses", WireName: "warehouses", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_production-fg-list",
			mcplib.WithDescription("Catalogue of manufacturable finished goods (those with a BOM) for the production-plan picker."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/production/api/fg-list/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_production-warehouses",
			mcplib.WithDescription("Full warehouse master (code + name) for the 'Stock from' selector."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/production/api/warehouses/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_reconciliation",
			mcplib.WithDescription("Wellness-Mart inter-company billing chains (PO -> SO -> GRPO -> A/P -> A/R) classified MATCHED/MISMATCH/INCOMPLETE. Optional: schema, date_from, date_to."),
			mcplib.WithString("schema", mcplib.Description("Seller company: oil (default) | beverages.")),
			mcplib.WithString("date_from", mcplib.Description("Window start (YYYY-MM-DD, optional; server default ~last 3 months).")),
			mcplib.WithString("date_to", mcplib.Description("Window end (YYYY-MM-DD, optional; server default today).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/reconciliation/api/data/", true, false, nil, []mcpParamBinding{{PublicName: "schema", WireName: "schema", Location: "query"}, {PublicName: "date_from", WireName: "date_from", Location: "query"}, {PublicName: "date_to", WireName: "date_to", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_reconciliation-ledgers",
			mcplib.WithDescription("BP ledgers behind the Wellness-Mart reconciliation, pivoted by document-type origin for each side (Mart vs Wellness). Optional: schema, date_from, date_to."),
			mcplib.WithString("schema", mcplib.Description("Seller company: oil | beverages.")),
			mcplib.WithString("date_from", mcplib.Description("Window start (YYYY-MM-DD, optional).")),
			mcplib.WithString("date_to", mcplib.Description("Window end (YYYY-MM-DD, optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/reconciliation/api/ledgers/", true, false, nil, []mcpParamBinding{{PublicName: "schema", WireName: "schema", Location: "query"}, {PublicName: "date_from", WireName: "date_from", Location: "query"}, {PublicName: "date_to", WireName: "date_to", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("inventory_stock",
			mcplib.WithDescription("Live finished-goods on-hand stock for one company: type summaries + per-SKU x per-warehouse rows. Optional: schema."),
			mcplib.WithString("schema", mcplib.Description("Company DB: jivo_oil (default) | jivo_mart | jivo_beverages.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/inventory/stock-available/api/data/", true, false, nil, []mcpParamBinding{{PublicName: "schema", WireName: "schema", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("masterdata_calculator-items",
			mcplib.WithDescription("SAP finished-goods item master for the realise-calculator picker (code, name, variety, sku, pcs/box, box litres)."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/realise-calculator/items/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("masterdata_customer-master",
			mcplib.WithDescription("Entire customer master (contact, tax, address, terms, credit limit, balance, status) in one payload. code is the join key."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/customer-master/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("masterdata_rate-list",
			mcplib.WithDescription("Saved realise-calculator results (rate lists). Pass --id to fetch a single saved result. Optional: id."),
			mcplib.WithNumber("id", mcplib.Description("Return only the saved result with this id (optional; omit to list all).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/rate-list/", true, false, nil, []mcpParamBinding{{PublicName: "id", WireName: "id", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("oih_breakdown",
			mcplib.WithDescription("Line-level OIH breakdown, one row per open SO line, split premium vs commodity value and pieces."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/oih-breakdown/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("oih_commodity-rows",
			mcplib.WithDescription("OIH open-order rows filtered to commodity oils (u_type=COMMODITY). Optional: start, end."),
			mcplib.WithString("start", mcplib.Description("Range start (YYYY-MM-DD, optional).")),
			mcplib.WithString("end", mcplib.Description("Range end (YYYY-MM-DD, optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/commodity-oih-rows/", true, false, nil, []mcpParamBinding{{PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "end", WireName: "end", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("oih_rows",
			mcplib.WithDescription("OIH as individual open-order rows (open litres per item/customer). Optional: start, end."),
			mcplib.WithString("start", mcplib.Description("Range start (YYYY-MM-DD, optional).")),
			mcplib.WithString("end", mcplib.Description("Range end (YYYY-MM-DD, optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/order-in-hand-rows/", true, false, nil, []mcpParamBinding{{PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "end", WireName: "end", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("oih_summary",
			mcplib.WithDescription("Total OIH value summarised per salesperson."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/order-in-hand/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_beverages",
			mcplib.WithDescription("BEVERAGES dataset feed: beverage sales lines, day-over-day box comparison, customer grading, month rollup and beverage OIH. Required: start_date, end_date."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/beverages-data/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_beverages-docs",
			mcplib.WithDescription("Documents (invoices / SOs) behind a beverages node — lazily fetched per drilled node. Required: metric, start, end. Optional: f_brand, f_ym."),
			mcplib.WithString("metric", mcplib.Required(), mcplib.Description("Node measure, e.g. quantity | boxes | oih.")),
			mcplib.WithString("start", mcplib.Required(), mcplib.Description("Beverages range start (YYYY-MM-DD).")),
			mcplib.WithString("end", mcplib.Required(), mcplib.Description("Beverages range end (YYYY-MM-DD).")),
			mcplib.WithString("f_brand", mcplib.Description("Active brand filter (optional).")),
			mcplib.WithString("f_ym", mcplib.Description("Active month filter YYYY-MM (optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/beverages-docs/", true, false, nil, []mcpParamBinding{{PublicName: "metric", WireName: "metric", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "end", WireName: "end", Location: "query"}, {PublicName: "f_brand", WireName: "f_brand", Location: "query"}, {PublicName: "f_ym", WireName: "f_ym", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_channel-docs",
			mcplib.WithDescription("Documents behind a Slide-2 channel card cell — invoices (done) or open SOs (oih), with per-line items and per-warehouse stock. Optional: channel, metric, seg (plus 8 more)."),
			mcplib.WithString("channel", mcplib.Description("Channel / main-group code (GT, MT, ECOM...); empty = all.")),
			mcplib.WithString("metric", mcplib.Description("done (invoices) or oih (open SOs). Default done.")),
			mcplib.WithString("seg", mcplib.Description("Segment scope, e.g. OILS.")),
			mcplib.WithString("start", mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end", mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithString("group", mcplib.Description("Main Group filter (optional).")),
			mcplib.WithString("state", mcplib.Description("State filter (optional).")),
			mcplib.WithString("person", mcplib.Description("Territory owner filter (optional).")),
			mcplib.WithString("product", mcplib.Description("Product / sub-group filter (optional).")),
			mcplib.WithString("item", mcplib.Description("Item filter (optional).")),
			mcplib.WithString("customer", mcplib.Description("Customer filter (optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/channel-detail-docs/", true, false, nil, []mcpParamBinding{{PublicName: "channel", WireName: "channel", Location: "query"}, {PublicName: "metric", WireName: "metric", Location: "query"}, {PublicName: "seg", WireName: "seg", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "end", WireName: "end", Location: "query"}, {PublicName: "group", WireName: "group", Location: "query"}, {PublicName: "state", WireName: "state", Location: "query"}, {PublicName: "person", WireName: "person", Location: "query"}, {PublicName: "product", WireName: "product", Location: "query"}, {PublicName: "item", WireName: "item", Location: "query"}, {PublicName: "customer", WireName: "customer", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_cn",
			mcplib.WithDescription("Line-level gross sales vs credit-note rows for one company (oil|beverages) over a date range. Required: start_date, end_date. Optional: company."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithString("company", mcplib.Description("Company books: oil (default) or beverages.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/sales-cn/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}, {PublicName: "company", WireName: "company", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_compare-docs",
			mcplib.WithDescription("Invoice-level drill-down behind a Compare-Sales pivot cell (one month range plus optional dimension filters). Required: start_date, end_date. Optional: seg, group, state (plus 4 more)."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("1st of the clicked month (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Last day of the clicked month (YYYY-MM-DD).")),
			mcplib.WithString("seg", mcplib.Description("Type filter: PREMIUM | COMMODITY | empty.")),
			mcplib.WithString("group", mcplib.Description("Main Group narrowing (optional).")),
			mcplib.WithString("state", mcplib.Description("State narrowing (optional).")),
			mcplib.WithString("person", mcplib.Description("Territory owner narrowing (optional).")),
			mcplib.WithString("product", mcplib.Description("Product / sub-group narrowing (optional).")),
			mcplib.WithString("item", mcplib.Description("Item name narrowing (optional).")),
			mcplib.WithString("customer", mcplib.Description("Customer narrowing (optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/compare-docs/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}, {PublicName: "seg", WireName: "seg", Location: "body"}, {PublicName: "group", WireName: "group", Location: "body"}, {PublicName: "state", WireName: "state", Location: "body"}, {PublicName: "person", WireName: "person", Location: "body"}, {PublicName: "product", WireName: "product", Location: "body"}, {PublicName: "item", WireName: "item", Location: "body"}, {PublicName: "customer", WireName: "customer", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_data",
			mcplib.WithDescription("Core OILS realise feed: per-product litres/₹/realise/target rows plus flattened channel + month line-item rows for a date range. Required: start_date, end_date. Optional: refresh."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Range start (YYYY-MM-DD). Use a single day to sample.")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithBoolean("refresh", mcplib.Description("Force server recompute / cache-bust.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/sales-data/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}, {PublicName: "refresh", WireName: "refresh", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_dispatch",
			mcplib.WithDescription("Per-invoice physical dispatch / freight metadata (bilty, transporter, vehicle, driver) for a date range. Required: start_date, end_date."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/dispatch-details/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_drill-down",
			mcplib.WithDescription("Expand one Slide-1 product row into a chosen dimension (litres + linetotal per value). drill_by is case-sensitive (State|U_Main_Group|U_Chain|ItemName|CardName). Required: start_date, end_date, u_type, u_sub_group, drill_by. Optional: filters, month, year."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithString("u_type", mcplib.Required(), mcplib.Description("Product tier, e.g. PREMIUM / COMMODITY.")),
			mcplib.WithString("u_sub_group", mcplib.Required(), mcplib.Description("Product variety, e.g. OLIVE, MUSTARD.")),
			mcplib.WithString("drill_by", mcplib.Required(), mcplib.Description("Pascal-case dimension: State | U_Main_Group | U_Chain | ItemName | CardName.")),
			mcplib.WithString("filters", mcplib.Description("Accumulated parent-drill path filters as JSON, e.g. {'State':'HARYANA'}; {} at top level.")),
			mcplib.WithString("month", mcplib.Description("Month filter (optional).")),
			mcplib.WithString("year", mcplib.Description("Year filter (optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/drill-down/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}, {PublicName: "u_type", WireName: "u_type", Location: "body"}, {PublicName: "u_sub_group", WireName: "u_sub_group", Location: "body"}, {PublicName: "drill_by", WireName: "drill_by", Location: "body"}, {PublicName: "filters", WireName: "filters", Location: "body"}, {PublicName: "month", WireName: "month", Location: "body"}, {PublicName: "year", WireName: "year", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_flow",
			mcplib.WithDescription("Sales document chains (Quotation -> Order -> Invoice) with open/closed status and source, for a date range and company. Required: start_date, end_date. Optional: company."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithString("company", mcplib.Description("oil (default) or beverages.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/sales-flow/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}, {PublicName: "company", WireName: "company", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_flow-open-items",
			mcplib.WithDescription("Drill-down: still-open line items of a single open Sales Order or Quotation. Required: doc_type, doc_no. Optional: company."),
			mcplib.WithString("doc_type", mcplib.Required(), mcplib.Description("order or quotation.")),
			mcplib.WithString("doc_no", mcplib.Required(), mcplib.Description("SAP document number.")),
			mcplib.WithString("company", mcplib.Description("oil (default) or beverages — must match the row.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/sales-flow/open-items/", true, false, nil, []mcpParamBinding{{PublicName: "doc_type", WireName: "doc_type", Location: "body"}, {PublicName: "doc_no", WireName: "doc_no", Location: "body"}, {PublicName: "company", WireName: "company", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_hidden",
			mcplib.WithDescription("Hidden sales-invoice lines (SAP U_ARNO='H') over a date range — oil company only. Required: start_date, end_date."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Range end (YYYY-MM-DD).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/hidden-sales/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_historical",
			mcplib.WithDescription("Trailing-period average realise (₹/L) per product and per drilled dimension, as a Slide-1 overlay. Required: start_date, end_date. Optional: period."),
			mcplib.WithString("start_date", mcplib.Required(), mcplib.Description("Anchor range start (YYYY-MM-DD).")),
			mcplib.WithString("end_date", mcplib.Required(), mcplib.Description("Anchor range end (YYYY-MM-DD).")),
			mcplib.WithString("period", mcplib.Description("Trailing window: 12m | 6m | 3m | last_month. Empty = off.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("POST", "/realise/api/historical-realise/", true, false, nil, []mcpParamBinding{{PublicName: "start_date", WireName: "start_date", Location: "body"}, {PublicName: "end_date", WireName: "end_date", Location: "body"}, {PublicName: "period", WireName: "period", Location: "body"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("sales_pulse",
			mcplib.WithDescription("Cheap change-fingerprint / heartbeat for the Realise backend (empty pulse = no signal). Detect change, not data. Optional: dataset, start, end."),
			mcplib.WithString("dataset", mcplib.Description("oils | beverages.")),
			mcplib.WithString("start", mcplib.Description("Active window start (YYYY-MM-DD).")),
			mcplib.WithString("end", mcplib.Description("Active window end (YYYY-MM-DD).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/sales-pulse/", true, false, nil, []mcpParamBinding{{PublicName: "dataset", WireName: "dataset", Location: "query"}, {PublicName: "start", WireName: "start", Location: "query"}, {PublicName: "end", WireName: "end", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("targets_channel",
			mcplib.WithDescription("Monthly target litres per sales channel (main group). Optional: month, year."),
			mcplib.WithNumber("month", mcplib.Description("Target month 1-12.")),
			mcplib.WithNumber("year", mcplib.Description("Target year.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/channel-targets/", true, false, nil, []mcpParamBinding{{PublicName: "month", WireName: "month", Location: "query"}, {PublicName: "year", WireName: "year", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("targets_flex",
			mcplib.WithDescription("Flex (flat, dimension-scoped) litre targets — currently per salesperson — for the target month. Optional: seg, month, year."),
			mcplib.WithString("seg", mcplib.Description("Segment scope, e.g. OILS, BEVERAGES.")),
			mcplib.WithNumber("month", mcplib.Description("Target month 1-12 (optional).")),
			mcplib.WithNumber("year", mcplib.Description("Target year (optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/flex-targets/", true, false, nil, []mcpParamBinding{{PublicName: "seg", WireName: "seg", Location: "query"}, {PublicName: "month", WireName: "month", Location: "query"}, {PublicName: "year", WireName: "year", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("targets_list",
			mcplib.WithDescription("Product-level monthly targets (tgt_ltrs, tgt_rate, source) keyed by U_TYPE|SUB_GROUP. Optional: month, year."),
			mcplib.WithNumber("month", mcplib.Description("Target month 1-12.")),
			mcplib.WithNumber("year", mcplib.Description("Target year (four-digit).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/targets/", true, false, nil, []mcpParamBinding{{PublicName: "month", WireName: "month", Location: "query"}, {PublicName: "year", WireName: "year", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("targets_nodes",
			mcplib.WithDescription("Granular target nodes: target litres by main_group x state x sales_person x segment for a month. Optional: month, year, seg."),
			mcplib.WithNumber("month", mcplib.Description("Target month 1-12.")),
			mcplib.WithNumber("year", mcplib.Description("Target year.")),
			mcplib.WithString("seg", mcplib.Description("Segment scope, e.g. OILS, BEVERAGES.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/target-nodes/", true, false, nil, []mcpParamBinding{{PublicName: "month", WireName: "month", Location: "query"}, {PublicName: "year", WireName: "year", Location: "query"}, {PublicName: "seg", WireName: "seg", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("targets_segment",
			mcplib.WithDescription("Saved target overrides scoped to a single segment (empty {} when no overrides saved). Required: segment. Optional: month, year, seg."),
			mcplib.WithString("segment", mcplib.Required(), mcplib.Description("Segment name (server lower-cases it), e.g. OILS.")),
			mcplib.WithNumber("month", mcplib.Description("Target month 1-12 (optional).")),
			mcplib.WithNumber("year", mcplib.Description("Target year (optional).")),
			mcplib.WithString("seg", mcplib.Description("Secondary segment scope (optional).")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/realise/api/segment-targets/", true, false, nil, []mcpParamBinding{{PublicName: "segment", WireName: "segment", Location: "query"}, {PublicName: "month", WireName: "month", Location: "query"}, {PublicName: "year", WireName: "year", Location: "query"}, {PublicName: "seg", WireName: "seg", Location: "query"}}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users_catalog",
			mcplib.WithDescription("Permission-module catalog used by the Users page — read-only, from the page's embedded JSON."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	s.AddTool(
		mcplib.NewTool("users_list",
			mcplib.WithDescription("Admin user list + roles/permission groups — read-only, from the page's embedded JSON."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		makeAPIHandler("GET", "/users/", true, false, nil, []mcpParamBinding{}, []string{}),
	)
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='items'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

type mcpParamBinding struct {
	PublicName string
	WireName   string
	Location   string
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		return fmt.Sprintf("%v", v)
	}
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				continue
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("authentication failed: " + msg +
					"\nhint: check your API credentials." +
					"\n      Run 'jivo-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("permission denied: " + msg +
					"\nhint: this API is configured without credentials; the service may be blocking the request by rate limit, geography, bot protection, or endpoint policy." +
					"\n      Run 'jivo-pp-cli doctor' to check auth status."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			out, _ := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      base64.StdEncoding.EncodeToString(data),
				"byte_count":       len(data),
			})
			return mcplib.NewToolResultText(string(out)), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	trimmed := strings.TrimSpace(string(data))
	if strings.EqualFold(method, "GET") && len(trimmed) > 0 && trimmed[0] == '[' {
		var items []json.RawMessage
		if json.Unmarshal(data, &items) == nil {
			return mcplib.NewToolResultText(string(mcpBoundedListEnvelope("items", items, len(data))))
		}
	}
	if len(data) <= mcpToolResultMaxBytes {
		return mcplib.NewToolResultText(string(data))
	}
	if strings.EqualFold(method, "GET") {
		if out, ok := mcpBoundedSingleArrayObject(data); ok {
			return mcplib.NewToolResultText(string(out))
		}
	}
	return mcplib.NewToolResultText(string(mcpOversizedPreviewEnvelope(data)))
}

func mcpBoundedSingleArrayObject(data json.RawMessage) ([]byte, bool) {
	var obj map[string]json.RawMessage
	if json.Unmarshal(data, &obj) != nil {
		return nil, false
	}
	arrayField := ""
	var items []json.RawMessage
	for key, raw := range obj {
		trimmed := strings.TrimSpace(string(raw))
		if len(trimmed) == 0 || trimmed[0] != '[' {
			continue
		}
		var candidate []json.RawMessage
		if json.Unmarshal(raw, &candidate) != nil {
			continue
		}
		if arrayField != "" {
			return nil, false
		}
		arrayField = key
		items = candidate
	}
	if arrayField == "" {
		return nil, false
	}
	build := func(subset []json.RawMessage) any {
		out := make(map[string]any, len(obj)+6)
		for key, raw := range obj {
			if key == arrayField {
				out[key] = subset
				continue
			}
			out[key] = raw
		}
		if len(subset) < len(items) {
			out["_pp_truncated"] = true
			out["_pp_total_count"] = len(items)
			out["_pp_returned_count"] = len(subset)
			out["_pp_original_bytes"] = len(data)
			out["_pp_max_bytes"] = mcpToolResultMaxBytes
			out["_pp_note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	out := mcpFitJSONItems(items, build)
	if len(out) > mcpToolResultMaxBytes {
		return nil, false
	}
	return out, true
}

func mcpBoundedListEnvelope(field string, items []json.RawMessage, originalBytes int) []byte {
	build := func(subset []json.RawMessage) any {
		out := map[string]any{
			"count": len(items),
			field:   subset,
		}
		if len(subset) < len(items) {
			out["truncated"] = true
			out["returned_count"] = len(subset)
			out["original_bytes"] = originalBytes
			out["max_bytes"] = mcpToolResultMaxBytes
			out["note"] = "Typed MCP endpoint response exceeded the tool result budget. Narrow the request with limit, offset, filters, search/sql, or a command-mirror tool with --agent/--compact/--select."
		}
		return out
	}
	return mcpFitJSONItems(items, build)
}

func mcpFitJSONItems(items []json.RawMessage, build func([]json.RawMessage) any) []byte {
	limit := len(items)
	if limit > mcpToolResultMaxItems {
		limit = mcpToolResultMaxItems
	}
	for n := limit; n >= 0; n-- {
		out, err := json.Marshal(build(items[:n]))
		if err != nil {
			continue
		}
		if len(out) <= mcpToolResultMaxBytes || n == 0 {
			return out
		}
	}
	out, _ := json.Marshal(build(items[:0]))
	return out
}

func mcpOversizedPreviewEnvelope(data json.RawMessage) []byte {
	previewBytes := data
	if len(previewBytes) > 4000 {
		previewBytes = previewBytes[:4000]
	}
	out, _ := json.Marshal(map[string]any{
		"truncated":      true,
		"original_bytes": len(data),
		"max_bytes":      mcpToolResultMaxBytes,
		"preview":        string(previewBytes),
		"note":           "Typed MCP endpoint response exceeded the tool result budget and was not a recognized list envelope. Narrow the request with filters, search/sql, or a command-mirror tool with --agent/--compact/--select.",
	})
	return out
}

func newMCPClient() (*client.Client, error) {
	home, _ := os.UserHomeDir()
	cfgPath := filepath.Join(home, ".config", "jivo-pp-cli", "config.toml")
	cfg, err := config.Load(cfgPath)
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c, nil
}

func dbPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".local", "share", "jivo-pp-cli", "data.db")
}

// Note: MCP tools use their own dbPath() because they are in a separate package (main, not cli).
// The CLI's defaultDBPath() in the cli package uses the same canonical path.

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}

	return toolResultJSON(results)
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	db, err := store.OpenReadOnly(dbPath())
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("opening database: %v", err)), nil
	}
	defer db.Close()

	rows, err := db.Query(query)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("query failed: %v", err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}

	return toolResultJSON(results)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	data, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	ctx := map[string]any{
		"api":         "jivo",
		"description": "Jivo Group — Control Panel",
		"archetype":   "crm",
		"tool_count":  42,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion jivo-pp-cli binary.",
		"resources": []map[string]any{
			{
				"name":        "accounts",
				"description": "Accounts receivable — customer aging (oil AR flat, mart & beverages pre-bucketed), on-account payments",
				"endpoints":   []string{"aging-beverages", "aging-mart", "aging-oil", "claims", "open-payments"},
				"searchable":  true,
			},
			{
				"name":        "credit",
				"description": "Required Credit Limit page — no JSON API; data is embedded in the page HTML.",
				"endpoints":   []string{"required-limit"},
			},
			{
				"name":        "inventory",
				"description": "Inventory & production — live on-hand stock, non-moving/ageing stock, production feasibility & catalogues",
				"endpoints":   []string{"daily-production", "non-moving", "non-moving-drill", "production-feasibility", "production-fg-list", "production-warehouses", "reconciliation", "reconciliation-ledgers", "stock"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "masterdata",
				"description": "Reference master data — customer master, saved realise-calculator rate lists, and the FG item master.",
				"endpoints":   []string{"calculator-items", "customer-master", "rate-list"},
				"syncable":    true,
			},
			{
				"name":        "oih",
				"description": "Order In Hand (open, uninvoiced sales orders) — line breakdown, per-person totals, and open-quantity rows.",
				"endpoints":   []string{"breakdown", "commodity-rows", "rows", "summary"},
				"searchable":  true,
			},
			{
				"name":        "sales",
				"description": "Sales realise dashboard feeds — per-product realise, credit notes, hidden sales, document flow, dispatch",
				"endpoints":   []string{"beverages", "beverages-docs", "channel-docs", "cn", "compare-docs", "data", "dispatch", "drill-down", "flow", "flow-open-items", "hidden", "historical", "pulse"},
				"searchable":  true,
			},
			{
				"name":        "targets",
				"description": "Monthly target layer — product, flex (per-salesperson), segment, node (main-group x state x person x segment)",
				"endpoints":   []string{"channel", "flex", "list", "nodes", "segment"},
				"syncable":    true,
				"searchable":  true,
			},
			{
				"name":        "users",
				"description": "User Management (Admin) page — no JSON API; data is embedded in the page HTML.",
				"endpoints":   []string{"catalog", "list"},
				"syncable":    true,
			},
		},
		"query_tips": []string{
			"Pagination uses cursor-based paging. Pass after parameter for subsequent pages.",
			"Control page size with the limit parameter (default 100).",
			"Use the sql tool for ad-hoc analysis on synced data. Run sync first to populate the local database.",
			"Use the search tool for full-text search across all synced resources. Faster than iterating list endpoints.",
			"Prefer sql/search over repeated API calls when the data is already synced.",
		},
		"playbook": []map[string]string{
			{"topic": "Contact lookup", "insight": "Use search for finding contacts by name/email. List endpoints return unsorted results and require pagination for large datasets."},
			{"topic": "Activity tracking", "insight": "When checking deal activity, sync first and query locally. CRM APIs often throttle activity-log endpoints heavily."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
