// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAttendanceAttendanceRecordsCmd(flags *rootFlags) *cobra.Command {
	var flagDate string
	var flagDateFrom string
	var flagDateTo string
	var flagEmployee int
	var flagDepartment int
	var flagDirection string

	cmd := &cobra.Command{
		Use:         "attendance-records",
		Short:       "List manual attendance marks (IN/OUT punches with photo proof) for a date or date range.",
		Example:     "  jivo-factory-pp-cli attendance attendance-records",
		Annotations: map[string]string{"pp:endpoint": "attendance.attendance-records", "pp:method": "GET", "pp:path": "/attendance/records/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/attendance/records/"
			params := map[string]string{}
			if flagDate != "" {
				params["date"] = formatCLIParamValue(flagDate)
			}
			if flagDateFrom != "" {
				params["date_from"] = formatCLIParamValue(flagDateFrom)
			}
			if flagDateTo != "" {
				params["date_to"] = formatCLIParamValue(flagDateTo)
			}
			if flagEmployee != 0 {
				params["employee"] = formatCLIParamValue(flagEmployee)
			}
			if flagDepartment != 0 {
				params["department"] = formatCLIParamValue(flagDepartment)
			}
			if flagDirection != "" {
				params["direction"] = formatCLIParamValue(flagDirection)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "attendance", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDate, "date", "", "Single day.")
	cmd.Flags().StringVar(&flagDateFrom, "date-from", "", "Start of range, inclusive. Verified accepted live. (YYYY-MM-DD)")
	cmd.Flags().StringVar(&flagDateTo, "date-to", "", "End of range, inclusive. (YYYY-MM-DD)")
	cmd.Flags().IntVar(&flagEmployee, "employee", 0, "Employee id from /attendance/employees/ (NOT the employee_code string).")
	cmd.Flags().IntVar(&flagDepartment, "department", 0, "Department id from /accounts/departments/ (1=IT, 2=Ecom, 3=Account, 4=Store, 5=Others, 6=Mess, 8=production")
	cmd.Flags().StringVar(&flagDirection, "direction", "", "The React client never sends this on the list")

	return cmd
}
