// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDashboardsStockExportCmd(flags *rootFlags) *cobra.Command {
	var flagSearch string
	var flagItemGroup string
	var flagWarehouse string
	var flagStatus string
	var flagMovementStatus string
	var flagSortBy string
	var flagSortDir string
	var flagAsOfDate string

	cmd := &cobra.Command{
		Use:         "stock-export",
		Short:       "Download the whole stock-benchmark view as an Excel file (.xlsx) — the same rows and filters as the on-screen stock dashboard, but not capped to a page.",
		Example:     "  jivo-factory-pp-cli dashboards stock-export",
		Annotations: map[string]string{"pp:endpoint": "dashboards.stock-export", "pp:method": "GET", "pp:path": "/dashboards/stock/export/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/dashboards/stock/export/"
			params := map[string]string{}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagItemGroup != "" {
				params["item_group"] = formatCLIParamValue(flagItemGroup)
			}
			if flagWarehouse != "" {
				params["warehouse"] = formatCLIParamValue(flagWarehouse)
			}
			if flagStatus != "" {
				params["status"] = formatCLIParamValue(flagStatus)
			}
			if flagMovementStatus != "" {
				params["movement_status"] = formatCLIParamValue(flagMovementStatus)
			}
			if flagSortBy != "" {
				params["sort_by"] = formatCLIParamValue(flagSortBy)
			}
			if flagSortDir != "" {
				params["sort_dir"] = formatCLIParamValue(flagSortDir)
			}
			if flagAsOfDate != "" {
				params["as_of_date"] = formatCLIParamValue(flagAsOfDate)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "dashboards", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearch, "search", "", "Same as the stock dashboard; upper-cased by the app before sending.")
	cmd.Flags().StringVar(&flagItemGroup, "item-group", "", "Item group NAME.")
	cmd.Flags().StringVar(&flagWarehouse, "warehouse", "", "Comma-separated warehouse codes.")
	cmd.Flags().StringVar(&flagStatus, "status", "", "Comma-separated; critical | healthy | low | unset.")
	cmd.Flags().StringVar(&flagMovementStatus, "movement-status", "", "recent | slow.")
	cmd.Flags().StringVar(&flagSortBy, "sort-by", "", "string")
	cmd.Flags().StringVar(&flagSortDir, "sort-dir", "", "string")
	cmd.Flags().StringVar(&flagAsOfDate, "as-of-date", "", "YYYY-MM-DD. The app's export builder forwards as_of_date, so the same command can export a point-in-time sheet; the downloaded file is named stock_benchmark_<date>.xlsx.")

	return cmd
}
