// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDashboardsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dashboards",
		Short:       "Admin dashboards (stock, inventory-age, dispatch pipeline, SAP plan)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDashboardsInventoryAgeFilterOptionsCmd(flags))
	cmd.AddCommand(newDashboardsInventoryAgeReportCmd(flags))
	cmd.AddCommand(newDashboardsSalesPlanningRequirementAnalysisCmd(flags))
	cmd.AddCommand(newDashboardsSalesPlanningRequirementReportCmd(flags))
	cmd.AddCommand(newDashboardsSalesPlanningRequirementStatusCmd(flags))
	cmd.AddCommand(newDashboardsStockCmd(flags))
	cmd.AddCommand(newDashboardsStockAsOfCmd(flags))
	return cmd
}
