// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newDashboardsInventoryAgeReportCmd(flags *rootFlags) *cobra.Command {
	var flagItemGroup string
	var flagSearch string
	var flagMinAge int
	var flagWarehouse string
	var flagSubGroup string
	var flagVariety string

	cmd := &cobra.Command{
		Use:         "inventory-age-report",
		Short:       "Every item sitting in stock with how many days it has been there, its litres and its stock value",
		Example:     "  jivo-factory-pp-cli dashboards inventory-age-report",
		Annotations: map[string]string{"pp:endpoint": "dashboards.inventory-age-report", "pp:method": "GET", "pp:path": "/dashboards/inventory-age/report/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/dashboards/inventory-age/report/"
			params := map[string]string{}
			if flagItemGroup != "" {
				params["item_group"] = formatCLIParamValue(flagItemGroup)
			}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagMinAge != 0 {
				params["min_age"] = formatCLIParamValue(flagMinAge)
			}
			if flagWarehouse != "" {
				params["warehouse"] = formatCLIParamValue(flagWarehouse)
			}
			if flagSubGroup != "" {
				params["sub_group"] = formatCLIParamValue(flagSubGroup)
			}
			if flagVariety != "" {
				params["variety"] = formatCLIParamValue(flagVariety)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "dashboards", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagItemGroup, "item-group", "", "Item group NAME (e.g. 'PACKAGING MATERIAL'), not the numeric code. Verified: 1,445 of OIL's 2,418 rows.")
	cmd.Flags().StringVar(&flagSearch, "search", "", "Item code or name; upper-cased by the UI. Verified: search=TIN returned 132 rows on OIL.")
	cmd.Flags().IntVar(&flagMinAge, "min-age", 0, "INCLUSIVE lower bound — min_age=90 returned rows whose smallest days_age was exactly 90.")
	cmd.Flags().StringVar(&flagWarehouse, "warehouse", "", "SERVER-SIDE and working, though the UI filters this client-side.")
	cmd.Flags().StringVar(&flagSubGroup, "sub-group", "", "Single value; same last-wins behaviour. Verified: sub_group=TIN → 63 rows on OIL.")
	cmd.Flags().StringVar(&flagVariety, "variety", "", "Single value; same last-wins behaviour. Verified: variety=OLIVE → 95 rows, variety=POMACE → 138 on OIL.")

	return cmd
}
