// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDispatchCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dispatch",
		Short:       "Dispatch — docking, bilty-GRPO, transporter invoices",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDispatchBiltyGrpoHistoryCmd(flags))
	cmd.AddCommand(newDispatchBiltyGrpoOptionsCmd(flags))
	cmd.AddCommand(newDispatchBiltyGrpoPendingCmd(flags))
	cmd.AddCommand(newDispatchBiltyGrpoPreviewCmd(flags))
	cmd.AddCommand(newDispatchOpenBiltiesCmd(flags))
	cmd.AddCommand(newDispatchTransporterInvoicesHistoryCmd(flags))
	return cmd
}
