// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGateCoreEmptyVehicleOutsCmd(flags *rootFlags) *cobra.Command {
	var flagFromDate string
	var flagToDate string
	var flagEntryType string
	var flagAllCompanies string

	cmd := &cobra.Command{
		Use:         "empty-vehicle-outs",
		Short:       "Vehicles sent back out empty — the gate-out record for a truck that came in but did not load.",
		Example:     "  jivo-factory-pp-cli gate-core empty-vehicle-outs",
		Annotations: map[string]string{"pp:endpoint": "gate-core.empty-vehicle-outs", "pp:method": "GET", "pp:path": "/gate-core/empty-vehicle-outs/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/gate-core/empty-vehicle-outs/"
			params := map[string]string{}
			if flagFromDate != "" {
				params["from_date"] = formatCLIParamValue(flagFromDate)
			}
			if flagToDate != "" {
				params["to_date"] = formatCLIParamValue(flagToDate)
			}
			if flagEntryType != "" {
				params["entry_type"] = formatCLIParamValue(flagEntryType)
			}
			if flagAllCompanies != "" {
				params["all_companies"] = formatCLIParamValue(flagAllCompanies)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "gate-core", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagFromDate, "from-date", "", "YYYY-MM-DD")
	cmd.Flags().StringVar(&flagToDate, "to-date", "", "YYYY-MM-DD")
	cmd.Flags().StringVar(&flagEntryType, "entry-type", "", "observed values EMPTY_VEHICLE, SALES_DISPATCH")
	cmd.Flags().StringVar(&flagAllCompanies, "all-companies", "", "the UI sends String(all_companies); 1 works")

	return cmd
}
