// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGateCoreCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "gate-core",
		Short:       "Gate — arrivals, BST in/out/return, empty-vehicle, job-work, sales-dispatch gate-out",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGateCoreArrivalsCmd(flags))
	cmd.AddCommand(newGateCoreArrivalsExpectedCmd(flags))
	cmd.AddCommand(newGateCoreBstInsCmd(flags))
	cmd.AddCommand(newGateCoreBstInsEligibleOutsCmd(flags))
	cmd.AddCommand(newGateCoreBstOutsCmd(flags))
	cmd.AddCommand(newGateCoreBstOutsSapTransfersCmd(flags))
	cmd.AddCommand(newGateCoreBstReturnsCmd(flags))
	cmd.AddCommand(newGateCoreBstReturnsEligibleOutsCmd(flags))
	cmd.AddCommand(newGateCoreEmptyVehicleInsCmd(flags))
	cmd.AddCommand(newGateCoreEmptyVehicleInsEligibleCmd(flags))
	cmd.AddCommand(newGateCoreEmptyVehicleInsReasonsCmd(flags))
	cmd.AddCommand(newGateCoreEmptyVehicleOutsCmd(flags))
	cmd.AddCommand(newGateCoreEmptyVehicleOutsEligibleEntriesCmd(flags))
	cmd.AddCommand(newGateCoreJobWorkCmd(flags))
	cmd.AddCommand(newGateCoreJobWorkSapGrposCmd(flags))
	cmd.AddCommand(newGateCoreJobWorkSapProductionOrdersCmd(flags))
	cmd.AddCommand(newGateCoreRejectedQcReturnsCmd(flags))
	cmd.AddCommand(newGateCoreSalesDispatchCmd(flags))
	cmd.AddCommand(newGateCoreSalesDispatchDocumentsCmd(flags))
	cmd.AddCommand(newGateCoreSalesDispatchLockCmd(flags))
	cmd.AddCommand(newGateCoreSalesDispatchPendingBookingsCmd(flags))
	cmd.AddCommand(newGateCoreSalesDispatchReportsCmd(flags))
	return cmd
}
