// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGrpoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "grpo",
		Short:       "GRPO = 'Goods Receipt PO' — the step where material that has physically arrived at a JIVO plant gets booked into SAP as",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGrpoAllEntriesCmd(flags))
	cmd.AddCommand(newGrpoAttachmentsCmd(flags))
	cmd.AddCommand(newGrpoFgAllEntriesCmd(flags))
	cmd.AddCommand(newGrpoFgHistoryCmd(flags))
	cmd.AddCommand(newGrpoFgPendingCmd(flags))
	cmd.AddCommand(newGrpoFgSummaryCmd(flags))
	cmd.AddCommand(newGrpoHistoryCmd(flags))
	cmd.AddCommand(newGrpoHistoryDetailCmd(flags))
	cmd.AddCommand(newGrpoInspectionReportCmd(flags))
	cmd.AddCommand(newGrpoPendingCmd(flags))
	cmd.AddCommand(newGrpoPreviewCmd(flags))
	cmd.AddCommand(newGrpoServiceHistoryCmd(flags))
	cmd.AddCommand(newGrpoServiceHistoryDetailCmd(flags))
	cmd.AddCommand(newGrpoServiceOptionsCmd(flags))
	cmd.AddCommand(newGrpoServicePendingCmd(flags))
	cmd.AddCommand(newGrpoSummaryCmd(flags))
	return cmd
}
