// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newGrpoCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "grpo",
		Short:       "GRPO — goods-receipt POs (material & service)",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newGrpoAllEntriesCmd(flags))
	cmd.AddCommand(newGrpoHistoryCmd(flags))
	cmd.AddCommand(newGrpoHistoryDetailCmd(flags))
	cmd.AddCommand(newGrpoPendingCmd(flags))
	cmd.AddCommand(newGrpoPreviewCmd(flags))
	cmd.AddCommand(newGrpoServiceHistoryCmd(flags))
	cmd.AddCommand(newGrpoServiceHistoryDetailCmd(flags))
	cmd.AddCommand(newGrpoServiceOptionsCmd(flags))
	cmd.AddCommand(newGrpoServicePendingCmd(flags))
	cmd.AddCommand(newGrpoServicePreviewCmd(flags))
	cmd.AddCommand(newGrpoSummaryCmd(flags))
	return cmd
}
