// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newGrpoFgHistoryCmd(flags *rootFlags) *cobra.Command {
	var flagStatus string
	var flagSearch string
	var flagPage int
	var flagPageSize int

	cmd := &cobra.Command{
		Use:         "fg-history",
		Short:       "Log of finished-goods GRPO posting attempts to SAP — the finished-goods twin of the material posting log — currently holding no rows in any company.",
		Example:     "  jivo-factory-pp-cli grpo fg-history",
		Annotations: map[string]string{"pp:endpoint": "grpo.fg-history", "pp:method": "GET", "pp:path": "/grpo/fg/history/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/grpo/fg/history/"
			params := map[string]string{}
			if flagStatus != "" {
				params["status"] = formatCLIParamValue(flagStatus)
			}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagPage != 0 {
				params["page"] = formatCLIParamValue(flagPage)
			}
			if flagPageSize != 0 {
				params["page_size"] = formatCLIParamValue(flagPageSize)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "grpo", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagStatus, "status", "", "INFERRED, not exercised: DRAFT | PENDING | POSTED | FAILED | PARTIALLY_POSTED, the shared GRPO status constant used by /grpo/history/.")
	cmd.Flags().StringVar(&flagSearch, "search", "", "INFERRED, not exercised, by symmetry with /grpo/history/.")
	cmd.Flags().IntVar(&flagPage, "page", 0, "1-based; envelope carries page/total_pages/next/previous.")
	cmd.Flags().IntVar(&flagPageSize, "page-size", 0, "Server default 25 observed.")

	return cmd
}
