// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newMaintenanceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "maintenance",
		Short:       "Maintenance CMMS — assets, PM, spares, work orders",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newMaintenanceAlertsCmd(flags))
	cmd.AddCommand(newMaintenanceAssetCategoriesCmd(flags))
	cmd.AddCommand(newMaintenanceAssetDepartmentsCmd(flags))
	cmd.AddCommand(newMaintenanceAssetDocumentsCmd(flags))
	cmd.AddCommand(newMaintenanceAssetLocationsCmd(flags))
	cmd.AddCommand(newMaintenanceAssetPhotosCmd(flags))
	cmd.AddCommand(newMaintenanceAssetsCmd(flags))
	cmd.AddCommand(newMaintenanceDashboardCmd(flags))
	cmd.AddCommand(newMaintenanceOptionsCmd(flags))
	cmd.AddCommand(newMaintenancePmChecklistItemsCmd(flags))
	cmd.AddCommand(newMaintenancePmExecutionsCmd(flags))
	cmd.AddCommand(newMaintenancePmPlansCmd(flags))
	cmd.AddCommand(newMaintenanceReportsCmd(flags))
	cmd.AddCommand(newMaintenanceScanLookupCmd(flags))
	cmd.AddCommand(newMaintenanceSpareCategoriesCmd(flags))
	cmd.AddCommand(newMaintenanceSpareMovementsCmd(flags))
	cmd.AddCommand(newMaintenanceSpareRequestsCmd(flags))
	cmd.AddCommand(newMaintenanceSparesCmd(flags))
	cmd.AddCommand(newMaintenanceSparesLowStockCmd(flags))
	cmd.AddCommand(newMaintenanceSparesStockCmd(flags))
	cmd.AddCommand(newMaintenanceVendorVisitsCmd(flags))
	cmd.AddCommand(newMaintenanceWorkOrderPhotosCmd(flags))
	cmd.AddCommand(newMaintenanceWorkOrdersCmd(flags))
	return cmd
}
