// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMaintenanceWorkOrdersCmd(flags *rootFlags) *cobra.Command {
	var flagSearch string
	var flagStatus string
	var flagWorkType string
	var flagPriority string
	var flagDepartment int
	var flagLine string
	var flagIsActive bool

	cmd := &cobra.Command{
		Use:         "work-orders",
		Short:       "Maintenance work orders — complaints, breakdowns and jobs against an asset, with downtime",
		Example:     "  jivo-factory-pp-cli maintenance work-orders",
		Annotations: map[string]string{"pp:endpoint": "maintenance.work-orders", "pp:method": "GET", "pp:path": "/maintenance/work-orders/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/maintenance/work-orders/"
			params := map[string]string{}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagStatus != "" {
				params["status"] = formatCLIParamValue(flagStatus)
			}
			if flagWorkType != "" {
				params["work_type"] = formatCLIParamValue(flagWorkType)
			}
			if flagPriority != "" {
				params["priority"] = formatCLIParamValue(flagPriority)
			}
			if flagDepartment != 0 {
				params["department"] = formatCLIParamValue(flagDepartment)
			}
			if flagLine != "" {
				params["line"] = formatCLIParamValue(flagLine)
			}
			if flagIsActive != false {
				params["is_active"] = formatCLIParamValue(flagIsActive)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "maintenance", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearch, "search", "", "spans work_order_no, title, problem_statement AND the related asset name — verified: search=LIVE matched 4 of 5 rows")
	cmd.Flags().StringVar(&flagStatus, "status", "", "DRAFT | OPEN | ASSIGNED | IN_PROGRESS | WAITING_SPARE | WAITING_VENDOR | ON_HOLD | COMPLETED | APPROVED | CLOSED")
	cmd.Flags().StringVar(&flagWorkType, "work-type", "", "COMPLAINT | BREAKDOWN | GENERAL | PREVENTIVE | INSPECTION | CALIBRATION | AMC_VENDOR | PROJECT")
	cmd.Flags().StringVar(&flagPriority, "priority", "", "NORMAL | HIGH | CRITICAL")
	cmd.Flags().IntVar(&flagDepartment, "department", 0, "maintenance department id int")
	cmd.Flags().StringVar(&flagLine, "line", "", "")
	cmd.Flags().BoolVar(&flagIsActive, "is-active", false, "bool")

	return cmd
}
