// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMaintenanceMaintenanceFireItemsCmd(flags *rootFlags) *cobra.Command {
	var flagSearch string
	var flagCategory int
	var flagIsCritical bool
	var flagLowStock bool
	var flagIsActive bool

	cmd := &cobra.Command{
		Use:         "maintenance-fire-items",
		Short:       "Fire & safety store master — extinguishers, hydrants, PPE, jackets, boots — with stock",
		Example:     "  jivo-factory-pp-cli maintenance maintenance-fire-items",
		Annotations: map[string]string{"pp:endpoint": "maintenance.maintenance-fire-items", "pp:method": "GET", "pp:path": "/maintenance/fire/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/maintenance/fire/"
			params := map[string]string{}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagCategory != 0 {
				params["category"] = formatCLIParamValue(flagCategory)
			}
			if flagIsCritical != false {
				params["is_critical"] = formatCLIParamValue(flagIsCritical)
			}
			if flagLowStock != false {
				params["low_stock"] = formatCLIParamValue(flagLowStock)
			}
			if flagIsActive != false {
				params["is_active"] = formatCLIParamValue(flagIsActive)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "maintenance", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagSearch, "search", "", "verified: search=Jacket matched 1 of 7")
	cmd.Flags().IntVar(&flagCategory, "category", 0, "fire-category id — verified: category=3 -> 1 row int")
	cmd.Flags().BoolVar(&flagIsCritical, "is-critical", false, "verified bool")
	cmd.Flags().BoolVar(&flagLowStock, "low-stock", false, "verified: low_stock=true -> 2 rows, matching /maintenance/fire/low-stock/ bool")
	cmd.Flags().BoolVar(&flagIsActive, "is-active", false, "bool")

	return cmd
}
