// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newNonMovingRmCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "non-moving-rm",
		Short:       "This is the factory app's read-only reporting corner — the five 'management dashboard' screens the plant and purchase",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newNonMovingRmItemGroupsCmd(flags))
	cmd.AddCommand(newNonMovingRmReportCmd(flags))
	return cmd
}
