// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newOrderProcessingOrdersCmd(flags *rootFlags) *cobra.Command {
	var flagState string
	var flagIssue string
	var flagSearch string
	var flagPage int

	cmd := &cobra.Command{
		Use:         "orders",
		Short:       "The mirrored OMS sales orders — one row per order with customer, branch, delivery date, value, line count, how many of its lines are flagged, whether it was pushed to SAP, and where it sits in the stock-check pipeline. Read-only copy; the app itself says 'Mirrored from OMS. Read-only here.'",
		Example:     "  jivo-factory-pp-cli order-processing orders",
		Annotations: map[string]string{"pp:endpoint": "order-processing.orders", "pp:method": "GET", "pp:path": "/order-processing/orders/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/order-processing/orders/"
			params := map[string]string{}
			if flagState != "" {
				params["state"] = formatCLIParamValue(flagState)
			}
			if flagIssue != "" {
				params["issue"] = formatCLIParamValue(flagIssue)
			}
			if flagSearch != "" {
				params["search"] = formatCLIParamValue(flagSearch)
			}
			if flagPage != 0 {
				params["page"] = formatCLIParamValue(flagPage)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "order-processing", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagState, "state", "", "Pipeline state. Values the app offers: RECEIVED (mirrored, stock never checked), STOCK_CHECKED (checked, unresolved), PRODUCTION_REQUIRED (needs production), READY_FOR_FULFILLMENT (ready). The app's badge map also knows PARTIALLY_AVAILABLE and CANCELLED. Omit for all.")
	cmd.Flags().StringVar(&flagIssue, "issue", "", "Keep only orders carrying a flagged line. NO_WAREHOUSE is the only value wired to a button in the app; the flag vocabulary is shared with line-issues (NO_WAREHOUSE, QTY_DISAGREES, NO_ITEM_CODE, ZERO_QTY) but only NO_WAREHOUSE was observed at a call site.")
	cmd.Flags().StringVar(&flagSearch, "search", "", "Free text. The app's own placeholder is 'Order, customer or item code'.")
	cmd.Flags().IntVar(&flagPage, "page", 0, "1-based page number. 2281 orders at page_size 50 = 46 pages.")

	return cmd
}
