// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newVehicleManagementCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "vehicle-management",
		Short:       "Vehicle management — vehicles, transporters, entries, types",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newVehicleManagementTransportersCmd(flags))
	cmd.AddCommand(newVehicleManagementTransportersNamesCmd(flags))
	cmd.AddCommand(newVehicleManagementVehicleEntriesCmd(flags))
	cmd.AddCommand(newVehicleManagementVehicleEntriesCountCmd(flags))
	cmd.AddCommand(newVehicleManagementVehicleEntriesListByStatusCmd(flags))
	cmd.AddCommand(newVehicleManagementVehicleTypesCmd(flags))
	cmd.AddCommand(newVehicleManagementVehiclesCmd(flags))
	cmd.AddCommand(newVehicleManagementVehiclesNamesCmd(flags))
	return cmd
}
