// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newWarehouseCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "warehouse",
		Short:       "The warehouse module is the factory floor's stock-handling desk — its own landing page calls it 'Material requests",
		Hidden:      true,
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newWarehouseBomRequestGetCmd(flags))
	cmd.AddCommand(newWarehouseBomRequestsCmd(flags))
	cmd.AddCommand(newWarehouseBstGateInwardsCmd(flags))
	cmd.AddCommand(newWarehouseBstGateOutwardsCmd(flags))
	cmd.AddCommand(newWarehouseBstGetCmd(flags))
	cmd.AddCommand(newWarehouseBstIncomingCmd(flags))
	cmd.AddCommand(newWarehouseBstIncomingGetCmd(flags))
	cmd.AddCommand(newWarehouseBstListCmd(flags))
	cmd.AddCommand(newWarehouseBstPartialTransfersCmd(flags))
	cmd.AddCommand(newWarehouseBstSapTransferGetCmd(flags))
	cmd.AddCommand(newWarehouseBstSapTransfersCmd(flags))
	cmd.AddCommand(newWarehouseFgReceiptGetCmd(flags))
	cmd.AddCommand(newWarehouseFgReceiptsCmd(flags))
	cmd.AddCommand(newWarehouseWmsItemGroupsCmd(flags))
	cmd.AddCommand(newWarehouseWmsWarehousesCmd(flags))
	return cmd
}
