// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newAccountCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "account",
		Short:       "Authenticated account, users, roles, and reference master data (companies, states, categories, main groups)",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAccountCategoriesCmd(flags))
	cmd.AddCommand(newAccountCompaniesCmd(flags))
	cmd.AddCommand(newAccountMainGroupsCmd(flags))
	cmd.AddCommand(newAccountPartyProductsCmd(flags))
	cmd.AddCommand(newAccountProfileCmd(flags))
	cmd.AddCommand(newAccountRolesCmd(flags))
	cmd.AddCommand(newAccountStatesCmd(flags))
	cmd.AddCommand(newAccountUserPagePermissionsCmd(flags))
	cmd.AddCommand(newAccountUserPartiesCmd(flags))
	cmd.AddCommand(newAccountUsersCmd(flags))
	return cmd
}
