// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newDashboardCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "dashboard",
		Short:       "Order dashboard widgets and charts",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newDashboardChartsCmd(flags))
	cmd.AddCommand(newDashboardSummaryCmd(flags))
	return cmd
}
