// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newEinvoiceIrnByDocCmd(flags *rootFlags) *cobra.Command {
	var flagDoctype string
	var flagDocnum string
	var flagDocdate string

	cmd := &cobra.Command{
		Use:         "irn-by-doc",
		Short:       "Find the IRN for a document you know by type, number and date.",
		Long:        "The reverse lookup into `einvoice logs`. All three parameters are required together - omitting any returns {\"error\":\"Missing query params: doctype, docnum, docdate\"}.",
		Example:     "  oms-pp-cli einvoice irn-by-doc --doctype <doctype> --docnum <docnum> --docdate <docdate>",
		Annotations: map[string]string{"pp:endpoint": "einvoice.irn-by-doc", "pp:method": "GET", "pp:path": "/api/einvoice/irn/by-doc/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			// Bare invocation of a command with required input prints help
			// instead of pflag's terse "required flag not set" error. Optional-
			// only read commands fall through so a bare call still executes.
			if cmd.Flags().NFlag() == 0 && len(args) == 0 && !flags.dryRun {
				return cmd.Help()
			}
			if !cmd.Flags().Changed("doctype") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "doctype")
			}
			if !cmd.Flags().Changed("docnum") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "docnum")
			}
			if !cmd.Flags().Changed("docdate") && !flags.dryRun {
				return fmt.Errorf("required flag \"%s\" not set", "docdate")
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/einvoice/irn/by-doc/"
			params := map[string]string{}
			if flagDoctype != "" {
				params["doctype"] = formatCLIParamValue(flagDoctype)
			}
			if flagDocnum != "" {
				params["docnum"] = formatCLIParamValue(flagDocnum)
			}
			if flagDocdate != "" {
				params["docdate"] = formatCLIParamValue(flagDocdate)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "einvoice", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagDoctype, "doctype", "", "Document type as NIC names it")
	cmd.Flags().StringVar(&flagDocnum, "docnum", "", "Document number, e.g. 626088091")
	cmd.Flags().StringVar(&flagDocdate, "docdate", "", "Document date, DD/MM/YYYY - note the slashes, not the ISO form the rest of this API uses")

	return cmd
}
