// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newEinvoiceCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "einvoice",
		Short:       "Manage einvoice command groups",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newEinvoiceCompaniesCmd(flags))
	cmd.AddCommand(newEinvoiceHealthCmd(flags))
	cmd.AddCommand(newEinvoiceInvoicesCmd(flags))
	cmd.AddCommand(newEinvoiceLogsCmd(flags))
	return cmd
}
