// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newHanaCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "hana",
		Short:       "Live SAP HANA reads.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newHanaAddressCmd(flags))
	cmd.AddCommand(newHanaAllCustomersCmd(flags))
	cmd.AddCommand(newHanaBatchDetailsCmd(flags))
	cmd.AddCommand(newHanaCustomerDetailsCmd(flags))
	cmd.AddCommand(newHanaFgItemsCmd(flags))
	cmd.AddCommand(newHanaFreightMastersCmd(flags))
	cmd.AddCommand(newHanaInventoryDetailsCmd(flags))
	cmd.AddCommand(newHanaInventoryReportCmd(flags))
	cmd.AddCommand(newHanaInvoiceDraftsCmd(flags))
	cmd.AddCommand(newHanaItemPriceCmd(flags))
	cmd.AddCommand(newHanaNextDocNumberCmd(flags))
	cmd.AddCommand(newHanaOpenPartiesCmd(flags))
	cmd.AddCommand(newHanaPendingDispatchCmd(flags))
	cmd.AddCommand(newHanaProductSoCmd(flags))
	cmd.AddCommand(newHanaProductStockCmd(flags))
	cmd.AddCommand(newHanaSalespersonDetailsCmd(flags))
	cmd.AddCommand(newHanaSeriesCmd(flags))
	cmd.AddCommand(newHanaSoCmd(flags))
	cmd.AddCommand(newHanaStateChainCmd(flags))
	cmd.AddCommand(newHanaVendorStatesCmd(flags))
	cmd.AddCommand(newHanaWarehouseDetailsCmd(flags))
	return cmd
}
