// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newInvoicesUsedSalesOrdersCmd(flags *rootFlags) *cobra.Command {
	var flagBranch string
	var flagCardCode string

	cmd := &cobra.Command{
		Use:         "used-sales-orders",
		Short:       "Sales orders already consumed by an invoice posting run.",
		Long:        "so_number, log_id, status (POSTED_TO_SAP or ERROR), the sap_doc_num it became, and created_at. The audit trail for 'why can I not invoice this SO again'. TRAP: --card-code is DECORATIVE. The server echoes it back in the response and does not filter on it - the row set is byte-for-byte the same with and without it. --branch is the parameter that actually narrows.",
		Example:     "  oms-pp-cli invoices used-sales-orders",
		Annotations: map[string]string{"pp:endpoint": "invoices.used-sales-orders", "pp:method": "GET", "pp:path": "/api/invoice/used-sales-orders/", "mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if cmd.Flags().Changed("branch") {
				allowedBranch := []string{"OIL", "BEVERAGE"}
				validBranch := false
				for _, v := range allowedBranch {
					if flagBranch == v {
						validBranch = true
						break
					}
				}
				if !validBranch {
					return fmt.Errorf("invalid value %q for --%s: must be one of %v", flagBranch, "branch", allowedBranch)
				}
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/api/invoice/used-sales-orders/"
			params := map[string]string{}
			if flagBranch != "" {
				params["branch"] = formatCLIParamValue(flagBranch)
			}
			if flagCardCode != "" {
				params["card_code"] = formatCLIParamValue(flagCardCode)
			}
			data, prov, err := resolveReadWithStrategy(cmd.Context(), c, flags, "auto", "invoices", false, path, params, nil, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlags(cmd.OutOrStdout(), data, flags)
		},
	}
	cmd.Flags().StringVar(&flagBranch, "branch", "", "Company branch. The real filter (one of: OIL, BEVERAGE)")
	cmd.Flags().StringVar(&flagCardCode, "card-code", "", "Echoed back in the response and otherwise IGNORED - it does not filter. Sent by the UI; kept for parity")

	return cmd
}
