// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newInvoicesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "invoices",
		Short:       "The invoice review-and-approval queue, credit limits and SKU master data",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newInvoicesAllCmd(flags))
	cmd.AddCommand(newInvoicesCreditLimitCardsCmd(flags))
	cmd.AddCommand(newInvoicesCreditLimitFlowCmd(flags))
	cmd.AddCommand(newInvoicesCrystalCmd(flags))
	// Live verification (2026-07-19, re-verified 2026-08-04): the deployed OMS
	// backend has no /api/invoice/history/{id}/ route, so this command always
	// 404s. Unregistered until the backend team confirms the route.
	// cmd.AddCommand(newInvoicesHistoryCmd(flags))
	cmd.AddCommand(newInvoicesLogsCmd(flags))
	cmd.AddCommand(newInvoicesReservedBatchesCmd(flags))
	cmd.AddCommand(newInvoicesSkuCmd(flags))
	cmd.AddCommand(newInvoicesSkusCmd(flags))
	cmd.AddCommand(newInvoicesSkusPendingCmd(flags))
	cmd.AddCommand(newInvoicesUsedSalesOrdersCmd(flags))
	return cmd
}
