// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newLegalCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "legal",
		Short:       "FSSAI food-label compliance: pack artwork checked against the statutory declarations for an item",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newLegalItemNutritionCmd(flags))
	cmd.AddCommand(newLegalItemsCmd(flags))
	cmd.AddCommand(newLegalNutritionCmd(flags))
	cmd.AddCommand(newLegalUomsCmd(flags))
	return cmd
}
