// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newOrdersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "orders",
		Short:       "Orders: list, detail, status lifecycle, tracking, dispatch, approval-flow config",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newOrdersAddressesCmd(flags))
	cmd.AddCommand(newOrdersBranchCmd(flags))
	cmd.AddCommand(newOrdersByUserCmd(flags))
	cmd.AddCommand(newOrdersDetailCmd(flags))
	cmd.AddCommand(newOrdersDispatchesCmd(flags))
	cmd.AddCommand(newOrdersFlowConfigCmd(flags))
	cmd.AddCommand(newOrdersListCmd(flags))
	cmd.AddCommand(newOrdersLogsCmd(flags))
	cmd.AddCommand(newOrdersNotificationsCmd(flags))
	cmd.AddCommand(newOrdersPartiesCmd(flags))
	cmd.AddCommand(newOrdersPartyFlowConfigCmd(flags))
	cmd.AddCommand(newOrdersPartyProductsCmd(flags))
	cmd.AddCommand(newOrdersProductsCmd(flags))
	cmd.AddCommand(newOrdersSchemesCmd(flags))
	cmd.AddCommand(newOrdersStaffProductsCmd(flags))
	cmd.AddCommand(newOrdersStatusCmd(flags))
	cmd.AddCommand(newOrdersStatusTrackingCmd(flags))
	cmd.AddCommand(newOrdersStockCheckCmd(flags))
	return cmd
}
