// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newQuotationsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "quotations",
		Short:       "Sales quotations and their SAP push status",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newQuotationsOverviewCmd(flags))
	cmd.AddCommand(newQuotationsStatusCmd(flags))
	return cmd
}
