// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newSapCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "sap",
		Short:       "SAP Business One sync — history logs and synced master data (branches, parties, products)",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newSapAddressesCmd(flags))
	cmd.AddCommand(newSapBranchesCmd(flags))
	cmd.AddCommand(newSapLogsCmd(flags))
	cmd.AddCommand(newSapPartiesCmd(flags))
	cmd.AddCommand(newSapPartyCategoriesCmd(flags))
	cmd.AddCommand(newSapProductVarietiesCmd(flags))
	cmd.AddCommand(newSapProductsCmd(flags))
	cmd.AddCommand(newSapQuotationLogCmd(flags))
	return cmd
}
