// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newTrackerCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "tracker",
		Short:       "The OMS invoice tracker: invoices moving through stages, queues, vendors, alerts and reports.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newTrackerAdminLookupsCmd(flags))
	cmd.AddCommand(newTrackerAdminStagesCmd(flags))
	cmd.AddCommand(newTrackerAdminTrackerUsersCmd(flags))
	cmd.AddCommand(newTrackerAdminUsersCmd(flags))
	cmd.AddCommand(newTrackerAlertsCmd(flags))
	cmd.AddCommand(newTrackerAllInvoicesCmd(flags))
	cmd.AddCommand(newTrackerAllInvoicesExportCmd(flags))
	cmd.AddCommand(newTrackerInvoiceDetailCmd(flags))
	cmd.AddCommand(newTrackerInvoiceJsapCmd(flags))
	cmd.AddCommand(newTrackerInvoicesCmd(flags))
	cmd.AddCommand(newTrackerLookupsCmd(flags))
	cmd.AddCommand(newTrackerMyQueueCmd(flags))
	cmd.AddCommand(newTrackerReportsCmd(flags))
	cmd.AddCommand(newTrackerStageAdvancedCmd(flags))
	cmd.AddCommand(newTrackerVendorsCmd(flags))
	return cmd
}
