// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "account categories", Description: "List product categories (e.g. OIL)", Group: "account"},
	{Command: "account companies", Description: "List companies (Jivo Mart, Jivo Wellness)", Group: "account"},
	{Command: "account main-groups", Description: "List main groups (ROI, GT, MT, BRANCH, ...)", Group: "account"},
	{Command: "account party-products", Description: "Products assigned to a party (argument is the SAP card_code, not a numeric id)", Group: "account"},
	{Command: "account profile", Description: "Show the authenticated user (role, company, main groups, states, category, page permissions)", Group: "account"},
	{Command: "account roles", Description: "List roles (admin, auditor, billing, rate approver, manager, etc.)", Group: "account"},
	{Command: "account states", Description: "List states", Group: "account"},
	{Command: "account user-page-permissions", Description: "Page-permission grants for a user", Group: "account"},
	{Command: "account user-parties", Description: "Parties (customers) assigned to a user", Group: "account"},
	{Command: "account users", Description: "List app users", Group: "account"},
	{Command: "dashboard charts", Description: "Dashboard chart series (visual overview, statewise)", Group: "dashboard"},
	{Command: "dashboard summary", Description: "Dashboard KPI block (total orders, total sales, completion)", Group: "dashboard"},
	{Command: "hana address", Description: "Addresses for a customer. Requires --card-code.", Group: "hana"},
	{Command: "hana all-customers", Description: "All customers from SAP HANA", Group: "hana"},
	{Command: "hana batch-details", Description: "Batch details for an item in a warehouse. Requires --item-code and --whs-code.", Group: "hana"},
	{Command: "hana customer-details", Description: "Customer master detail. Requires --card-code.", Group: "hana"},
	{Command: "hana fg-items", Description: "Finished-goods items", Group: "hana"},
	{Command: "hana freight-masters", Description: "Freight master records", Group: "hana"},
	{Command: "hana inventory-details", Description: "Per-warehouse inventory for an item. Requires --item-code.", Group: "hana"},
	{Command: "hana item-price", Description: "Price for an item on a price list. Requires --item-code and --price-list.", Group: "hana"},
	{Command: "hana next-doc-number", Description: "Next document number for a document type. Requires --doc-type.", Group: "hana"},
	{Command: "hana open-parties", Description: "Parties with open transactions", Group: "hana"},
	{Command: "hana product-so", Description: "Product sales-order data", Group: "hana"},
	{Command: "hana product-stock", Description: "Live product stock from SAP HANA", Group: "hana"},
	{Command: "hana salesperson-details", Description: "Salesperson detail. Requires --slp-code.", Group: "hana"},
	{Command: "hana so", Description: "Sales orders", Group: "hana"},
	{Command: "invoices all", Description: "Invoice review queue (all invoices). Optionally filter by status.", Group: "invoices"},
	{Command: "invoices history", Description: "Status-history timeline for an invoice", Group: "invoices"},
	{Command: "invoices sku", Description: "Per-SKU detail", Group: "invoices"},
	{Command: "invoices skus", Description: "All SKUs", Group: "invoices"},
	{Command: "invoices skus-pending", Description: "SKUs pending review", Group: "invoices"},
	{Command: "orders addresses", Description: "Bill-to / ship-to addresses for a party. Requires --card-code.", Group: "orders"},
	{Command: "orders branch", Description: "SAP branch / BPL list", Group: "orders"},
	{Command: "orders by-user", Description: "Orders raised by a specific user (source for View Orders / Order Tracking)", Group: "orders"},
	{Command: "orders detail", Description: "Full order with line items, addresses, rate approvals, SAP doc number", Group: "orders"},
	{Command: "orders dispatches", Description: "Dispatch-from locations", Group: "orders"},
	{Command: "orders flow-config", Description: "Global order approval-flow configuration", Group: "orders"},
	{Command: "orders list", Description: "All orders (admin-wide). Filter by status/stage.", Group: "orders"},
	{Command: "orders logs", Description: "Status-change audit trail for an order (drives the tracking timeline)", Group: "orders"},
	{Command: "orders notifications", Description: "Order-status notifications for the current user", Group: "orders"},
	{Command: "orders parties", Description: "Assigned-party dropdown (card_code -> card_name) for the current user", Group: "orders"},
	{Command: "orders party-flow-config", Description: "Per-party approval-flow configuration", Group: "orders"},
	{Command: "orders party-products", Description: "Products (with rates) assigned to a party, for the order product selector", Group: "orders"},
	{Command: "orders products", Description: "Global product list", Group: "orders"},
	{Command: "orders schemes", Description: "Sales schemes / promotions", Group: "orders"},
	{Command: "orders staff-products", Description: "Staff-assigned products", Group: "orders"},
	{Command: "orders status", Description: "Order status master (id -> name)", Group: "orders"},
	{Command: "orders status-tracking", Description: "Approval queue for a stage. Requires --mode.", Group: "orders"},
	{Command: "orders stock-check", Description: "Per-order required-qty vs available-stock (legacy view)", Group: "orders"},
	{Command: "quotations overview", Description: "All quotations with SAP doc numbers and cancellation state", Group: "quotations"},
	{Command: "quotations status", Description: "Open/closed SAP status badges for specific quotations", Group: "quotations"},
	{Command: "sap addresses", Description: "SAP addresses", Group: "sap"},
	{Command: "sap branches", Description: "SAP branches", Group: "sap"},
	{Command: "sap logs", Description: "SAP sync history (sync_type, status, records processed/created/updated, duration)", Group: "sap"},
	{Command: "sap parties", Description: "SAP parties (business partners)", Group: "sap"},
	{Command: "sap party-categories", Description: "SAP parties filtered by category", Group: "sap"},
	{Command: "sap product-varieties", Description: "SAP product varieties", Group: "sap"},
	{Command: "sap products", Description: "SAP products", Group: "sap"},
	{Command: "sap quotation-log", Description: "Per-order SAP quotation push record", Group: "sap"},
	{Command: "tracker admin-lookups", Description: "Tracker admin: lookup set by type", Group: "tracker"},
	{Command: "tracker admin-stages", Description: "Tracker admin: stage definitions", Group: "tracker"},
	{Command: "tracker admin-tracker-users", Description: "Tracker admin: tracker-role users", Group: "tracker"},
	{Command: "tracker admin-users", Description: "Tracker admin: users", Group: "tracker"},
	{Command: "tracker alerts", Description: "Tracker alerts", Group: "tracker"},
	{Command: "tracker all-invoices", Description: "All tracker invoices", Group: "tracker"},
	{Command: "tracker all-invoices-export", Description: "Export of all tracker invoices", Group: "tracker"},
	{Command: "tracker invoice-detail", Description: "Single tracker invoice", Group: "tracker"},
	{Command: "tracker invoices", Description: "Tracker invoices", Group: "tracker"},
	{Command: "tracker lookups", Description: "Tracker lookup reference data", Group: "tracker"},
	{Command: "tracker my-queue", Description: "Current user's tracker work queue", Group: "tracker"},
	{Command: "tracker reports", Description: "Tracker reports", Group: "tracker"},
	{Command: "tracker stage-advanced", Description: "Advanced stage view", Group: "tracker"},
	{Command: "tracker vendors", Description: "Tracker vendors", Group: "tracker"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  oms-pp-cli which "stale tickets"
  oms-pp-cli which "bottleneck"
  oms-pp-cli which --limit 1 "send message"
  oms-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
