// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

// whichEntry is one row of the curated capability index. The index is
// seeded at generation time from the same NovelFeature list that drives
// the SKILL.md feature section, so the command a `which` query returns
// is guaranteed to exist and to match what the skill advertises.
type whichEntry struct {
	Command      string `json:"command"`
	Description  string `json:"description"`
	Group        string `json:"group,omitempty"`
	WhyItMatters string `json:"why_it_matters,omitempty"`
}

// whichIndex is the curated list of capabilities this CLI advertises as
// its hero features. Endpoint-level commands are discoverable via
// `--help`; `which` exists to resolve a natural-language capability
// query to one of the commands the skill says matter most.
var whichIndex = []whichEntry{
	{Command: "account categories", Description: "List product categories (e.g. OIL)", Group: "account"},
	{Command: "account companies", Description: "List companies (Jivo Mart, Jivo Wellness)", Group: "account"},
	{Command: "account device", Description: "Full record for one enrolled device — model, OS, app build, first and last login — for when you need to confirm exactly what a specific user was running.", Group: "account"},
	{Command: "account device-analytics", Description: "One-screen rollout health for the OMS apps — how many devices are on each Android/iOS/web build, and how many have been seen recently. Use it to answer \"has everyone updated?\" before blaming the backend.", Group: "account"},
	{Command: "account devices", Description: "The device registry — every browser and phone that has logged into OMS, who was on it, and when it was last seen. This is how you find out which app build a salesperson is actually running before you believe a bug report from the field.", Group: "account"},
	{Command: "account main-groups", Description: "List main groups (ROI, GT, MT, BRANCH, ...)", Group: "account"},
	{Command: "account my-devices", Description: "Push-notification devices registered to the calling user. Returns an empty list if you have never enrolled a browser or handset.", Group: "account"},
	{Command: "account party-products", Description: "Products assigned to a party (argument is the SAP card_code, not a numeric id)", Group: "account"},
	{Command: "account profile", Description: "Show the authenticated user (role, company, main groups, states, category, page permissions)", Group: "account"},
	{Command: "account roles", Description: "List roles (admin, auditor, billing, rate approver, manager, etc.)", Group: "account"},
	{Command: "account states", Description: "List states", Group: "account"},
	{Command: "account ui-label-config", Description: "The editable definitions behind OMS's renameable field labels — the admin view, with the description and the active flag.", Group: "account"},
	{Command: "account ui-labels", Description: "The resolved label map the app renders with — what the UI currently calls each renameable field. Useful when a user's screenshot says something your data dictionary doesn't.", Group: "account"},
	{Command: "account user-page-permissions", Description: "Page-permission grants for a user", Group: "account"},
	{Command: "account user-parties", Description: "Parties (customers) assigned to a user", Group: "account"},
	{Command: "account users", Description: "List app users", Group: "account"},
	{Command: "dashboard charts", Description: "Dashboard chart series (visual overview, statewise)", Group: "dashboard"},
	{Command: "dashboard summary", Description: "Dashboard KPI block (total orders, total sales, completion)", Group: "dashboard"},
	{Command: "einvoice companies", Description: "The JIVO legal entities enrolled for GST e-invoicing, with their GSTINs.", Group: "einvoice"},
	{Command: "einvoice health", Description: "Whether the GST e-invoicing integration is up and authenticated.", Group: "einvoice"},
	{Command: "einvoice invoices", Description: "Invoices that have been through GST e-invoicing, with their IRN status.", Group: "einvoice"},
	{Command: "einvoice logs", Description: "IRN generation attempts and their outcomes — the place to look when an e-invoice fails.", Group: "einvoice"},
	{Command: "hana address", Description: "Addresses for a customer. Requires --card-code.", Group: "hana"},
	{Command: "hana all-customers", Description: "All customers from SAP HANA", Group: "hana"},
	{Command: "hana batch-details", Description: "Batch details for an item in a warehouse. Requires --item-code and --whs-code.", Group: "hana"},
	{Command: "hana customer-details", Description: "Customer master detail. Requires --card-code.", Group: "hana"},
	{Command: "hana fg-items", Description: "Finished-goods items", Group: "hana"},
	{Command: "hana freight-masters", Description: "Freight master records", Group: "hana"},
	{Command: "hana inventory-details", Description: "Per-warehouse inventory for an item. Requires --item-code.", Group: "hana"},
	{Command: "hana invoice-drafts", Description: "READ of the A/R invoice drafts sitting in SAP for a branch. This reads drafts; it never creates one.", Group: "hana"},
	{Command: "hana item-price", Description: "Price for an item on a price list. Requires --item-code and --price-list.", Group: "hana"},
	{Command: "hana next-doc-number", Description: "Next document number for a document type. Requires --doc-type.", Group: "hana"},
	{Command: "hana open-parties", Description: "Parties with open transactions", Group: "hana"},
	{Command: "hana product-so", Description: "BROKEN UPSTREAM (2026-08-04): the OMS backend raises \"get_sales_orders_for_product() takes 1 positional argument but 2 were given\" and returns HTTP 500 on every call. Reported to the OMS team. | Product sales-order data for an item. Requires --item-code.", Group: "hana"},
	{Command: "hana product-stock", Description: "BROKEN UPSTREAM (2026-08-04): the OMS backend raises \"name 'unique_schemas' is not defined\" and returns HTTP 502 on every call, for both branches. Reported to the OMS team. | Live product stock from SAP HANA", Group: "hana"},
	{Command: "hana salesperson-details", Description: "Salesperson detail. Requires --slp-code.", Group: "hana"},
	{Command: "hana series", Description: "SAP document numbering series for a branch — the series a document will draw its number from.", Group: "hana"},
	{Command: "hana so", Description: "Sales orders for a party. Requires --card-code.", Group: "hana"},
	{Command: "hana state-chain", Description: "The state-to-state routing chain used for freight and GST place-of-supply decisions.", Group: "hana"},
	{Command: "hana vendor-states", Description: "States JIVO's vendors operate in, per branch — used to work out interstate vs intrastate GST.", Group: "hana"},
	{Command: "hana warehouse-details", Description: "Warehouse master for a branch: codes, names and locations behind every WhsCode you see in stock and batch data.", Group: "hana"},
	{Command: "invoices all", Description: "BROKEN UPSTREAM (2026-08-04): returns HTTP 400 \"Warehouse Code is a required parameter\" for every parameter name tried, and the OMS web app never calls this route. Use `invoices logs` instead. Reported to the OMS team. | Invoice review queue (all invoices). Optionally filter by status.", Group: "invoices"},
	{Command: "invoices credit-limit-cards", Description: "The credit-limit master for every customer account in one SAP company — how much each party currently owes, the credit line they are allowed, and the debt line. This is what the reviewer looks at before releasing an invoice for a party who is close to their limit.", Group: "invoices"},
	{Command: "invoices credit-limit-flow", Description: "The approval chain for a credit-limit override request raised against one invoice — which named approver sits at which stage, in what order, and whether they approved, rejected or have not acted.", Group: "invoices"},
	{Command: "invoices crystal", Description: "The Crystal Reports print payload for one posted invoice, by SAP document number.", Group: "invoices"},
	{Command: "invoices history", Description: "Status-history timeline for an invoice (BACKEND ROUTE MISSING — unregistered)", Group: "invoices"},
	{Command: "invoices logs", Description: "The invoice review-and-approval queue. One row per invoice a salesperson has submitted out of a sales order, carrying the full SAP B1 document payload, the finished-goods stock position at the time of submission, and where it currently sits between \"submitted\" and \"posted into SAP\".", Group: "invoices"},
	{Command: "invoices sku", Description: "Per-SKU detail", Group: "invoices"},
	{Command: "invoices skus", Description: "All SKUs", Group: "invoices"},
	{Command: "invoices skus-pending", Description: "BROKEN UPSTREAM (2026-08-04): the OMS backend raises \"getFGItems() missing 1 required positional argument: 'branch'\" and returns HTTP 500 on every call. Reported to the OMS team. | SKUs pending review", Group: "invoices"},
	{Command: "legal item-nutrition", Description: "The nutritional facts JIVO has declared for one product — the reference values an uploaded label is checked against.", Group: "legal"},
	{Command: "legal items", Description: "The food products whose pack labels are checked for FSSAI compliance. One row per product.", Group: "legal"},
	{Command: "legal nutrition", Description: "The master list of nutrition rows (the nutrient lines that can appear in a nutritional-information table).", Group: "legal"},
	{Command: "legal uoms", Description: "The units of measure used when declaring nutritional values on a label (g, kcal, mg …).", Group: "legal"},
	{Command: "orders addresses", Description: "Bill-to / ship-to addresses for a party. Requires --card-code.", Group: "orders"},
	{Command: "orders branch", Description: "SAP branch / BPL list", Group: "orders"},
	{Command: "orders by-item", Description: "Every order line for one FG item — who ordered it, how much, and in what state.", Group: "orders"},
	{Command: "orders by-user", Description: "Orders raised by a specific user (source for View Orders / Order Tracking)", Group: "orders"},
	{Command: "orders dashboard", Description: "Order dashboard headline counters. Note this is a DIFFERENT endpoint from the shipped `orders dashboardW`, which the web app uses; both are live.", Group: "orders"},
	{Command: "orders dashboard-charts", Description: "Chart series behind the order dashboard. Large — 268 KB in one unpaginated response; use --compact or --csv.", Group: "orders"},
	{Command: "orders detail", Description: "Full order with line items, addresses, rate approvals, SAP doc number", Group: "orders"},
	{Command: "orders dispatches", Description: "Dispatch-from locations", Group: "orders"},
	{Command: "orders flow-config", Description: "Global order approval-flow configuration", Group: "orders"},
	{Command: "orders list", Description: "All orders (admin-wide). Filter by status/stage. TRAPS: bare `orders list` is NOT the order book - it returns one slice (263 of 2,163 orders). `status` accepts a comma-separated list and unions them. `billing=true` DISCARDS any `status` you also pass (proven: six query strings, byte-identical bodies). `approval_pending=true` alone is a no-op.", Group: "orders"},
	{Command: "orders logs", Description: "Status-change audit trail for an order (drives the tracking timeline)", Group: "orders"},
	{Command: "orders notifications", Description: "Order-status notifications for the current user", Group: "orders"},
	{Command: "orders notifications-history", Description: "The full notification feed for the current user, paged — including alerts already read, which the live `orders notifications` call drops.", Group: "orders"},
	{Command: "orders parties", Description: "Assigned-party dropdown (card_code -> card_name) for the current user", Group: "orders"},
	{Command: "orders party-flow-config", Description: "Per-party approval-flow configuration", Group: "orders"},
	{Command: "orders party-products", Description: "Products (with rates) assigned to a party, for the order product selector", Group: "orders"},
	{Command: "orders product-filters", Description: "The filter options (brand, variety, pack size) offered by the order product selector.", Group: "orders"},
	{Command: "orders products", Description: "Global product list", Group: "orders"},
	{Command: "orders schemes", Description: "Sales schemes / promotions", Group: "orders"},
	{Command: "orders schemes-manage", Description: "The full scheme table behind the scheme admin screen — each scheme joined to the SKU it applies to, its pack size, its state, and whether it is switched on.", Group: "orders"},
	{Command: "orders staff-products", Description: "Staff-assigned products", Group: "orders"},
	{Command: "orders status", Description: "Order status master (id -> name)", Group: "orders"},
	{Command: "orders status-tracking", Description: "Approval queue for a stage. Requires --mode.", Group: "orders"},
	{Command: "orders stock-check", Description: "Per-order required-qty vs available-stock (legacy view)", Group: "orders"},
	{Command: "orders template-orders", Description: "Previous orders for one party, offered as templates for a new order.", Group: "orders"},
	{Command: "orders template-parties", Description: "Parties available as an order template — the 'repeat a previous order' picker. Empty for a user with no assigned parties.", Group: "orders"},
	{Command: "orders web-push-key", Description: "The VAPID public key the browser needs to register for OMS push notifications. Infrastructure, not business data.", Group: "orders"},
	{Command: "quotations overview", Description: "All quotations with SAP doc numbers and cancellation state The SAP doc numbers here are real: sampled (doc_num, doc_entry) pairs resolve exactly to SAP OQUT quotations. Note doc_num is NOT unique across companies - the same number exists in Oil and Beverages, so always pair it with the branch.", Group: "quotations"},
	{Command: "quotations status", Description: "Open/closed SAP status badges for specific quotations", Group: "quotations"},
	{Command: "sap addresses", Description: "SAP addresses", Group: "sap"},
	{Command: "sap branches", Description: "SAP branches", Group: "sap"},
	{Command: "sap logs", Description: "SAP sync history (sync_type, status, records processed/created/updated, duration)", Group: "sap"},
	{Command: "sap parties", Description: "SAP parties (business partners)", Group: "sap"},
	{Command: "sap party-categories", Description: "SAP parties filtered by category", Group: "sap"},
	{Command: "sap product-varieties", Description: "SAP product varieties", Group: "sap"},
	{Command: "sap products", Description: "SAP products", Group: "sap"},
	{Command: "sap quotation-log", Description: "Per-order SAP quotation push record", Group: "sap"},
	{Command: "sap schedules", Description: "Configured SAP sync schedules. Read-only view; the toggle that enables one is a write and is not wrapped.", Group: "sap"},
	{Command: "sap sync-status", Description: "Current state of the SAP mirror sync: what ran, when, and whether it finished.", Group: "sap"},
	{Command: "tracker admin-lookups", Description: "Tracker admin: lookup set by type", Group: "tracker"},
	{Command: "tracker admin-stages", Description: "Tracker admin: stage definitions", Group: "tracker"},
	{Command: "tracker admin-tracker-users", Description: "Tracker admin: tracker-role users", Group: "tracker"},
	{Command: "tracker admin-users", Description: "Tracker admin: users", Group: "tracker"},
	{Command: "tracker alerts", Description: "Tracker alerts", Group: "tracker"},
	{Command: "tracker all-invoices", Description: "All tracker invoices", Group: "tracker"},
	{Command: "tracker all-invoices-export", Description: "Export of all tracker invoices", Group: "tracker"},
	{Command: "tracker invoice-detail", Description: "Single tracker invoice", Group: "tracker"},
	{Command: "tracker invoice-jsap", Description: "Whether this tracker invoice has reached **JSAP** (JIVO's internal ops platform at `103.89.45.75:5001`, the system `jsap-cli` talks to) and what JSAP's approvers did with it — approved, rejected, or still sitting there. Answers \"the invoice is stuck at JSAP Approval, has JSAP actually seen it?\"", Group: "tracker"},
	{Command: "tracker invoices", Description: "Tracker invoices", Group: "tracker"},
	{Command: "tracker lookups", Description: "Tracker lookup reference data", Group: "tracker"},
	{Command: "tracker my-queue", Description: "Current user's tracker work queue", Group: "tracker"},
	{Command: "tracker reports", Description: "Tracker reports", Group: "tracker"},
	{Command: "tracker stage-advanced", Description: "Advanced stage view", Group: "tracker"},
	{Command: "tracker vendors", Description: "Tracker vendors", Group: "tracker"},
}

// whichMatch pairs an index entry with its ranking score for a query.
// Higher score means stronger match. The ranker is naive (exact token
// then substring then group tag) because 20-40 entries do not need
// semantic retrieval - a ranker upgrade is a future change that would
// not break this contract.
type whichMatch struct {
	Entry whichEntry `json:"entry"`
	Score int        `json:"score"`
}

// rankWhich returns up to `limit` best matches for `query` against the
// index, sorted by descending score. Score breakdown:
//
//	+3  exact token match on the command's leaf or full path
//	+2  substring match on the command (any part)
//	+2  substring match on the description
//	+1  group tag contains the query as a word
//
// Ties break on declaration order in the index. An empty query returns
// every entry at score 0 in declaration order - this is the "list all"
// behavior the skill documents for broad agent discovery.
func rankWhich(index []whichEntry, query string, limit int) []whichMatch {
	if limit <= 0 {
		limit = 3
	}
	q := strings.ToLower(strings.TrimSpace(query))
	if q == "" {
		out := make([]whichMatch, 0, len(index))
		for _, e := range index {
			out = append(out, whichMatch{Entry: e, Score: 0})
		}
		return out
	}
	qTokens := strings.Fields(q)

	scored := make([]whichMatch, 0, len(index))
	for i, e := range index {
		score := whichScoreEntry(e, q, qTokens)
		scored = append(scored, whichMatch{Entry: e, Score: score})
		_ = i
	}

	sort.SliceStable(scored, func(i, j int) bool {
		return scored[i].Score > scored[j].Score
	})
	// Drop zero-score matches when the query was non-empty; agents
	// branching on exit code rely on "no match" meaning no confidence.
	filtered := scored[:0]
	for _, m := range scored {
		if m.Score > 0 {
			filtered = append(filtered, m)
		}
	}
	if len(filtered) > limit {
		filtered = filtered[:limit]
	}
	return filtered
}

func whichScoreEntry(e whichEntry, query string, qTokens []string) int {
	score := 0
	cmd := strings.ToLower(e.Command)
	cmdTokens := strings.Fields(cmd)
	desc := strings.ToLower(e.Description)
	group := strings.ToLower(e.Group)

	// Exact token match on the command path (any token).
	for _, qt := range qTokens {
		for _, ct := range cmdTokens {
			if qt == ct {
				score += 3
				break
			}
		}
	}
	// Substring match on the full command (covers hyphenated leaves).
	if strings.Contains(cmd, query) {
		score += 2
	}
	// Substring match on the description.
	if strings.Contains(desc, query) {
		score += 2
	}
	// Group tag match.
	if group != "" {
		for _, qt := range qTokens {
			if strings.Contains(group, qt) {
				score += 1
				break
			}
		}
	}
	return score
}

func newWhichCmd(flags *rootFlags) *cobra.Command {
	var limit int
	cmd := &cobra.Command{
		Use:   "which [query]",
		Short: "Find the command that implements a capability",
		Annotations: map[string]string{
			"mcp:read-only":       "true",
			"pp:typed-exit-codes": "0,2",
		},
		Long: `which resolves a natural-language capability query (for example, "search messages" or "stale tickets") to the best matching command from this CLI's curated feature index.

Exit codes:
  0  at least one match found
  2  no confident match - the query did not score against any indexed capability; fall back to '--help' or 'search' if this CLI has one`,
		Example: `  oms-pp-cli which "stale tickets"
  oms-pp-cli which "bottleneck"
  oms-pp-cli which --limit 1 "send message"
  oms-pp-cli which                                # list the full capability index`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(whichIndex) == 0 {
				return usageErr(fmt.Errorf("this CLI has no curated capability index; run '--help' to see every command"))
			}
			query := strings.Join(args, " ")
			matches := rankWhich(whichIndex, query, limit)

			// Empty query returns the whole index at score 0 (listing mode).
			if strings.TrimSpace(query) == "" {
				return renderWhich(cmd, flags, rankWhichAll(whichIndex))
			}

			if len(matches) == 0 {
				// Under --json, return an empty matches envelope at exit 0
				// so agents can branch on `matches.length == 0` instead of
				// parsing a usage error message. Non-JSON keeps the typed
				// exit-2 path so terminal users see the help hint.
				if flags.asJSON {
					return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"matches": []whichMatch{},
					}, flags)
				}
				return usageErr(fmt.Errorf("no match for %q; try '%s --help' for the full command list", query, cmd.Root().Name()))
			}
			return renderWhich(cmd, flags, matches)
		},
	}
	cmd.Flags().IntVar(&limit, "limit", 3, "Maximum number of matches to return")
	return cmd
}

// rankWhichAll is a narrow helper used by the "empty query lists the
// index" path. It returns every entry in declaration order at score 0
// so the render path treats them uniformly.
func rankWhichAll(index []whichEntry) []whichMatch {
	out := make([]whichMatch, 0, len(index))
	for _, e := range index {
		out = append(out, whichMatch{Entry: e, Score: 0})
	}
	return out
}

func renderWhich(cmd *cobra.Command, flags *rootFlags, matches []whichMatch) error {
	w := cmd.OutOrStdout()
	// Output shape follows the same rule as every other generated
	// command: JSON when the caller asked for it OR when stdout is not
	// a terminal; table when a human is looking.
	asJSON := flags.asJSON
	if !asJSON && !isTerminal(w) {
		asJSON = true
	}
	if asJSON {
		// JSON envelope: {matches: [...]}. The wrap is critical:
		// printJSONFiltered's --compact path uses compactListFields
		// (allowlist) for top-level arrays, which would strip
		// entry/score keys; routing through compactObjectFields
		// (blocklist) via an object envelope preserves them.
		if matches == nil {
			matches = []whichMatch{}
		}
		return printJSONFiltered(w, map[string]any{"matches": matches}, flags)
	}
	fmt.Fprintf(w, "%-24s  %-8s  %s\n", "COMMAND", "SCORE", "DESCRIPTION")
	for _, m := range matches {
		fmt.Fprintf(w, "%-24s  %-8d  %s\n", m.Entry.Command, m.Score, m.Entry.Description)
	}
	return nil
}
