// Copyright 2026 daman8271 and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

// Package mcp — code-orchestration thin surface.
//
// Two tools cover the entire API: <api>_search to discover endpoints, and
// <api>_execute to invoke one. This collapses a large API (50+ endpoints)
// to ~1K tokens of tool definitions while preserving full coverage — the
// agent writes the composition logic in its own sandbox.
//
// Pattern source: Anthropic 2026-04-22 "Building agents that reach
// production systems with MCP" — Cloudflare's MCP server covers ~2,500
// endpoints in roughly 1K tokens via the same search+execute shape.

package mcp

import (
	"context"
	"encoding/json"
	"fmt"
	neturl "net/url"
	"sort"
	"strings"

	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

// RegisterCodeOrchestrationTools registers the two agent-facing tools that
// cover the whole API surface. Called from RegisterTools in place of the
// per-endpoint registrations when MCP.Orchestration is "code".
func RegisterCodeOrchestrationTools(s *server.MCPServer) {
	s.AddTool(
		mcplib.NewTool("jivo-ecom_search",
			mcplib.WithDescription("Search the jivo-ecom API for endpoints matching a natural-language query. Returns a ranked list of {endpoint_id, method, path, summary} entries. Call this first to find the endpoint to execute."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Natural-language description of what you want to do.")),
			mcplib.WithNumber("limit", mcplib.Description("Max endpoints to return (default 10).")),
		),
		handleCodeOrchSearch,
	)

	s.AddTool(
		mcplib.NewTool("jivo-ecom_execute",
			mcplib.WithDescription("Execute one jivo-ecom API endpoint by its endpoint_id (from jivo-ecom_search). Params are passed as a JSON object; path placeholders and query strings are resolved automatically."),
			mcplib.WithString("endpoint_id", mcplib.Required(), mcplib.Description("Endpoint identifier returned by jivo-ecom_search (e.g., \"users.list\").")),
			mcplib.WithObject("params", mcplib.Description("Parameters for the endpoint. Path placeholders match by name; remaining entries become query string on GET/DELETE or JSON body on POST/PUT/PATCH.")),
		),
		handleCodeOrchExecute,
	)
}

// codeOrchEndpoint captures the small slice of endpoint metadata the
// search+execute pair needs at runtime. `keywords` is a precomputed
// lowercase stream of description + path tokens used for naive ranking;
// anything more sophisticated belongs on the agent side.
type codeOrchEndpoint struct {
	ID         string
	Method     string
	Path       string
	Tier       string
	Summary    string
	Positional []string
	// TemplateParams carries public-to-wire bindings for promoted global path
	// placeholders. These resolve through Config.TemplateVars just like the
	// per-endpoint MCP tool inputs do.
	TemplateParams []codeOrchParamBinding
	// QueryParams carries public-to-wire bindings for spec-declared in:query
	// parameters. Write methods (POST/PUT/PATCH) route these to the query
	// string instead of dumping them into the JSON body. Derived from the
	// same mcpParamBindings location data the per-endpoint tools use.
	QueryParams []codeOrchParamBinding
	// HeaderOverrides carries per-endpoint request headers (e.g. an
	// Accept override for binary-only response endpoints). Without
	// threading these through, the code-orchestration execute path
	// sends the client's default Accept and binary endpoints 406.
	HeaderOverrides map[string]string
	// BodyIsArray marks endpoints whose request body schema root is a
	// bare top-level JSON array. The execute path then sends a top-level
	// array (the agent supplies it as params["body"]) instead of the
	// params object; a strict-mapping API rejects an object at the body
	// root with HTTP 422 "Invalid json".
	BodyIsArray bool
	keywords    []string
}

type codeOrchParamBinding struct {
	PublicName string
	WireName   string
}

// codeOrchEndpoints is the generator-populated registry covering every
// endpoint declared in the spec. Kept flat on purpose — the agent queries
// via <api>_search, so hierarchy shows up as dotted IDs, not nested maps.
var codeOrchEndpoints = []codeOrchEndpoint{
	{
		ID:             "account.me",
		Method:         "GET",
		Path:           "/api/auth/me",
		Summary:        "Show the authenticated user (profile, groups, platforms, permissions)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("account", "me", "Show the authenticated user (profile, groups, platforms, permissions)", "/api/auth/me"),
	},
	{
		ID:             "account.permissions",
		Method:         "GET",
		Path:           "/api/auth/permissions",
		Summary:        "List the permission modules granted to the current user",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("account", "permissions", "List the permission modules granted to the current user", "/api/auth/permissions"),
	},
	{
		ID:             "chatbot.conversation",
		Method:         "GET",
		Path:           "/api/chatbot/conversations/{id}",
		Summary:        "Get a chatbot conversation (with messages) by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("chatbot", "conversation", "Get a chatbot conversation (with messages) by id", "/api/chatbot/conversations/{id}"),
	},
	{
		ID:             "chatbot.conversations",
		Method:         "GET",
		Path:           "/api/chatbot/conversations",
		Summary:        "List chatbot conversations",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("chatbot", "conversations", "List chatbot conversations", "/api/chatbot/conversations"),
	},
	{
		ID:             "chatbot.health",
		Method:         "GET",
		Path:           "/api/chatbot/health",
		Summary:        "Chatbot service health",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("chatbot", "health", "Chatbot service health", "/api/chatbot/health"),
	},
	{
		ID:             "dashboard.category-breakdown",
		Method:         "GET",
		Path:           "/api/dashboard/category-breakdown",
		Summary:        "Premium vs commodity category breakdown",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "category-breakdown", "Premium vs commodity category breakdown", "/api/dashboard/category-breakdown"),
	},
	{
		ID:             "dashboard.category-litres",
		Method:         "GET",
		Path:           "/api/dashboard/category-litres",
		Summary:        "Category sales measured in litres",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "category-litres", "Category sales measured in litres", "/api/dashboard/category-litres"),
	},
	{
		ID:             "dashboard.category-platform-breakdown",
		Method:         "GET",
		Path:           "/api/dashboard/category-platform-breakdown",
		Summary:        "Category breakdown split by platform",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "category-platform-breakdown", "Category breakdown split by platform", "/api/dashboard/category-platform-breakdown"),
	},
	{
		ID:             "dashboard.category-sku-breakdown",
		Method:         "GET",
		Path:           "/api/dashboard/category-sku-breakdown",
		Summary:        "SKU-level breakdown within a category (requires --platform)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "category-sku-breakdown", "SKU-level breakdown within a category (requires --platform)", "/api/dashboard/category-sku-breakdown"),
	},
	{
		ID:             "dashboard.category-trend",
		Method:         "GET",
		Path:           "/api/dashboard/category-trend",
		Summary:        "Category sales trend over time",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}},
		keywords:       codeOrchKeywords("dashboard", "category-trend", "Category sales trend over time", "/api/dashboard/category-trend"),
	},
	{
		ID:             "dashboard.expiry-alerts",
		Method:         "GET",
		Path:           "/api/dashboard/expiry-alerts/{platform}",
		Summary:        "Expiry alerts for a single platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dashboard", "expiry-alerts", "Expiry alerts for a single platform", "/api/dashboard/expiry-alerts/{platform}"),
	},
	{
		ID:             "dashboard.expiry-alerts-po-items",
		Method:         "GET",
		Path:           "/api/dashboard/platform-expiry-alerts/{platform}/pos/{po}/items",
		Summary:        "Line items for a PO behind an expiry alert",
		Positional:     []string{"platform", "po"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dashboard", "expiry-alerts-po-items", "Line items for a PO behind an expiry alert", "/api/dashboard/platform-expiry-alerts/{platform}/pos/{po}/items"),
	},
	{
		ID:             "dashboard.expiry-alerts-pos",
		Method:         "GET",
		Path:           "/api/dashboard/platform-expiry-alerts/{platform}/pos",
		Summary:        "Purchase orders behind a platform expiry alert",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "expiry-alerts-pos", "Purchase orders behind a platform expiry alert", "/api/dashboard/platform-expiry-alerts/{platform}/pos"),
	},
	{
		ID:             "dashboard.fulfilment-health",
		Method:         "GET",
		Path:           "/api/dashboard/fulfilment-health",
		Summary:        "Fulfilment health summary by platform",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "window", WireName: "window"}},
		keywords:       codeOrchKeywords("dashboard", "fulfilment-health", "Fulfilment health summary by platform", "/api/dashboard/fulfilment-health"),
	},
	{
		ID:             "dashboard.inventory-charts",
		Method:         "GET",
		Path:           "/api/dashboard/inventory-charts",
		Summary:        "Inventory chart series",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}},
		keywords:       codeOrchKeywords("dashboard", "inventory-charts", "Inventory chart series", "/api/dashboard/inventory-charts"),
	},
	{
		ID:             "dashboard.latest-month",
		Method:         "GET",
		Path:           "/api/dashboard/latest-month",
		Summary:        "Latest data month/year available, with source metadata",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dashboard", "latest-month", "Latest data month/year available, with source metadata", "/api/dashboard/latest-month"),
	},
	{
		ID:             "dashboard.lead-time-report",
		Method:         "GET",
		Path:           "/api/dashboard/lead-time-report",
		Summary:        "Distributor lead-time report (rows, slabs, grand total)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dashboard", "lead-time-report", "Distributor lead-time report (rows, slabs, grand total)", "/api/dashboard/lead-time-report"),
	},
	{
		ID:             "dashboard.platform-expiry-alerts",
		Method:         "GET",
		Path:           "/api/dashboard/platform-expiry-alerts",
		Summary:        "Expiry alerts aggregated across platforms",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("dashboard", "platform-expiry-alerts", "Expiry alerts aggregated across platforms", "/api/dashboard/platform-expiry-alerts"),
	},
	{
		ID:             "dashboard.primary-po-litres",
		Method:         "GET",
		Path:           "/api/dashboard/primary-po-litres",
		Summary:        "Primary purchase-order volume in litres",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "primary-po-litres", "Primary purchase-order volume in litres", "/api/dashboard/primary-po-litres"),
	},
	{
		ID:             "dashboard.realise-breakdown",
		Method:         "GET",
		Path:           "/api/dashboard/realise-breakdown",
		Summary:        "Realise dashboard: breakdown (net realisation analytics)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "source", WireName: "source"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "realise-breakdown", "Realise dashboard: breakdown (net realisation analytics)", "/api/dashboard/realise-breakdown"),
	},
	{
		ID:             "dashboard.realise-overview",
		Method:         "GET",
		Path:           "/api/dashboard/realise-overview",
		Summary:        "Realise dashboard: overview (net realisation analytics)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "source", WireName: "source"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "realise-overview", "Realise dashboard: overview (net realisation analytics)", "/api/dashboard/realise-overview"),
	},
	{
		ID:             "dashboard.realise-trend",
		Method:         "GET",
		Path:           "/api/dashboard/realise-trend",
		Summary:        "Realise dashboard: trend (net realisation analytics)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "source", WireName: "source"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "realise-trend", "Realise dashboard: trend (net realisation analytics)", "/api/dashboard/realise-trend"),
	},
	{
		ID:             "dashboard.realise-waterfall",
		Method:         "GET",
		Path:           "/api/dashboard/realise-waterfall",
		Summary:        "Realise dashboard: waterfall (net realisation analytics)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "source", WireName: "source"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "realise-waterfall", "Realise dashboard: waterfall (net realisation analytics)", "/api/dashboard/realise-waterfall"),
	},
	{
		ID:             "dashboard.secondary-yoy-growth",
		Method:         "GET",
		Path:           "/api/dashboard/secondary-yoy-growth",
		Summary:        "Secondary sales year-over-year growth",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}},
		keywords:       codeOrchKeywords("dashboard", "secondary-yoy-growth", "Secondary sales year-over-year growth", "/api/dashboard/secondary-yoy-growth"),
	},
	{
		ID:             "dashboard.state-sales",
		Method:         "GET",
		Path:           "/api/dashboard/state-sales",
		Summary:        "State-wise sales with mapped/unmapped coverage",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "metric", WireName: "metric"}, {PublicName: "mode", WireName: "mode"}, {PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "state-sales", "State-wise sales with mapped/unmapped coverage", "/api/dashboard/state-sales"),
	},
	{
		ID:             "dashboard.state-sales-detail",
		Method:         "GET",
		Path:           "/api/dashboard/state-sales/detail",
		Summary:        "Detailed state-wise sales rows",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "state-sales-detail", "Detailed state-wise sales rows", "/api/dashboard/state-sales/detail"),
	},
	{
		ID:             "dashboard.state-sales-detail-cities",
		Method:         "GET",
		Path:           "/api/dashboard/state-sales/detail/cities",
		Summary:        "State-sales detail drilled to cities",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "state", WireName: "state"}, {PublicName: "metric", WireName: "metric"}, {PublicName: "dimension", WireName: "dimension"}, {PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "state-sales-detail-cities", "State-sales detail drilled to cities", "/api/dashboard/state-sales/detail/cities"),
	},
	{
		ID:             "dashboard.state-sales-detail-city-skus",
		Method:         "GET",
		Path:           "/api/dashboard/state-sales/detail/city-skus",
		Summary:        "State-sales detail drilled to city SKUs",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "state", WireName: "state"}, {PublicName: "city", WireName: "city"}, {PublicName: "metric", WireName: "metric"}, {PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "state-sales-detail-city-skus", "State-sales detail drilled to city SKUs", "/api/dashboard/state-sales/detail/city-skus"),
	},
	{
		ID:             "dashboard.state-sales-detail-options",
		Method:         "GET",
		Path:           "/api/dashboard/state-sales/detail/options",
		Summary:        "Filter options (skus, cities) for state-sales detail",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "state", WireName: "state"}},
		keywords:       codeOrchKeywords("dashboard", "state-sales-detail-options", "Filter options (skus, cities) for state-sales detail", "/api/dashboard/state-sales/detail/options"),
	},
	{
		ID:             "dashboard.state-sales-export",
		Method:         "GET",
		Path:           "/api/dashboard/state-sales/export",
		Summary:        "Export state-wise sales (file/CSV payload)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "state-sales-export", "Export state-wise sales (file/CSV payload)", "/api/dashboard/state-sales/export"),
	},
	{
		ID:             "dashboard.top-skus",
		Method:         "GET",
		Path:           "/api/dashboard/top-skus",
		Summary:        "Top-selling SKUs with top risers and fallers",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "platform", WireName: "platform"}, {PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("dashboard", "top-skus", "Top-selling SKUs with top risers and fallers", "/api/dashboard/top-skus"),
	},
	{
		ID:             "master.fcs",
		Method:         "GET",
		Path:           "/api/master/fcs",
		Summary:        "List fulfilment centres (paginated)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("master", "fcs", "List fulfilment centres (paginated)", "/api/master/fcs"),
	},
	{
		ID:             "master.products",
		Method:         "GET",
		Path:           "/api/master/products",
		Summary:        "List master products (paginated)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}, {PublicName: "search", WireName: "search"}},
		keywords:       codeOrchKeywords("master", "products", "List master products (paginated)", "/api/master/products"),
	},
	{
		ID:             "notifications.get",
		Method:         "GET",
		Path:           "/api/notifications/{id}",
		Summary:        "Get a single notification by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notifications", "get", "Get a single notification by id", "/api/notifications/{id}"),
	},
	{
		ID:             "notifications.inventory-doh",
		Method:         "GET",
		Path:           "/api/notifications/inventory-doh/{id}",
		Summary:        "Inventory days-of-health detail for a notification id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notifications", "inventory-doh", "Inventory days-of-health detail for a notification id", "/api/notifications/inventory-doh/{id}"),
	},
	{
		ID:             "notifications.list",
		Method:         "GET",
		Path:           "/api/notifications",
		Summary:        "List notifications with unread count",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("notifications", "list", "List notifications with unread count", "/api/notifications"),
	},
	{
		ID:             "platform.ads",
		Method:         "GET",
		Path:           "/api/platform/{platform}/ads-dashboard",
		Summary:        "Advertising performance dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "ads", "Advertising performance dashboard for a platform", "/api/platform/{platform}/ads-dashboard"),
	},
	{
		ID:             "platform.ads-summary",
		Method:         "GET",
		Path:           "/api/platform/ads-summary",
		Summary:        "Cross-platform advertising summary",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "ads-summary", "Cross-platform advertising summary", "/api/platform/ads-summary"),
	},
	{
		ID:             "platform.ads-total-sales",
		Method:         "GET",
		Path:           "/api/platform/{platform}/ads-total-sales",
		Summary:        "Ads total-sales for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "ads-total-sales", "Ads total-sales for a platform", "/api/platform/{platform}/ads-total-sales"),
	},
	{
		ID:             "platform.bigbasket-ads-daily-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/bigbasket-ads-daily-dashboard",
		Summary:        "Bigbasket Ads Daily Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "bigbasket-ads-daily-dashboard", "Bigbasket Ads Daily Dashboard for a platform", "/api/platform/{platform}/bigbasket-ads-daily-dashboard"),
	},
	{
		ID:             "platform.bigbasket-ads-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/bigbasket-ads-dashboard",
		Summary:        "Bigbasket Ads Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "bigbasket-ads-dashboard", "Bigbasket Ads Dashboard for a platform", "/api/platform/{platform}/bigbasket-ads-dashboard"),
	},
	{
		ID:             "platform.blinkit-ads-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/blinkit-ads-dashboard",
		Summary:        "Blinkit Ads Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "blinkit-ads-dashboard", "Blinkit Ads Dashboard for a platform", "/api/platform/{platform}/blinkit-ads-dashboard"),
	},
	{
		ID:             "platform.blinkit-brandfund-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/blinkit-brandfund-dashboard",
		Summary:        "Blinkit Brandfund Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "blinkit-brandfund-dashboard", "Blinkit Brandfund Dashboard for a platform", "/api/platform/{platform}/blinkit-brandfund-dashboard"),
	},
	{
		ID:             "platform.call-center-targets",
		Method:         "GET",
		Path:           "/api/platform/call-center-targets",
		Summary:        "Call-center secondary targets (premium/commodity)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("platform", "call-center-targets", "Call-center secondary targets (premium/commodity)", "/api/platform/call-center-targets"),
	},
	{
		ID:             "platform.comparison",
		Method:         "GET",
		Path:           "/api/platform/{platform}/comparison-dashboard",
		Summary:        "Comparison dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "comparison", "Comparison dashboard for a platform", "/api/platform/{platform}/comparison-dashboard"),
	},
	{
		ID:             "platform.coupon",
		Method:         "GET",
		Path:           "/api/platform/{platform}/coupon-dashboard",
		Summary:        "Coupon performance dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "coupon", "Coupon performance dashboard for a platform", "/api/platform/{platform}/coupon-dashboard"),
	},
	{
		ID:             "platform.drr",
		Method:         "GET",
		Path:           "/api/platform/{platform}/drr-dashboard",
		Summary:        "Daily run-rate (DRR) dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "drr", "Daily run-rate (DRR) dashboard for a platform", "/api/platform/{platform}/drr-dashboard"),
	},
	{
		ID:             "platform.flipkart-ads-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/flipkart-ads-dashboard",
		Summary:        "Flipkart Ads Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "flipkart-ads-dashboard", "Flipkart Ads Dashboard for a platform", "/api/platform/{platform}/flipkart-ads-dashboard"),
	},
	{
		ID:             "platform.flipkart-fsn-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/flipkart-fsn-dashboard",
		Summary:        "Flipkart Fsn Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "flipkart-fsn-dashboard", "Flipkart Fsn Dashboard for a platform", "/api/platform/{platform}/flipkart-fsn-dashboard"),
	},
	{
		ID:             "platform.inventory-match",
		Method:         "GET",
		Path:           "/api/platform/{platform}/inventory-match",
		Summary:        "Inventory reconciliation/match for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "inventory-match", "Inventory reconciliation/match for a platform", "/api/platform/{platform}/inventory-match"),
	},
	{
		ID:             "platform.landing-rate",
		Method:         "GET",
		Path:           "/api/platform/{platform}/landing-rate",
		Summary:        "Monthly landing rate (blinkit/zepto/swiggy/bigbasket/flipkart_grocery only)",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("platform", "landing-rate", "Monthly landing rate (blinkit/zepto/swiggy/bigbasket/flipkart_grocery only)", "/api/platform/{platform}/landing-rate"),
	},
	{
		ID:             "platform.landing-rate-skus",
		Method:         "GET",
		Path:           "/api/platform/{platform}/landing-rate/skus",
		Summary:        "Landing-rate SKUs (blinkit/zepto/swiggy/bigbasket/flipkart_grocery only)",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "landing-rate-skus", "Landing-rate SKUs (blinkit/zepto/swiggy/bigbasket/flipkart_grocery only)", "/api/platform/{platform}/landing-rate/skus"),
	},
	{
		ID:             "platform.marketplace",
		Method:         "GET",
		Path:           "/api/platform/{platform}/mp-dashboard",
		Summary:        "Marketplace dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "marketplace", "Marketplace dashboard for a platform", "/api/platform/{platform}/mp-dashboard"),
	},
	{
		ID:             "platform.meta",
		Method:         "GET",
		Path:           "/api/platform/meta",
		Summary:        "Platform metadata (slugs, labels, config)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "meta", "Platform metadata (slugs, labels, config)", "/api/platform/meta"),
	},
	{
		ID:             "platform.month-on-month-sale",
		Method:         "GET",
		Path:           "/api/platform/{platform}/month-on-month-sale",
		Summary:        "Month-on-month sales for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "month-on-month-sale", "Month-on-month sales for a platform", "/api/platform/{platform}/month-on-month-sale"),
	},
	{
		ID:             "platform.month-targets",
		Method:         "GET",
		Path:           "/api/platform/{platform}/month-targets",
		Summary:        "Secondary monthly targets for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "month-targets", "Secondary monthly targets for a platform", "/api/platform/{platform}/month-targets"),
	},
	{
		ID:             "platform.month-targets-dashboard",
		Method:         "GET",
		Path:           "/api/platform/month-targets/dashboard",
		Summary:        "Secondary month-targets dashboard across platforms",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("platform", "month-targets-dashboard", "Secondary month-targets dashboard across platforms", "/api/platform/month-targets/dashboard"),
	},
	{
		ID:             "platform.mp-dashboard-version",
		Method:         "GET",
		Path:           "/api/platform/{platform}/mp-dashboard-version",
		Summary:        "Data version stamp for a platform marketplace dashboard",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "mp-dashboard-version", "Data version stamp for a platform marketplace dashboard", "/api/platform/{platform}/mp-dashboard-version"),
	},
	{
		ID:             "platform.pendency",
		Method:         "GET",
		Path:           "/api/platform/{platform}/pendency-dashboard",
		Summary:        "Order pendency dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "pendency", "Order pendency dashboard for a platform", "/api/platform/{platform}/pendency-dashboard"),
	},
	{
		ID:             "platform.pos",
		Method:         "GET",
		Path:           "/api/platform/{platform}/pos",
		Summary:        "Purchase orders for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "pos", "Purchase orders for a platform", "/api/platform/{platform}/pos"),
	},
	{
		ID:             "platform.price",
		Method:         "GET",
		Path:           "/api/platform/{platform}/price-dashboard",
		Summary:        "Pricing dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "price", "Pricing dashboard for a platform", "/api/platform/{platform}/price-dashboard"),
	},
	{
		ID:             "platform.primary",
		Method:         "GET",
		Path:           "/api/platform/{platform}/primary-dashboard",
		Summary:        "Primary (sell-in / PO) dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "primary", "Primary (sell-in / PO) dashboard for a platform", "/api/platform/{platform}/primary-dashboard"),
	},
	{
		ID:             "platform.primary-month-targets",
		Method:         "GET",
		Path:           "/api/platform/{platform}/primary-month-targets",
		Summary:        "Primary monthly targets for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "primary-month-targets", "Primary monthly targets for a platform", "/api/platform/{platform}/primary-month-targets"),
	},
	{
		ID:             "platform.primary-month-targets-dashboard",
		Method:         "GET",
		Path:           "/api/platform/primary-month-targets/dashboard",
		Summary:        "Primary month-targets dashboard across platforms",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("platform", "primary-month-targets-dashboard", "Primary month-targets dashboard across platforms", "/api/platform/primary-month-targets/dashboard"),
	},
	{
		ID:             "platform.primary-overview-total",
		Method:         "GET",
		Path:           "/api/platform/primary-overview-total",
		Summary:        "Primary overview totals across platforms",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("platform", "primary-overview-total", "Primary overview totals across platforms", "/api/platform/primary-overview-total"),
	},
	{
		ID:             "platform.primary-summary",
		Method:         "GET",
		Path:           "/api/platform/primary-summary",
		Summary:        "Primary sell-in summary across platforms",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("platform", "primary-summary", "Primary sell-in summary across platforms", "/api/platform/primary-summary"),
	},
	{
		ID:             "platform.primary-summary-version",
		Method:         "GET",
		Path:           "/api/platform/primary-summary-version",
		Summary:        "Data version stamp for the primary summary",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "primary-summary-version", "Data version stamp for the primary summary", "/api/platform/primary-summary-version"),
	},
	{
		ID:             "platform.region-doh",
		Method:         "GET",
		Path:           "/api/platform/{platform}/region-doh-dashboard",
		Summary:        "Region-wise days-of-health dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "region-doh", "Region-wise days-of-health dashboard for a platform", "/api/platform/{platform}/region-doh-dashboard"),
	},
	{
		ID:             "platform.secondary",
		Method:         "GET",
		Path:           "/api/platform/{platform}/sec-dashboard",
		Summary:        "Secondary (sell-out) dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "secondary", "Secondary (sell-out) dashboard for a platform", "/api/platform/{platform}/sec-dashboard"),
	},
	{
		ID:             "platform.secondary-monthly",
		Method:         "GET",
		Path:           "/api/platform/{platform}/sec-monthly-dashboard",
		Summary:        "Monthly secondary-sales dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "secondary-monthly", "Monthly secondary-sales dashboard for a platform", "/api/platform/{platform}/sec-monthly-dashboard"),
	},
	{
		ID:             "platform.secondary-years",
		Method:         "GET",
		Path:           "/api/platform/{platform}/sec-dashboard-years",
		Summary:        "Years available for the secondary dashboard",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "secondary-years", "Years available for the secondary dashboard", "/api/platform/{platform}/sec-dashboard-years"),
	},
	{
		ID:             "platform.soh-doh",
		Method:         "GET",
		Path:           "/api/platform/{platform}/soh-doh-dashboard",
		Summary:        "Stock-on-hand / days-of-health dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "soh-doh", "Stock-on-hand / days-of-health dashboard for a platform", "/api/platform/{platform}/soh-doh-dashboard"),
	},
	{
		ID:             "platform.stats",
		Method:         "GET",
		Path:           "/api/platform/{platform}/stats",
		Summary:        "Headline stats for a platform (inventory, sells, open POs, active trucks)",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "stats", "Headline stats for a platform (inventory, sells, open POs, active trucks)", "/api/platform/{platform}/stats"),
	},
	{
		ID:             "platform.swiggy-ads-daily-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/swiggy-ads-daily-dashboard",
		Summary:        "Swiggy Ads Daily Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "swiggy-ads-daily-dashboard", "Swiggy Ads Daily Dashboard for a platform", "/api/platform/{platform}/swiggy-ads-daily-dashboard"),
	},
	{
		ID:             "platform.swiggy-ads-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/swiggy-ads-dashboard",
		Summary:        "Swiggy Ads Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "swiggy-ads-dashboard", "Swiggy Ads Dashboard for a platform", "/api/platform/{platform}/swiggy-ads-dashboard"),
	},
	{
		ID:             "platform.swiggy-brandfund-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/swiggy-brandfund-dashboard",
		Summary:        "Swiggy Brandfund Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "swiggy-brandfund-dashboard", "Swiggy Brandfund Dashboard for a platform", "/api/platform/{platform}/swiggy-brandfund-dashboard"),
	},
	{
		ID:             "platform.zepto-ads-daily-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/zepto-ads-daily-dashboard",
		Summary:        "Zepto Ads Daily Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "zepto-ads-daily-dashboard", "Zepto Ads Daily Dashboard for a platform", "/api/platform/{platform}/zepto-ads-daily-dashboard"),
	},
	{
		ID:             "platform.zepto-ads-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/zepto-ads-dashboard",
		Summary:        "Zepto Ads Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "zepto-ads-dashboard", "Zepto Ads Dashboard for a platform", "/api/platform/{platform}/zepto-ads-dashboard"),
	},
	{
		ID:             "platform.zepto-brandfund-dashboard",
		Method:         "GET",
		Path:           "/api/platform/{platform}/zepto-brandfund-dashboard",
		Summary:        "Zepto Brandfund Dashboard for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("platform", "zepto-brandfund-dashboard", "Zepto Brandfund Dashboard for a platform", "/api/platform/{platform}/zepto-brandfund-dashboard"),
	},
	{
		ID:             "reports.amazon-po",
		Method:         "GET",
		Path:           "/api/reports/amazon-po",
		Summary:        "Amazon PO report",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("reports", "amazon-po", "Amazon PO report", "/api/reports/amazon-po"),
	},
	{
		ID:             "reports.amazon-po-filter-options",
		Method:         "GET",
		Path:           "/api/reports/amazon-po/filter-options",
		Summary:        "Filter options for the Amazon PO report",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("reports", "amazon-po-filter-options", "Filter options for the Amazon PO report", "/api/reports/amazon-po/filter-options"),
	},
	{
		ID:             "reports.amazon-po-matrix",
		Method:         "GET",
		Path:           "/api/reports/amazon-po/matrix",
		Summary:        "Amazon PO matrix (by month/year)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "month", WireName: "month"}, {PublicName: "year", WireName: "year"}},
		keywords:       codeOrchKeywords("reports", "amazon-po-matrix", "Amazon PO matrix (by month/year)", "/api/reports/amazon-po/matrix"),
	},
	{
		ID:             "reports.amazon-po-new-po",
		Method:         "GET",
		Path:           "/api/reports/amazon-po/new-po",
		Summary:        "Amazon new-PO report",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("reports", "amazon-po-new-po", "Amazon new-PO report", "/api/reports/amazon-po/new-po"),
	},
	{
		ID:             "reports.amazon-po-summary",
		Method:         "GET",
		Path:           "/api/reports/amazon-po/summary",
		Summary:        "Amazon PO report summary",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("reports", "amazon-po-summary", "Amazon PO report summary", "/api/reports/amazon-po/summary"),
	},
	{
		ID:             "reports.appointment",
		Method:         "GET",
		Path:           "/api/reports/appointment",
		Summary:        "Appointment report",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("reports", "appointment", "Appointment report", "/api/reports/appointment"),
	},
	{
		ID:             "reports.appointment-filter-options",
		Method:         "GET",
		Path:           "/api/reports/appointment/filter-options",
		Summary:        "Filter options (pos_numbers, destination_fcs) for the appointment report",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("reports", "appointment-filter-options", "Filter options (pos_numbers, destination_fcs) for the appointment report", "/api/reports/appointment/filter-options"),
	},
	{
		ID:             "reports.appointment-summary",
		Method:         "GET",
		Path:           "/api/reports/appointment/summary",
		Summary:        "Appointment report summary",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("reports", "appointment-summary", "Appointment report summary", "/api/reports/appointment/summary"),
	},
	{
		ID:             "reports.columns",
		Method:         "GET",
		Path:           "/api/reports/columns",
		Summary:        "Column definitions for a report view",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "view", WireName: "view"}},
		keywords:       codeOrchKeywords("reports", "columns", "Column definitions for a report view", "/api/reports/columns"),
	},
	{
		ID:             "reports.raw",
		Method:         "GET",
		Path:           "/api/reports/raw",
		Summary:        "Raw rows for a report view",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "view", WireName: "view"}, {PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("reports", "raw", "Raw rows for a report view", "/api/reports/raw"),
	},
	{
		ID:             "sap.distributor",
		Method:         "GET",
		Path:           "/api/sap/distributors/{code}",
		Summary:        "Get a distributor (profile, addresses, contacts) by card code",
		Positional:     []string{"code"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("sap", "distributor", "Get a distributor (profile, addresses, contacts) by card code", "/api/sap/distributors/{code}"),
	},
	{
		ID:             "sap.distributor-inventory",
		Method:         "GET",
		Path:           "/api/sap/distributor-inventory",
		Summary:        "Distributor inventory",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "distributor-inventory", "Distributor inventory", "/api/sap/distributor-inventory"),
	},
	{
		ID:             "sap.distributor-invoices",
		Method:         "GET",
		Path:           "/api/sap/distributor-invoices/{code}",
		Summary:        "Invoices for a distributor by card code",
		Positional:     []string{"code"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "distributor-invoices", "Invoices for a distributor by card code", "/api/sap/distributor-invoices/{code}"),
	},
	{
		ID:             "sap.distributor-orders",
		Method:         "GET",
		Path:           "/api/sap/distributor-orders/{code}",
		Summary:        "Orders for a distributor by card code",
		Positional:     []string{"code"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "distributor-orders", "Orders for a distributor by card code", "/api/sap/distributor-orders/{code}"),
	},
	{
		ID:             "sap.distributors",
		Method:         "GET",
		Path:           "/api/sap/distributors",
		Summary:        "List SAP distributors",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "distributors", "List SAP distributors", "/api/sap/distributors"),
	},
	{
		ID:             "sap.inventory-finished-goods",
		Method:         "GET",
		Path:           "/api/sap/inventory-finished-goods",
		Summary:        "Finished-goods inventory",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "inventory-finished-goods", "Finished-goods inventory", "/api/sap/inventory-finished-goods"),
	},
	{
		ID:             "sap.inventory-overview",
		Method:         "GET",
		Path:           "/api/sap/inventory-overview",
		Summary:        "Inventory overview",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("sap", "inventory-overview", "Inventory overview", "/api/sap/inventory-overview"),
	},
	{
		ID:             "sap.inventory-warehouse-comparison",
		Method:         "GET",
		Path:           "/api/sap/inventory-warehouse-comparison",
		Summary:        "Inventory comparison across warehouses",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("sap", "inventory-warehouse-comparison", "Inventory comparison across warehouses", "/api/sap/inventory-warehouse-comparison"),
	},
	{
		ID:             "sap.items",
		Method:         "GET",
		Path:           "/api/sap/items",
		Summary:        "SAP item master",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "items", "SAP item master", "/api/sap/items"),
	},
	{
		ID:             "sap.platform-distributor",
		Method:         "GET",
		Path:           "/api/sap/platform-distributors/{platform}/{code}",
		Summary:        "A platform-distributor mapping by card code",
		Positional:     []string{"platform", "code"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("sap", "platform-distributor", "A platform-distributor mapping by card code", "/api/sap/platform-distributors/{platform}/{code}"),
	},
	{
		ID:             "sap.platform-distributors",
		Method:         "GET",
		Path:           "/api/sap/platform-distributors/{platform}",
		Summary:        "Distributors mapped to a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "platform-distributors", "Distributors mapped to a platform", "/api/sap/platform-distributors/{platform}"),
	},
	{
		ID:             "sap.platform-sales-invoices",
		Method:         "GET",
		Path:           "/api/sap/platform-sales-invoices/{platform}",
		Summary:        "Sales invoices for a platform",
		Positional:     []string{"platform"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "platform-sales-invoices", "Sales invoices for a platform", "/api/sap/platform-sales-invoices/{platform}"),
	},
	{
		ID:             "sap.sales-analysis",
		Method:         "GET",
		Path:           "/api/sap/sales-analysis",
		Summary:        "Sales analysis over a date range",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "from_date", WireName: "from_date"}, {PublicName: "to_date", WireName: "to_date"}, {PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "sales-analysis", "Sales analysis over a date range", "/api/sap/sales-analysis"),
	},
	{
		ID:             "sap.sales-invoice",
		Method:         "GET",
		Path:           "/api/sap/sales-invoices/{id}",
		Summary:        "Get a sales invoice by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "sales-invoice", "Get a sales invoice by id", "/api/sap/sales-invoices/{id}"),
	},
	{
		ID:             "sap.sales-invoice-lines",
		Method:         "GET",
		Path:           "/api/sap/sales-invoice-lines/{id}",
		Summary:        "Line items for a sales invoice by id (note: upstream SAP query may 500)",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("sap", "sales-invoice-lines", "Line items for a sales invoice by id (note: upstream SAP query may 500)", "/api/sap/sales-invoice-lines/{id}"),
	},
	{
		ID:             "sap.sales-invoices",
		Method:         "GET",
		Path:           "/api/sap/sales-invoices",
		Summary:        "List SAP sales invoices",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "sales-invoices", "List SAP sales invoices", "/api/sap/sales-invoices"),
	},
	{
		ID:             "sap.stock-by-warehouse",
		Method:         "GET",
		Path:           "/api/sap/stock-by-warehouse",
		Summary:        "Stock levels by warehouse",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("sap", "stock-by-warehouse", "Stock levels by warehouse", "/api/sap/stock-by-warehouse"),
	},
	{
		ID:             "shipment.all-appointments",
		Method:         "GET",
		Path:           "/api/shipment/all-appointments",
		Summary:        "All shipment appointments",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "all-appointments", "All shipment appointments", "/api/shipment/all-appointments"),
	},
	{
		ID:             "shipment.appointment-commits",
		Method:         "GET",
		Path:           "/api/shipment/appointment-commits",
		Summary:        "Appointment commit records",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "appointment-commits", "Appointment commit records", "/api/shipment/appointment-commits"),
	},
	{
		ID:             "shipment.appointment-dates",
		Method:         "GET",
		Path:           "/api/shipment/appointments/dates",
		Summary:        "Available appointment dates",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "appointment-dates", "Available appointment dates", "/api/shipment/appointments/dates"),
	},
	{
		ID:             "shipment.appointment-extra-pos",
		Method:         "GET",
		Path:           "/api/shipment/appointments/{id}/extra-pos",
		Summary:        "Extra POs for an appointment",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "appointment-extra-pos", "Extra POs for an appointment", "/api/shipment/appointments/{id}/extra-pos"),
	},
	{
		ID:             "shipment.appointment-items",
		Method:         "GET",
		Path:           "/api/shipment/appointments/{id}/items",
		Summary:        "Items for an appointment",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "appointment-items", "Items for an appointment", "/api/shipment/appointments/{id}/items"),
	},
	{
		ID:             "shipment.appointments",
		Method:         "GET",
		Path:           "/api/shipment/appointments",
		Summary:        "Shipment appointments",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "appointments", "Shipment appointments", "/api/shipment/appointments"),
	},
	{
		ID:             "shipment.asin-catalog",
		Method:         "GET",
		Path:           "/api/shipment/asin-catalog",
		Summary:        "ASIN catalog",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "asin-catalog", "ASIN catalog", "/api/shipment/asin-catalog"),
	},
	{
		ID:             "shipment.inventory",
		Method:         "GET",
		Path:           "/api/shipment/inventory",
		Summary:        "Shipment planning inventory",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "inventory", "Shipment planning inventory", "/api/shipment/inventory"),
	},
	{
		ID:             "shipment.po-items",
		Method:         "GET",
		Path:           "/api/shipment/po-items",
		Summary:        "PO items available to ship",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "po-items", "PO items available to ship", "/api/shipment/po-items"),
	},
	{
		ID:             "shipment.po-shipment-lookup",
		Method:         "GET",
		Path:           "/api/shipment/po-shipment-lookup",
		Summary:        "Lookup shipments for a PO",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "po-shipment-lookup", "Lookup shipments for a PO", "/api/shipment/po-shipment-lookup"),
	},
	{
		ID:             "shipment.po-short-supply",
		Method:         "GET",
		Path:           "/api/shipment/po-short-supply",
		Summary:        "PO short-supply report",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "po-short-supply", "PO short-supply report", "/api/shipment/po-short-supply"),
	},
	{
		ID:             "shipment.record",
		Method:         "GET",
		Path:           "/api/shipment/record",
		Summary:        "Shipment record",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "record", "Shipment record", "/api/shipment/record"),
	},
	{
		ID:             "shipment.shipment",
		Method:         "GET",
		Path:           "/api/shipment/shipments/{id}",
		Summary:        "Get a shipment by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipment", "Get a shipment by id", "/api/shipment/shipments/{id}"),
	},
	{
		ID:             "shipment.shipment-invoice-file",
		Method:         "GET",
		Path:           "/api/shipment/shipments/{id}/invoices/{invoice}/file",
		Summary:        "Download an invoice file for a shipment",
		Positional:     []string{"id", "invoice"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipment-invoice-file", "Download an invoice file for a shipment", "/api/shipment/shipments/{id}/invoices/{invoice}/file"),
	},
	{
		ID:             "shipment.shipment-invoices",
		Method:         "GET",
		Path:           "/api/shipment/shipments/{id}/invoices",
		Summary:        "Invoices for a shipment",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipment-invoices", "Invoices for a shipment", "/api/shipment/shipments/{id}/invoices"),
	},
	{
		ID:             "shipment.shipment-po-document",
		Method:         "GET",
		Path:           "/api/shipment/shipments/{id}/po-documents/{document}",
		Summary:        "A PO document for a shipment",
		Positional:     []string{"id", "document"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipment-po-document", "A PO document for a shipment", "/api/shipment/shipments/{id}/po-documents/{document}"),
	},
	{
		ID:             "shipment.shipment-po-documents",
		Method:         "GET",
		Path:           "/api/shipment/shipments/{id}/po-documents",
		Summary:        "PO documents for a shipment",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipment-po-documents", "PO documents for a shipment", "/api/shipment/shipments/{id}/po-documents"),
	},
	{
		ID:             "shipment.shipments",
		Method:         "GET",
		Path:           "/api/shipment/shipments",
		Summary:        "List shipments",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipments", "List shipments", "/api/shipment/shipments"),
	},
	{
		ID:             "shipment.shipments-deletion-log",
		Method:         "GET",
		Path:           "/api/shipment/shipments/deletion-log",
		Summary:        "Shipment deletion log",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipments-deletion-log", "Shipment deletion log", "/api/shipment/shipments/deletion-log"),
	},
	{
		ID:             "shipment.shipments-doh-auto-fill",
		Method:         "GET",
		Path:           "/api/shipment/shipments/doh-auto-fill",
		Summary:        "DOH auto-fill suggestions",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipments-doh-auto-fill", "DOH auto-fill suggestions", "/api/shipment/shipments/doh-auto-fill"),
	},
	{
		ID:             "shipment.shipments-pending-approvals",
		Method:         "GET",
		Path:           "/api/shipment/shipments/pending-approvals",
		Summary:        "Shipments pending approval",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipments-pending-approvals", "Shipments pending approval", "/api/shipment/shipments/pending-approvals"),
	},
	{
		ID:             "shipment.shipments-stats",
		Method:         "GET",
		Path:           "/api/shipment/shipments/stats",
		Summary:        "Shipment stats",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("shipment", "shipments-stats", "Shipment stats", "/api/shipment/shipments/stats"),
	},
	{
		ID:             "tables.columns",
		Method:         "GET",
		Path:           "/api/dashboard/table-columns/{table}",
		Summary:        "Column definitions for a table",
		Positional:     []string{"table"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tables", "columns", "Column definitions for a table", "/api/dashboard/table-columns/{table}"),
	},
	{
		ID:             "tables.count",
		Method:         "GET",
		Path:           "/api/dashboard/table-count/{table}",
		Summary:        "Row count for a single table",
		Positional:     []string{"table"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tables", "count", "Row count for a single table", "/api/dashboard/table-count/{table}"),
	},
	{
		ID:             "tables.counts",
		Method:         "GET",
		Path:           "/api/dashboard/table-counts",
		Summary:        "Row counts for every available data table",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tables", "counts", "Row counts for every available data table", "/api/dashboard/table-counts"),
	},
	{
		ID:             "tables.data",
		Method:         "GET",
		Path:           "/api/dashboard/table-data/{table}",
		Summary:        "Paginated rows for a table (server-shaped payload)",
		Positional:     []string{"table"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("tables", "data", "Paginated rows for a table (server-shaped payload)", "/api/dashboard/table-data/{table}"),
	},
	{
		ID:             "tables.distinct",
		Method:         "GET",
		Path:           "/api/dashboard/table-distinct/{table}/{column}",
		Summary:        "Distinct values for a column in a table",
		Positional:     []string{"table", "column"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("tables", "distinct", "Distinct values for a column in a table", "/api/dashboard/table-distinct/{table}/{column}"),
	},
	{
		ID:             "upload.ads-master",
		Method:         "GET",
		Path:           "/api/upload/ads-master",
		Summary:        "Ads master sheet (columns, rows)",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("upload", "ads-master", "Ads master sheet (columns, rows)", "/api/upload/ads-master"),
	},
	{
		ID:             "upload.master-sheet",
		Method:         "GET",
		Path:           "/api/upload/master-sheet",
		Summary:        "Master sheet",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("upload", "master-sheet", "Master sheet", "/api/upload/master-sheet"),
	},
	{
		ID:             "upload.pincode-mapping",
		Method:         "GET",
		Path:           "/api/upload/pincode-mapping",
		Summary:        "Pincode mapping table",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("upload", "pincode-mapping", "Pincode mapping table", "/api/upload/pincode-mapping"),
	},
	{
		ID:             "uploads.get",
		Method:         "GET",
		Path:           "/api/uploads/{id}",
		Summary:        "Get an upload job (summary, errors, diagnostics) by id",
		Positional:     []string{"id"},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{},
		keywords:       codeOrchKeywords("uploads", "get", "Get an upload job (summary, errors, diagnostics) by id", "/api/uploads/{id}"),
	},
	{
		ID:             "uploads.list",
		Method:         "GET",
		Path:           "/api/uploads",
		Summary:        "List upload jobs",
		Positional:     []string{},
		TemplateParams: []codeOrchParamBinding{},
		QueryParams:    []codeOrchParamBinding{{PublicName: "page", WireName: "page"}, {PublicName: "page-size", WireName: "page_size"}},
		keywords:       codeOrchKeywords("uploads", "list", "List upload jobs", "/api/uploads"),
	},
}

// codeOrchStopwords filters two-letter and short common-word substrings
// that pollute ranking via the substring-contains rule. Without them, a
// search for "list links" matches every endpoint whose description
// contains "is enrolled" because "is" is two chars and the matcher
// accepts kw.contains(t) || t.contains(kw).
var codeOrchStopwords = map[string]bool{
	"a": true, "an": true, "and": true, "are": true, "as": true,
	"at": true, "be": true, "by": true, "for": true, "from": true,
	"has": true, "in": true, "is": true, "it": true, "its": true,
	"of": true, "on": true, "or": true, "that": true, "the": true,
	"this": true, "to": true, "was": true, "will": true, "with": true,
	"your": true, "you": true, "any": true, "all": true,
}

// codeOrchKeywords produces the lowercase token stream used for search
// ranking. Defined at package level so the registry initializer can call it
// inline above without pulling in a separate precompute step.
func codeOrchKeywords(resource, endpoint, summary, path string) []string {
	raw := strings.ToLower(resource + " " + endpoint + " " + summary + " " + path)
	raw = strings.Map(func(r rune) rune {
		switch r {
		case '_', '-', '/', '{', '}', '.', ',', ':', ';':
			return ' '
		}
		return r
	}, raw)
	out := make([]string, 0, 16)
	seen := map[string]bool{}
	for _, tok := range strings.Fields(raw) {
		if len(tok) < 3 || codeOrchStopwords[tok] || seen[tok] {
			continue
		}
		seen[tok] = true
		out = append(out, tok)
	}
	return out
}

func handleCodeOrchSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || strings.TrimSpace(query) == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}
	limit := 10
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	terms := codeOrchKeywords("", "", query, "")
	type scored struct {
		ep    *codeOrchEndpoint
		score int
	}
	results := make([]scored, 0, len(codeOrchEndpoints))
	for i := range codeOrchEndpoints {
		ep := &codeOrchEndpoints[i]
		score := 0
		for _, t := range terms {
			for _, kw := range ep.keywords {
				if kw == t {
					score += 2
				} else if strings.Contains(kw, t) || strings.Contains(t, kw) {
					score++
				}
			}
		}
		if score > 0 {
			results = append(results, scored{ep: ep, score: score})
		}
	}
	sort.SliceStable(results, func(i, j int) bool { return results[i].score > results[j].score })
	if len(results) > limit {
		results = results[:limit]
	}

	out := make([]map[string]any, 0, len(results))
	for _, r := range results {
		out = append(out, map[string]any{
			"endpoint_id": r.ep.ID,
			"method":      r.ep.Method,
			"path":        r.ep.Path,
			"summary":     r.ep.Summary,
			"score":       r.score,
		})
	}
	data, _ := json.Marshal(map[string]any{"count": len(out), "results": out})
	return mcplib.NewToolResultText(string(data)), nil
}

func handleCodeOrchExecute(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	id, ok := args["endpoint_id"].(string)
	if !ok || id == "" {
		return mcplib.NewToolResultError("endpoint_id is required (call jivo-ecom_search first)"), nil
	}

	var ep *codeOrchEndpoint
	for i := range codeOrchEndpoints {
		if codeOrchEndpoints[i].ID == id {
			ep = &codeOrchEndpoints[i]
			break
		}
	}
	if ep == nil {
		return mcplib.NewToolResultError(fmt.Sprintf("unknown endpoint_id %q — call jivo-ecom_search to discover valid ids", id)), nil
	}

	params, _ := args["params"].(map[string]any)
	if params == nil {
		params = map[string]any{}
	}

	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path := ep.Path
	for _, p := range ep.Positional {
		if v, ok := params[p]; ok {
			path = strings.ReplaceAll(path, "{"+p+"}", formatMCPParamValue(v))
			delete(params, p)
		}
	}

	// Route params to their runtime slots. GET/DELETE params are query
	// strings; write methods split spec-declared query params from the
	// remaining params used as the request body below.
	query := map[string]string{}
	if ep.Method == "GET" || ep.Method == "DELETE" {
		for k, v := range params {
			query[codeOrchWireQueryName(ep.QueryParams, k)] = formatMCPParamValue(v)
		}
	} else {
		// Route spec-declared in:query params to the query string for write
		// methods too. Without this, a query param (e.g. sendToLedger on
		// PUT /ledger/voucher/{id}) wrongly lands in the JSON body and the
		// API silently ignores it or rejects the request. The remaining
		// params stay in the map for codeOrchWriteBody (the JSON body).
		if enc := codeOrchSplitQuery(ep.QueryParams, params); enc != "" {
			sep := "?"
			if strings.Contains(path, "?") {
				sep = "&"
			}
			path += sep + enc
		}
	}

	hdrs := ep.HeaderOverrides
	writeBody := func() any {
		if ep.BodyIsArray {
			return codeOrchArrayBody(params)
		}
		return codeOrchWriteBody(params)
	}
	var data json.RawMessage
	switch ep.Method {
	case "GET":
		if len(hdrs) > 0 {
			data, err = c.GetWithHeaders(ctx, path, query, hdrs)
		} else {
			data, err = c.Get(ctx, path, query)
		}
	case "DELETE":
		if len(hdrs) > 0 {
			data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, query, hdrs)
		} else {
			data, _, err = c.DeleteWithParams(ctx, path, query)
		}
	case "POST":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PostWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Post(ctx, path, body)
		}
	case "PUT":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PutWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Put(ctx, path, body)
		}
	case "PATCH":
		body := writeBody()
		if len(hdrs) > 0 {
			data, _, err = c.PatchWithHeaders(ctx, path, body, hdrs)
		} else {
			data, _, err = c.Patch(ctx, path, body)
		}
	default:
		return mcplib.NewToolResultError(fmt.Sprintf("unsupported method %q", ep.Method)), nil
	}
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcplib.NewToolResultText(string(data)), nil
}

// codeOrchWriteBody returns the value handed to the client layer as the
// request body for write methods (POST/PUT/PATCH). It MUST be the structured
// params map, never pre-marshaled bytes.
//
// client.do() marshals the body value exactly once. Handing it []byte makes
// json.Marshal([]byte) emit a base64-encoded JSON *string*, so the API
// receives "eyJ...==" where it expects the request object. Strict JSON APIs
// reject that as the wrong type at the body root. GET/DELETE carry no body,
// so this defect stays latent until the first write attempt.
func codeOrchWriteBody(params map[string]any) any {
	return params
}

// codeOrchArrayBody returns the request body for endpoints whose schema root
// is a bare top-level JSON array (ep.BodyIsArray). Such a body cannot be
// expressed as the params object, so the agent supplies the array under the
// conventional params key "body" (these endpoints have no flattened named
// params, so there is no collision risk). When present and array-shaped it is
// sent as the top-level array the API expects. Otherwise params is returned
// unchanged so a malformed call fails loudly at the API (HTTP 422) instead of
// silently sending the wrong shape or a partial write — financial mutations
// are never retried with body-variant guesses (broken-convenience guardrail).
func codeOrchArrayBody(params map[string]any) any {
	if v, ok := params["body"]; ok {
		if arr, ok := v.([]any); ok {
			return arr
		}
	}
	return params
}

// codeOrchSplitQuery removes spec-declared in:query params from params and
// returns them URL-encoded for appending to the request path. The remaining
// entries stay in the map for codeOrchWriteBody (the JSON body), so a write
// method's query parameters never get buried in the body. Mutates params by
// design (deletes the consumed query keys).
func codeOrchSplitQuery(queryParams []codeOrchParamBinding, params map[string]any) string {
	uv := neturl.Values{}
	for _, q := range queryParams {
		for _, key := range []string{q.PublicName, q.WireName} {
			if key == "" {
				continue
			}
			if v, ok := params[key]; ok {
				uv.Set(q.WireName, formatMCPParamValue(v))
				delete(params, key)
				break
			}
		}
	}
	return uv.Encode()
}

func codeOrchWireQueryName(queryParams []codeOrchParamBinding, name string) string {
	for _, q := range queryParams {
		if q.PublicName == name || q.WireName == name {
			return q.WireName
		}
	}
	return name
}
