SELECT
  "ItemCode",
  "Warehouse",
  ROUND(TO_DOUBLE(SUM(CASE WHEN "DocDate" > LAST_DAY(ADD_MONTHS(CURRENT_DATE, -6)) THEN "InQty" - "OutQty" ELSE 0 END)), 2) AS "NET_AFTER_1",
  ROUND(TO_DOUBLE(SUM(CASE WHEN "DocDate" > LAST_DAY(ADD_MONTHS(CURRENT_DATE, -5)) THEN "InQty" - "OutQty" ELSE 0 END)), 2) AS "NET_AFTER_2",
  ROUND(TO_DOUBLE(SUM(CASE WHEN "DocDate" > LAST_DAY(ADD_MONTHS(CURRENT_DATE, -4)) THEN "InQty" - "OutQty" ELSE 0 END)), 2) AS "NET_AFTER_3",
  ROUND(TO_DOUBLE(SUM(CASE WHEN "DocDate" > LAST_DAY(ADD_MONTHS(CURRENT_DATE, -3)) THEN "InQty" - "OutQty" ELSE 0 END)), 2) AS "NET_AFTER_4",
  ROUND(TO_DOUBLE(SUM(CASE WHEN "DocDate" > LAST_DAY(ADD_MONTHS(CURRENT_DATE, -2)) THEN "InQty" - "OutQty" ELSE 0 END)), 2) AS "NET_AFTER_5",
  ROUND(TO_DOUBLE(SUM(CASE WHEN "DocDate" > LAST_DAY(ADD_MONTHS(CURRENT_DATE, -1)) THEN "InQty" - "OutQty" ELSE 0 END)), 2) AS "NET_AFTER_6"
FROM JIVO_BEVERAGES_HANADB.OINM
WHERE "DocDate" > LAST_DAY(ADD_MONTHS(CURRENT_DATE, -6))
GROUP BY "ItemCode", "Warehouse"
ORDER BY "ItemCode", "Warehouse"
