package main

// endpoints_gen.go — AUTO-GENERATED read-only allowlist. READ/READ_FILE only, no write-verb segment.

type Endpoint struct {
	Section string
	Name    string
	Host    string
	Path    string
	Class   string
	Params  string
}

var readEndpoints = []Endpoint{
	{Section: "Account-Health-Performance", Name: "ahd-floatingwidget", Host: "sellercentral.amazon.in", Path: "/ahd/floatingWidget", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "ahd-issuetypetags", Host: "sellercentral.amazon.in", Path: "/ahd/issueTypeTags", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "ahd-priorityactions", Host: "sellercentral.amazon.in", Path: "/ahd/priorityActions", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "appeal-appeals-csrf", Host: "sellercentral.amazon.in", Path: "/appeal/appeals/csrf", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "pcrhealth-download", Host: "sellercentral.amazon.in", Path: "/pcrHealth/download", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "pcrhealth-pcrkpi", Host: "sellercentral.amazon.in", Path: "/pcrHealth/pcrKpi", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "pcrhealth-pcrlistingsummary", Host: "sellercentral.amazon.in", Path: "/pcrHealth/pcrListingSummary", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "performance-getriskbanner", Host: "sellercentral.amazon.in", Path: "/performance/api/getriskbanner/", Class: "READ", Params: ""},
	{Section: "Account-Health-Performance", Name: "performance-summary", Host: "sellercentral.amazon.in", Path: "/performance/api/summary", Class: "READ", Params: ""},
	{Section: "Business-Reports-Analytics", Name: "reportcentral-getrecentlyvisitedreports", Host: "sellercentral.amazon.in", Path: "/reportcentral/api/v1/getRecentlyVisitedReports", Class: "READ", Params: ""},
	{Section: "Business-Reports-Analytics", Name: "reportcentral-getreportconfigurations", Host: "sellercentral.amazon.in", Path: "/reportcentral/api/v1/getReportConfigurations", Class: "READ", Params: ""},
	{Section: "Business-Reports-Analytics", Name: "reportcentral-getreportpreferences", Host: "sellercentral.amazon.in", Path: "/reportcentral/api/v1/getReportPreferences", Class: "READ", Params: ""},
	{Section: "Business-Reports-Analytics", Name: "reportcentral-getwhatsnewconfiguration", Host: "sellercentral.amazon.in", Path: "/reportcentral/api/v1/getWhatsNewConfiguration", Class: "READ", Params: ""},
	{Section: "Coupons-Promotions", Name: "coupons-banners", Host: "sellercentral.amazon.in", Path: "/coupons/api/banners", Class: "READ", Params: ""},
	{Section: "Coupons-Promotions", Name: "coupons-config", Host: "sellercentral.amazon.in", Path: "/coupons/api/config", Class: "READ", Params: ""},
	{Section: "Coupons-Promotions", Name: "coupons-getcouponpromotions", Host: "sellercentral.amazon.in", Path: "/coupons/api/getCouponPromotions", Class: "READ", Params: ""},
	{Section: "Coupons-Promotions", Name: "coupons-merchantinfo", Host: "sellercentral.amazon.in", Path: "/coupons/api/merchantInfo", Class: "READ", Params: ""},
	{Section: "Coupons-Promotions", Name: "coupons-tailoring", Host: "sellercentral.amazon.in", Path: "/coupons/api/tailoring", Class: "READ", Params: ""},
	{Section: "Coupons-Promotions", Name: "promotion-central-settings", Host: "sellercentral.amazon.in", Path: "/promotion-central/api/v1/settings", Class: "READ", Params: ""},
	{Section: "Feedback-Manager", Name: "fbmapi-aggregates", Host: "sellercentral.amazon.in", Path: "/fbmapi/v1/aggregates", Class: "READ", Params: ""},
	{Section: "Feedback-Manager", Name: "fbmapi-csrf", Host: "sellercentral.amazon.in", Path: "/fbmapi/v1/csrf", Class: "READ", Params: ""},
	{Section: "Feedback-Manager", Name: "fbmapi-feedbacks", Host: "sellercentral.amazon.in", Path: "/fbmapi/v1/feedbacks", Class: "READ", Params: ""},
	{Section: "Feedback-Manager", Name: "fbmapi-metadata", Host: "sellercentral.amazon.in", Path: "/fbmapi/v1/metadata", Class: "READ", Params: ""},
	{Section: "Feedback-Manager", Name: "fbmapi-orderperformancesellerbar", Host: "sellercentral.amazon.in", Path: "/fbmapi/v1/orderperformanceSellerBar", Class: "READ", Params: ""},
	{Section: "Feedback-Manager", Name: "fbmapi-orderperformanceuiversions", Host: "sellercentral.amazon.in", Path: "/fbmapi/v1/orderperformanceUIVersions", Class: "READ", Params: ""},
	{Section: "Global-Selling-Expansion", Name: "account-switcher-global-and-regional-account-merchantmarketplace", Host: "sellercentral.amazon.in", Path: "/account-switcher/global-and-regional-account/merchantMarketplace", Class: "READ", Params: ""},
	{Section: "Global-Selling-Expansion", Name: "meld-mons-api-getmarketplaceswitcher", Host: "sellercentral.amazon.in", Path: "/meld/mons-api/GetMarketplaceSwitcher", Class: "READ", Params: ""},
	{Section: "Global-Selling-Expansion", Name: "multi-channel-listings-catalogs", Host: "sellercentral.amazon.in", Path: "/multi-channel/listings/api/catalogs", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "communities-seller-news-articles", Host: "sellercentral.amazon.in", Path: "/communities/seller-news/articles", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "cu-case-lobby", Host: "sellercentral.amazon.in", Path: "/cu/case-lobby", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "cu-contact-us", Host: "sellercentral.amazon.in", Path: "/cu/contact-us", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "forums-index-jspa", Host: "sellercentral.amazon.in", Path: "/forums/index.jspa", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "forums-t", Host: "sellercentral.amazon.in", Path: "/forums/t/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help", Host: "sellercentral.amazon.in", Path: "/gp/help/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-customer", Host: "sellercentral.amazon.in", Path: "/gp/help/customer/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-external", Host: "sellercentral.amazon.in", Path: "/gp/help/external", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-external-2", Host: "sellercentral.amazon.in", Path: "/gp/help/external/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-help-content-html", Host: "sellercentral.amazon.in", Path: "/gp/help/external/help-content.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-help-folder-html", Host: "sellercentral.amazon.in", Path: "/gp/help/external/help-folder.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-help-home-html", Host: "sellercentral.amazon.in", Path: "/gp/help/external/help-home.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-help-page-html", Host: "sellercentral.amazon.in", Path: "/gp/help/external/help-page.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-help-html", Host: "sellercentral.amazon.in", Path: "/gp/help/external/help.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-home", Host: "sellercentral.amazon.in", Path: "/gp/help/external/home", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-home-html", Host: "sellercentral.amazon.in", Path: "/gp/help/external/home.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-login-help-html", Host: "sellercentral.amazon.in", Path: "/gp/help/external/login-help.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-external-id", Host: "sellercentral.amazon.in", Path: "/gp/help/external/{guid}/", Class: "READ", Params: "guid"},
	{Section: "Help-Support-Center", Name: "gp-help-help-content-html", Host: "sellercentral.amazon.in", Path: "/gp/help/help-content.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-help-folder-html", Host: "sellercentral.amazon.in", Path: "/gp/help/help-folder.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-help-home-html", Host: "sellercentral.amazon.in", Path: "/gp/help/help-home.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-help-page-html", Host: "sellercentral.amazon.in", Path: "/gp/help/help-page.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-help-popup-html", Host: "sellercentral.amazon.in", Path: "/gp/help/help-popup.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-help-html", Host: "sellercentral.amazon.in", Path: "/gp/help/help.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-home", Host: "sellercentral.amazon.in", Path: "/gp/help/home", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-home-html", Host: "sellercentral.amazon.in", Path: "/gp/help/home.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-login-help-html", Host: "sellercentral.amazon.in", Path: "/gp/help/login-help.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "gp-help-id", Host: "sellercentral.amazon.in", Path: "/gp/help/{guid}/", Class: "READ", Params: "guid"},
	{Section: "Help-Support-Center", Name: "center-inline-workflow", Host: "sellercentral.amazon.in", Path: "/help/center/inline/workflow", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-getting-started-guide", Host: "sellercentral.amazon.in", Path: "/help/getting-started-guide", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-getting-started-selling-faq", Host: "sellercentral.amazon.in", Path: "/help/getting-started-selling-faq", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-home", Host: "sellercentral.amazon.in", Path: "/help/home", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-hub", Host: "sellercentral.amazon.in", Path: "/help/hub/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-hub-debug", Host: "sellercentral.amazon.in", Path: "/help/hub/debug", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-hub-inline", Host: "sellercentral.amazon.in", Path: "/help/hub/inline", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "hub-mons-api-getbootstrapdata", Host: "sellercentral.amazon.in", Path: "/help/hub/mons-api/GetBootstrapData", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "hub-mons-api-getfeaturestatus", Host: "sellercentral.amazon.in", Path: "/help/hub/mons-api/GetFeatureStatus", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "hub-mons-api-getmeldeligibility", Host: "sellercentral.amazon.in", Path: "/help/hub/mons-api/GetMeldEligibility", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-hub-reference", Host: "sellercentral.amazon.in", Path: "/help/hub/reference/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "hub-reference-external", Host: "sellercentral.amazon.in", Path: "/help/hub/reference/external/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "reference-external-login-help", Host: "sellercentral.amazon.in", Path: "/help/hub/reference/external/login-help", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-hub-support", Host: "sellercentral.amazon.in", Path: "/help/hub/support", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "inline-athena-get-direct-answer-embed", Host: "sellercentral.amazon.in", Path: "/help/inline/athena-get-direct-answer/embed", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-manage-inventory-tool", Host: "sellercentral.amazon.in", Path: "/help/manage-inventory-tool", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-manage-orders", Host: "sellercentral.amazon.in", Path: "/help/manage-orders", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "merchant-documents-text-sign-in-html", Host: "sellercentral.amazon.in", Path: "/help/merchant_documents/text/sign-in.html", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "workflow-bulk-embed", Host: "sellercentral.amazon.in", Path: "/help/workflow/bulk/embed", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-workflow-embed", Host: "sellercentral.amazon.in", Path: "/help/workflow/embed", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "help-workflow-spl-setup", Host: "sellercentral.amazon.in", Path: "/help/workflow/spl-setup", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "hillservice-mons-api-getbootstrapconfig", Host: "sellercentral.amazon.in", Path: "/hill/hillservice/mons-api/GetBootstrapConfig", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "hillservice-mons-api-getspecialistsupportingresseligibility", Host: "sellercentral.amazon.in", Path: "/hill/hillservice/mons-api/GetSpecialistSupportIngressEligibility", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "reference-external", Host: "sellercentral.amazon.in", Path: "/reference/external", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "reference-external-login-help-2", Host: "sellercentral.amazon.in", Path: "/reference/external/login-help", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "reference-login-help", Host: "sellercentral.amazon.in", Path: "/reference/login-help/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "reference-search", Host: "sellercentral.amazon.in", Path: "/reference/search", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "roboapi-sc-announcements", Host: "sellercentral.amazon.in", Path: "/roboapi/v1/sc/announcements", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "solution-bulk-workflow", Host: "sellercentral.amazon.in", Path: "/solution/bulk-workflow", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "support-soa", Host: "sellercentral.amazon.in", Path: "/support/SOA", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "support-describe", Host: "sellercentral.amazon.in", Path: "/support/describe", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "support-form-hub", Host: "sellercentral.amazon.in", Path: "/support/form/hub", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "support-help-hub", Host: "sellercentral.amazon.in", Path: "/support/help/hub", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "support-help-node", Host: "sellercentral.amazon.in", Path: "/support/help/node/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "support-search", Host: "sellercentral.amazon.in", Path: "/support/search/", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "support-training-hub", Host: "sellercentral.amazon.in", Path: "/support/training/hub", Class: "READ", Params: ""},
	{Section: "Help-Support-Center", Name: "json-favorites-sellercentral", Host: "sellercentral.amazon.in", Path: "/trim/json/favorites/sellerCentral", Class: "READ", Params: ""},
	{Section: "Homepage-Widgets", Name: "cards-content-async-card", Host: "sellercentral.amazon.in", Path: "/homepage/casino/cards/content/async-card/", Class: "READ", Params: ""},
	{Section: "Inventory-FBA", Name: "fba-gstreports-report-history", Host: "sellercentral.amazon.in", Path: "/fba/gstreports/report-history", Class: "READ", Params: ""},
	{Section: "Inventory-FBA", Name: "inventoryplanning-check-unread-message", Host: "sellercentral.amazon.in", Path: "/inventoryplanning/check-unread-message", Class: "READ", Params: ""},
	{Section: "Inventory-FBA", Name: "inventoryplanning-stranded-inventory-autoremovalsettings", Host: "sellercentral.amazon.in", Path: "/inventoryplanning/stranded-inventory/autoRemovalSettings", Class: "READ", Params: ""},
	{Section: "Listings-ASIN-Management", Name: "abis-index-html", Host: "sellercentral.amazon.in", Path: "/abis/index.html", Class: "READ", Params: ""},
	{Section: "Listings-ASIN-Management", Name: "drafts-get", Host: "sellercentral.amazon.in", Path: "/drafts/api/get", Class: "READ", Params: ""},
	{Section: "Listings-ASIN-Management", Name: "drafts-getcontributors", Host: "sellercentral.amazon.in", Path: "/drafts/api/getContributors", Class: "READ", Params: ""},
	{Section: "Listings-ASIN-Management", Name: "lyp-enabledfeatures", Host: "sellercentral.amazon.in", Path: "/lyp/api/enabledFeatures", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "conversation-api-notifications", Host: "sellercentral.amazon.in", Path: "/conversation-api/v1/notifications", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "conversation-api-sidebarcontext", Host: "sellercentral.amazon.in", Path: "/conversation-api/v1/sidebarContext", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "messaging-global-cases", Host: "sellercentral.amazon.in", Path: "/messaging/api/global/cases", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "cases-id-ordercontext", Host: "sellercentral.amazon.in", Path: "/messaging/api/global/cases/{uuid}/orderContext", Class: "READ", Params: "uuid"},
	{Section: "Messaging-Buyer-Seller", Name: "cases-id-responsetemplates", Host: "sellercentral.amazon.in", Path: "/messaging/api/global/cases/{uuid}/responsetemplates", Class: "READ", Params: "uuid"},
	{Section: "Messaging-Buyer-Seller", Name: "messaging-global-partneraccounts", Host: "sellercentral.amazon.in", Path: "/messaging/api/global/partnerAccounts", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "global-partneraccounts-marketplaces", Host: "sellercentral.amazon.in", Path: "/messaging/api/global/partnerAccounts/marketplaces", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "messaging-global-rights", Host: "sellercentral.amazon.in", Path: "/messaging/api/global/rights", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "global-topics-categories", Host: "sellercentral.amazon.in", Path: "/messaging/api/global/topics/categories", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "messaging-inbox", Host: "sellercentral.amazon.in", Path: "/messaging/inbox", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "overview-metric-contactsreportedunresolved", Host: "sellercentral.amazon.in", Path: "/messaging/overview/api/metric/contactsReportedUnresolved", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "overview-metric-contactsrequireattention", Host: "sellercentral.amazon.in", Path: "/messaging/overview/api/metric/contactsRequireAttention", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "overview-metric-contactsresolved", Host: "sellercentral.amazon.in", Path: "/messaging/overview/api/metric/contactsResolved", Class: "READ", Params: ""},
	{Section: "Messaging-Buyer-Seller", Name: "overview-metric-contactsresponseneeded", Host: "sellercentral.amazon.in", Path: "/messaging/overview/api/metric/contactsResponseNeeded", Class: "READ", Params: ""},
	{Section: "Orders", Name: "orders-api-adconfig", Host: "sellercentral.amazon.in", Path: "/orders-api/adConfig", Class: "READ", Params: ""},
	{Section: "Orders", Name: "orders-api-manifest-v3", Host: "sellercentral.amazon.in", Path: "/orders-api/manifest-v3", Class: "READ", Params: ""},
	{Section: "Orders", Name: "orders-api-manifest-v3-quick-filters", Host: "sellercentral.amazon.in", Path: "/orders-api/manifest-v3/quick-filters", Class: "READ", Params: ""},
	{Section: "Orders", Name: "orders-api-notifications-myo-list-orders-easyship", Host: "sellercentral.amazon.in", Path: "/orders-api/notifications/MYO_LIST_ORDERS_EASYSHIP", Class: "READ", Params: ""},
	{Section: "Orders", Name: "orders-api-prefs-table-content", Host: "sellercentral.amazon.in", Path: "/orders-api/prefs/table-content", Class: "READ", Params: ""},
	{Section: "Orders", Name: "orders-api-search", Host: "sellercentral.amazon.in", Path: "/orders-api/search", Class: "READ", Params: ""},
	{Section: "Platform-Common", Name: "draft-dashboard", Host: "sellercentral.amazon.in", Path: "/draft/dashboard", Class: "READ", Params: ""},
	{Section: "Platform-Common", Name: "draft-registration-dashboard", Host: "sellercentral.amazon.in", Path: "/draft/registration/dashboard", Class: "READ", Params: ""},
	{Section: "Platform-Common", Name: "gp-satisfaction-survey-form-frame-html", Host: "sellercentral.amazon.in", Path: "/gp/satisfaction/survey-form-frame.html", Class: "READ", Params: ""},
	{Section: "Platform-Common", Name: "gp-satisfaction-survey-submit-html", Host: "sellercentral.amazon.in", Path: "/gp/satisfaction/survey-submit.html", Class: "READ", Params: ""},
	{Section: "Platform-Common", Name: "home", Host: "sellercentral.amazon.in", Path: "/home", Class: "READ", Params: ""},
	{Section: "Product-Classification", Name: "productclassify-browse", Host: "sellercentral.amazon.in", Path: "/productclassify/api/browse", Class: "READ", Params: ""},
	{Section: "Product-Classification", Name: "productclassify-favorites", Host: "sellercentral.amazon.in", Path: "/productclassify/api/favorites", Class: "READ", Params: ""},
	{Section: "Product-Classification", Name: "productclassify-index-html", Host: "sellercentral.amazon.in", Path: "/productclassify/index.html", Class: "READ", Params: ""},
	{Section: "Purchase-Orders", Name: "po-api-homepage-homepage-asn-discrepancies", Host: "www.vendorcentral.in", Path: "/po-api/vendor/homepage/homepage-asn-discrepancies", Class: "READ", Params: ""},
	{Section: "Purchase-Orders", Name: "po-api-homepage-homepage-confirmation", Host: "www.vendorcentral.in", Path: "/po-api/vendor/homepage/homepage-confirmation", Class: "READ", Params: ""},
	{Section: "Purchase-Orders", Name: "po-api-homepage-homepage-recently-modified", Host: "www.vendorcentral.in", Path: "/po-api/vendor/homepage/homepage-recently-modified", Class: "READ", Params: ""},
	{Section: "Purchase-Orders", Name: "po-po-mgmt-dashboard", Host: "www.vendorcentral.in", Path: "/po/vendor/members/po-mgmt/dashboard", Class: "READ", Params: ""},
	{Section: "Purchase-Orders", Name: "po-po-mgmt-managepos", Host: "www.vendorcentral.in", Path: "/po/vendor/members/po-mgmt/managepos", Class: "READ", Params: ""},
	{Section: "Retail-Analytics-ARA", Name: "analytics-dashboard-vendoranalytics", Host: "www.vendorcentral.in", Path: "/analytics/dashboard/vendorAnalytics", Class: "READ", Params: ""},
	{Section: "Retail-Analytics-ARA", Name: "retail-analytics-dashboard-sales", Host: "www.vendorcentral.in", Path: "/retail-analytics/dashboard/sales", Class: "READ", Params: ""},
	{Section: "VC-Catalog-Products", Name: "products-details", Host: "www.vendorcentral.in", Path: "/hz/vendor/members/products/details", Class: "READ", Params: ""},
	{Section: "VC-Catalog-Products", Name: "products-mycatalog", Host: "www.vendorcentral.in", Path: "/hz/vendor/members/products/mycatalog", Class: "READ", Params: ""},
	{Section: "VC-Catalog-Products", Name: "products-prismo-getcsrftoken", Host: "www.vendorcentral.in", Path: "/hz/vendor/members/products/prismo/api/getcsrftoken", Class: "READ", Params: ""},
	{Section: "VC-Support-Help", Name: "support-hub", Host: "sellercentral.amazon.in", Path: "/hz/vendor/members/support/hub", Class: "READ", Params: ""},
	{Section: "VC-Support-Help", Name: "support-hub-2", Host: "www.vendorcentral.in", Path: "/hz/vendor/members/support/hub", Class: "READ", Params: ""},
}
